"""Routing data schemas for the voice-assistant channel."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class RouteRequest(BaseModel):
    """Inbound route request (body of a `voice.route` envelope)."""

    text: str
    thread_id: str
    message_id: str | None = None
    platform: str = "macos"


class RouteDecision(BaseModel):
    """Result of the router: where to dispatch and with what params."""

    status: str = "routed"  # routed | delegate
    target_type: str = "agent"  # local | skill | macro | agent
    target: dict[str, Any] = Field(default_factory=dict)
    params: dict[str, Any] = Field(default_factory=dict)
    raw: str | None = None  # raw model output for debugging


class VoiceInitSpec(BaseModel):
    """Dynamic Layer-0 data generated by the backend and shipped to the client."""

    version: str
    actions: list[dict[str, Any]] = Field(default_factory=list)
    templates: list[dict[str, Any]] = Field(default_factory=list)
    slot_dictionaries: dict[str, Any] = Field(default_factory=dict)
    aliases: dict[str, str] = Field(default_factory=dict)
    default_apps: dict[str, str] = Field(default_factory=dict)
    app_usage_rank: list[str] = Field(default_factory=list)
    capabilities: dict[str, Any] = Field(default_factory=dict)
    preferences: dict[str, Any] = Field(default_factory=dict)
