from datetime import datetime

from sqlalchemy import JSON, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database.sql.database import Base
from app.utils.time import utcnow


class TraceEvent(Base):
    """
    Represents a high-fidelity snapshot of agent execution for Imitation Learning.
    Stores State -> Action tuples.

    Supports both:
    - Agent actions (LLM/tool calls, automatically captured)
    - Human actions (UI interactions, captured via frontend ActionRecorder)
    """

    __tablename__ = "trace_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Session Tracking
    thread_id: Mapped[str] = mapped_column(String(255), index=True)
    session_id: Mapped[str | None] = mapped_column(String(36), index=True, nullable=True) # Unified session/thread ID
    run_id: Mapped[str | None] = mapped_column(String(36), index=True, nullable=True)
    step_number: Mapped[int] = mapped_column(Integer)

    # Owner member ID for multi-user isolation
    member_id: Mapped[int] = mapped_column(Integer, default=0, index=True)

    # State Context
    node_name: Mapped[str] = mapped_column(String(100))
    state_snapshot: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # Unified JSON field

    # Action / Event Data
    event_type: Mapped[str] = mapped_column(String(50), index=True) # Consolidated action_type
    payload: Mapped[dict] = mapped_column(JSON) # Consolidated action_payload

    # Compatibility Fields (Legacy support for API routes and frontend)
    action_type: Mapped[str | None] = mapped_column(String(50), index=True, nullable=True)
    action_payload: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Human/Agent Distinction
    is_human_action: Mapped[bool] = mapped_column(default=False)
    source: Mapped[str | None] = mapped_column(String(20), nullable=True, default="agent") # "agent", "human", "global"

    # Visual Context
    screenshot_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    target_selector: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Feedback & Reward
    reward: Mapped[float | None] = mapped_column(Float, nullable=True)
    user_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Legacy / Compatibility Fields (To be removed after full migration)
    recording_session_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    timestamp: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Metadata
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    message_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)

    # Window Context (Global only)
    window_title: Mapped[str | None] = mapped_column(Text, nullable=True)
    app_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    process_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Mouse Position (Global only, screen coordinates)
    mouse_x: Mapped[int | None] = mapped_column(Integer, nullable=True)
    mouse_y: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Key Info (Global only)
    key_name: Mapped[str | None] = mapped_column(String(50), nullable=True)
    mouse_button: Mapped[str | None] = mapped_column(String(20), nullable=True)


class LearnedSkill(Base):
    """
    Stores learned skills synthesized from trace sequences.
    These can be matched to user intents and executed automatically.

    Skill Lifecycle (status) — CONVERGED (2026-07, see SKILL_CONVERGENCE_PLAN.md):
    - pending_review: Synthesized, awaiting user confirmation (is_active=False)
    - verified:       Confirmed by user (is_active=True); only this status is routable
    - candidate:      Imported SKILL.md with validation warnings (is_active=True,
                      visible but NOT routable)
    Retired values (never written; legacy rows repaired by
    migrate_legacy_status_rows at startup): draft, needs_update, deprecated, active.

    Skill Complexity Taxonomy (skill_level):
    - L1 (atomic):    1-3 steps, single intent
    - L2 (composite): 3-10 steps, complete user goal
    - L3 (workflow):  10+ steps, cross-app flow, generated by WorkflowSynthesizer

    Skill Source (skill_source):
    - record:            Synthesized from an agent/chat trace (WorkflowSynthesizer)
    - multimodal_record: Synthesized from a user video recording (MultimodalSkillSynthesizer)
    - imported:          User-authored SKILL.md folder import (SkillImporter)
    - manual:            Reserved; not currently written
    """

    __tablename__ = "learned_skills"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    description: Mapped[str] = mapped_column(Text)

    # Matching
    trigger_patterns: Mapped[list[str]] = mapped_column(JSON)  # JSON list of trigger patterns

    # Configuration
    namespace: Mapped[str | None] = mapped_column(String(500), nullable=True, index=True) # Physical tree path e.g. "domain/browser/github"
    parameters: Mapped[list[dict]] = mapped_column(JSON)  # JSON list of SkillParameter
    preconditions: Mapped[list[dict] | None] = mapped_column(JSON, nullable=True)  # JSON list of preconditions
    instructions: Mapped[str | None] = mapped_column(Text, nullable=True)  # Phase 5: Markdown Instructions (Replaces 'steps' JSON)

    tools_used: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)  # JSON list of tool names

    # 能力包声明（capability-packages-refactor.md §5.1）：
    # {domain, tools: [{mcp_server, include?}], preload, route_patterns}
    # null = 普通技能（非包）；与 requires.tools/tools_used（原生工具依赖）语义不同
    capability: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Source Reference
    source_thread_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_session_id: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Usage Statistics — FROZEN (2026-07): never written anywhere; kept in API
    # responses as 0 for SDK compatibility. Do not wire writers until M1+
    # proves the creation value hypothesis.
    success_count: Mapped[int] = mapped_column(Integer, default=0)
    failure_count: Mapped[int] = mapped_column(Integer, default=0)

    # Confidence & Lifecycle (Skill Evolution)
    confidence_score: Mapped[float] = mapped_column(Float, default=0.0)  # FROZEN: never written
    status: Mapped[str] = mapped_column(String(20), default="pending_review")  # see lifecycle note above
    last_success_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_failure_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    promotion_history: Mapped[str | None] = mapped_column(Text, nullable=True)  # UNUSED: never written; column kept to avoid migration

    # Lifecycle
    is_active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)

    # New fields compatibility
    project_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)

    # Owner member ID for multi-user isolation
    member_id: Mapped[int] = mapped_column(Integer, default=0, index=True)

    # Phase 5: External Skill Support
    resource_path: Mapped[str | None] = mapped_column(String(500), nullable=True)  # Path to external resource folder (SKILL.md)
    validation_report: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # JSON report from SkillValidator

    # Skill Level & Provenance
    skill_level: Mapped[str | None] = mapped_column(String(10), nullable=True, default="L2")  # "L1", "L2", "L3"
    skill_source: Mapped[str | None] = mapped_column(String(20), nullable=True, default="record")  # see taxonomy above

    # Pairing with Macro
    macro_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)

    active_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
