from datetime import datetime

from sqlalchemy import JSON, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database.sql.database import Base
from app.utils.time import utcnow


class TraceEvent(Base):
    """
    Represents a high-fidelity snapshot of agent execution for Imitation Learning.
    Stores State -> Action tuples.

    Supports both:
    - Agent actions (LLM/tool calls, automatically captured)
    - Human actions (UI interactions, captured via frontend ActionRecorder)
    """

    __tablename__ = "trace_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    thread_id: Mapped[str] = mapped_column(String(255), index=True)
    message_id: Mapped[str | None] = mapped_column(String(36), index=True, nullable=True)
    run_id: Mapped[str | None] = mapped_column(String(36), index=True, nullable=True)
    step_number: Mapped[int] = mapped_column(Integer)

    # State Context
    node_name: Mapped[str] = mapped_column(String(100))
    state_snapshot: Mapped[dict] = mapped_column(Text)  # Huge JSON of inputs/scratchpad

    # Action
    action_type: Mapped[str] = mapped_column(String(50))  # "node_start", "llm_call", "tool_call", "user_intervention", "user_click", "user_input"
    action_payload: Mapped[dict] = mapped_column(Text)  # JSON of args/output/message

    # Human/Agent Distinction (Phase 1)
    is_human_action: Mapped[bool] = mapped_column(default=False)  # True if action was performed by human, not agent

    # Visual Context (Phase 1)
    screenshot_path: Mapped[str | None] = mapped_column(String(500), nullable=True)  # Path to screenshot taken at this moment
    ui_element_info: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON: target element selector, text, bounds

    # Feedback & Reward
    reward: Mapped[float | None] = mapped_column(Integer, nullable=True)  # Normalized reward if available
    user_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)  # User correction/comment

    # Session Tracking
    recording_session_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)  # Groups events in one recording session

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    # New columns for compatibility with new refactors (Nullable)
    session_id: Mapped[str | None] = mapped_column(String(36), index=True, nullable=True)
    timestamp: Mapped[float | None] = mapped_column(Float, nullable=True)
    event_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    target_selector: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # NEW: Global Observation Fields (Phase 2)
    source: Mapped[str | None] = mapped_column(String(20), nullable=True, default="dom")  # "dom", "global"

    # Window Context (Global only)
    window_title: Mapped[str | None] = mapped_column(Text, nullable=True)
    app_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    process_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Mouse Position (Global only, screen coordinates)
    mouse_x: Mapped[int | None] = mapped_column(Integer, nullable=True)
    mouse_y: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Key Info (Global only)
    key_name: Mapped[str | None] = mapped_column(String(50), nullable=True)
    mouse_button: Mapped[str | None] = mapped_column(String(20), nullable=True)


class LearnedSkill(Base):
    """
    Stores learned skills synthesized from trace sequences.
    These can be matched to user intents and executed automatically.
    
    Skill Lifecycle (status):
    - draft: Auto-generated by Synthesizer, not yet validated
    - candidate: Executed successfully 3+ times, pending full verification
    - verified: Proven reliable, fully trusted by the system
    - needs_update: PreAction/PostAction drift detected; awaiting re-probe
    - deprecated: Too many failures, should be reviewed or removed
    
    Skill Complexity Taxonomy (skill_level):
    - L1 (atomic):    1-3 steps, single intent
    - L2 (composite): 3-10 steps, complete user goal
    - L3 (workflow):  10+ steps, cross-app flow, generated by WorkflowSynthesizer
    
    Skill Source (skill_source):
    - record:  Synthesized from user-recorded trace (WorkflowSynthesizer)
    - manual:  Manually authored by the user
    """

    __tablename__ = "learned_skills"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    description: Mapped[str] = mapped_column(Text)

    # Matching
    trigger_patterns: Mapped[str] = mapped_column(Text)  # JSON list of trigger patterns

    # Configuration
    namespace: Mapped[str | None] = mapped_column(String(500), nullable=True, index=True) # Physical tree path e.g. "domain/browser/github"
    parameters: Mapped[str] = mapped_column(Text)  # JSON list of SkillParameter
    preconditions: Mapped[str] = mapped_column(Text, nullable=True)  # JSON list of preconditions
    instructions: Mapped[str | None] = mapped_column(Text, nullable=True)  # Phase 5: Markdown Instructions (Replaces 'steps' JSON)

    tools_used: Mapped[str] = mapped_column(Text, nullable=True)  # JSON list of tool names

    # Source Reference
    source_thread_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_session_id: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Usage Statistics
    success_count: Mapped[int] = mapped_column(Integer, default=0)
    failure_count: Mapped[int] = mapped_column(Integer, default=0)

    # Confidence & Lifecycle (Skill Evolution)
    confidence_score: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(20), default="draft")  # draft, candidate, verified, deprecated
    last_success_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_failure_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    promotion_history: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON log of status changes

    # Lifecycle
    is_active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)

    # New fields compatibility
    project_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)

    # Phase 5: External Skill Support
    resource_path: Mapped[str | None] = mapped_column(String(500), nullable=True)  # Path to external resource folder (SKILL.md)
    validation_report: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # JSON report from SkillValidator

    # Skill Level & Provenance
    skill_level: Mapped[str | None] = mapped_column(String(10), nullable=True, default="L2")  # "L1", "L2", "L3"
    skill_source: Mapped[str | None] = mapped_column(String(20), nullable=True, default="record")  # "record", "manual"

    # Execution Mode (Phase 6: Deterministic Playback)
    execution_mode: Mapped[str] = mapped_column(String(20), default="agentic")  # "agentic" or "deterministic"
    macro_script: Mapped[str | None] = mapped_column(Text, nullable=True)  # YAML format of deterministic steps
    allow_self_healing: Mapped[bool] = mapped_column(default=True)
    active_model: Mapped[str | None] = mapped_column(String(100), nullable=True)


class RouterTrainingData(Base):
    """
    Stores few-shot examples for the Intent Router.
    This replaces the local 'few_shots.json' file with a persistent DB table.
    """

    __tablename__ = "router_training_data"

    id: Mapped[int] = mapped_column(primary_key=True)

    instruction: Mapped[str] = mapped_column(Text)
    intent: Mapped[str] = mapped_column(String(50))
    reasoning: Mapped[str] = mapped_column(Text)

    # Metadata
    is_active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    source: Mapped[str] = mapped_column(String(50), default="user_feedback")  # 'manual', 'user_feedback', 'system'


class SynthesisJob(Base):
    """
    Smart Replay Synthesis: LLM synthesis job tracking.
    Stores progress and results of skill generation from annotated recordings.
    """

    __tablename__ = "synthesis_jobs"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[str] = mapped_column(String(255), index=True)
    thread_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)

    # User input
    task_goal: Mapped[str] = mapped_column(Text)  # User's stated goal
    annotation_ids: Mapped[list] = mapped_column(JSON, default=list)  # [Scheme A] List of TraceEvent IDs (action_type="region_extract") used as annotations

    # Job status
    status: Mapped[str] = mapped_column(String(50), default="pending")  # pending, processing, analyzing_frames, understanding_phases, generating_macro, generating_metadata, completed, failed
    progress_percent: Mapped[int] = mapped_column(Integer, default=0)  # 0-100
    current_phase: Mapped[str | None] = mapped_column(String(100), nullable=True)  # Human-readable current phase

    # Intermediate results (stored for debugging and transparency)
    phase_analysis: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # Phase understanding results
    keyframes: Mapped[list | None] = mapped_column(JSON, nullable=True)  # Extracted keyframe info
    frame_analyses: Mapped[list | None] = mapped_column(JSON, nullable=True)  # Vision LLM analysis per frame
    extracted_insights: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # Key insights extracted

    # Error information
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_traceback: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Final result (populated when status = completed)
    generated_skill: Mapped[dict | None] = mapped_column(JSON, nullable=True)  # Complete skill object
    skill_id: Mapped[int | None] = mapped_column(Integer, nullable=True)  # If saved to LearnedSkill

    # Metadata
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
