// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatRequestSchema = {
    properties: {
        thread_id: {
            type: 'string',
            title: 'Thread Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        project_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id',
            default: 1
        },
        checkpoint_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Checkpoint Id'
        }
    },
    type: 'object',
    required: ['thread_id', 'message'],
    title: 'ChatRequest'
} as const;

export const CommandRequestSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        project_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id',
            default: 1
        }
    },
    type: 'object',
    required: ['content'],
    title: 'CommandRequest'
} as const;

export const ConceptCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        related_files: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Files'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'ConceptCreate'
} as const;

export const ConceptResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'description'],
    title: 'ConceptResponse'
} as const;

export const CreateFileRequestSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path'
        },
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['path', 'content'],
    title: 'CreateFileRequest'
} as const;

export const CreateProjectRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CreateProjectRequest'
} as const;

export const DeviceInfoSchema = {
    properties: {
        device_id: {
            type: 'integer',
            title: 'Device Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'integer',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['device_id', 'name', 'status'],
    title: 'DeviceInfo'
} as const;

export const FileContentSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        },
        language: {
            type: 'string',
            title: 'Language'
        }
    },
    type: 'object',
    required: ['content', 'language'],
    title: 'FileContent'
} as const;

export const FileNodeSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        children: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/FileNode'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        }
    },
    type: 'object',
    required: ['name', 'path', 'type'],
    title: 'FileNode'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IndexingRequestSchema = {
    properties: {
        project_id: {
            type: 'integer',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['project_id'],
    title: 'IndexingRequest'
} as const;

export const LogItemSchema = {
    properties: {
        log_id: {
            type: 'integer',
            title: 'Log Id'
        },
        thread_id: {
            type: 'string',
            title: 'Thread Id'
        },
        project_id: {
            type: 'integer',
            title: 'Project Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        type: {
            type: 'string',
            title: 'Type',
            default: 'info'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        create_time: {
            type: 'integer',
            title: 'Create Time'
        }
    },
    type: 'object',
    required: ['log_id', 'thread_id', 'project_id', 'role', 'content', 'create_time'],
    title: 'LogItem'
} as const;

export const LoginRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'LoginRequest'
} as const;

export const McpServerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        command: {
            type: 'string',
            title: 'Command'
        },
        args: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Args',
            default: []
        },
        env: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Env',
            default: {}
        }
    },
    type: 'object',
    required: ['name', 'command'],
    title: 'McpServerCreate'
} as const;

export const MobileLoginRequestSchema = {
    properties: {
        mobile: {
            type: 'string',
            title: 'Mobile'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['mobile', 'key', 'code'],
    title: 'MobileLoginRequest'
} as const;

export const RenameRequestSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'RenameRequest'
} as const;

export const SearchResultSchema = {
    properties: {
        thread_id: {
            type: 'string',
            title: 'Thread Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        match_snippet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Snippet'
        }
    },
    type: 'object',
    required: ['thread_id', 'role', 'content', 'created_at'],
    title: 'SearchResult'
} as const;

export const SendMobileCodeRequestSchema = {
    properties: {
        mobile: {
            type: 'string',
            title: 'Mobile'
        },
        captcha_id: {
            type: 'string',
            title: 'Captcha Id',
            default: ''
        },
        captcha_code: {
            type: 'string',
            title: 'Captcha Code',
            default: ''
        }
    },
    type: 'object',
    required: ['mobile'],
    title: 'SendMobileCodeRequest'
} as const;

export const SystemConfigSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'SystemConfig'
} as const;

export const TaskCreateRequestSchema = {
    properties: {
        project_id: {
            type: 'integer',
            title: 'Project Id'
        },
        task_title: {
            type: 'string',
            title: 'Task Title'
        },
        task_desc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Desc',
            default: ''
        },
        priority: {
            type: 'integer',
            title: 'Priority',
            default: 2
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score'
        },
        relevance_analysis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relevance Analysis'
        },
        key_modules: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Key Modules'
        },
        technical_challenges: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Technical Challenges'
        },
        implementation_complexity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Implementation Complexity'
        },
        deliverables: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Deliverables'
        }
    },
    type: 'object',
    required: ['project_id', 'task_title'],
    title: 'TaskCreateRequest'
} as const;

export const TaskStatusUpdateSchema = {
    properties: {
        status: {
            type: 'integer',
            title: 'Status'
        },
        progress: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress',
            default: 0
        }
    },
    type: 'object',
    required: ['status'],
    title: 'TaskStatusUpdate'
} as const;

export const TaskUpdateRequestSchema = {
    properties: {
        task_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Title'
        },
        task_desc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Desc'
        },
        priority: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        status: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        progress: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score'
        },
        relevance_analysis: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Relevance Analysis'
        },
        key_modules: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Key Modules'
        },
        technical_challenges: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Technical Challenges'
        },
        implementation_complexity: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Implementation Complexity'
        },
        deliverables: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Deliverables'
        }
    },
    type: 'object',
    title: 'TaskUpdateRequest'
} as const;

export const TimesheetQuickAddRequestSchema = {
    properties: {
        project_id: {
            type: 'integer',
            title: 'Project Id'
        },
        hours: {
            type: 'number',
            title: 'Hours'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        work_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Type',
            default: 'development'
        }
    },
    type: 'object',
    required: ['project_id', 'hours', 'description'],
    title: 'TimesheetQuickAddRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Id'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        mobile: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobile'
        },
        nickname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nickname'
        },
        headimg: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headimg'
        },
        member_level: {
            type: 'integer',
            title: 'Member Level',
            default: 0
        },
        member_level_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Member Level Name'
        },
        level_expire_time: {
            type: 'integer',
            title: 'Level Expire Time',
            default: 0
        },
        balance: {
            type: 'number',
            title: 'Balance',
            default: 0
        },
        balance_money: {
            type: 'number',
            title: 'Balance Money',
            default: 0
        },
        point: {
            type: 'integer',
            title: 'Point',
            default: 0
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: ['id'],
    title: 'UserPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WebhookRequestSchema = {
    properties: {
        source: {
            type: 'string',
            title: 'Source'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        thread_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thread Id'
        }
    },
    type: 'object',
    required: ['source', 'event_type', 'payload'],
    title: 'WebhookRequest'
} as const;