// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatRequest = {
    thread_id: string;
    message: string;
    project_id?: (number | null);
    checkpoint_id?: (string | null);
};

export type CommandRequest = {
    content: string;
    project_id?: (number | null);
};

export type ConceptCreate = {
    name: string;
    description: string;
    related_files?: (Array<(string)> | null);
};

export type ConceptResponse = {
    name: string;
    description: string;
};

export type CreateFileRequest = {
    path: string;
    content: string;
};

export type CreateProjectRequest = {
    name: string;
};

export type DeviceInfo = {
    device_id: number;
    name: string;
    status: number;
};

export type FileContent = {
    content: string;
    language: string;
};

export type FileNode = {
    name: string;
    path: string;
    type: string;
    children?: (Array<FileNode> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IndexingRequest = {
    project_id: number;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type LogItem = {
    log_id: number;
    thread_id: string;
    project_id: number;
    role: string;
    type?: string;
    content: string;
    create_time: number;
};

export type McpServerCreate = {
    name: string;
    command: string;
    args?: (Array<(string)> | null);
    env?: ({
        [key: string]: (string);
    } | null);
};

export type MobileLoginRequest = {
    mobile: string;
    key: string;
    code: string;
};

export type RenameRequest = {
    title: string;
};

export type SearchResult = {
    thread_id: string;
    role: string;
    content: string;
    created_at: string;
    match_snippet?: (string | null);
};

export type SendMobileCodeRequest = {
    mobile: string;
    captcha_id?: string;
    captcha_code?: string;
};

export type SystemConfig = {
    key: string;
    value: string;
    description?: (string | null);
};

export type TaskCreateRequest = {
    project_id: number;
    task_title: string;
    task_desc?: (string | null);
    priority?: number;
    match_score?: (number | null);
    relevance_analysis?: (string | null);
    key_modules?: (unknown | null);
    technical_challenges?: (unknown | null);
    implementation_complexity?: (string | null);
    deliverables?: (unknown | null);
};

export type TaskStatusUpdate = {
    status: number;
    progress?: (number | null);
};

export type TaskUpdateRequest = {
    task_title?: (string | null);
    task_desc?: (string | null);
    priority?: (number | null);
    status?: (number | null);
    progress?: (number | null);
    match_score?: (number | null);
    relevance_analysis?: (string | null);
    key_modules?: (unknown | null);
    technical_challenges?: (unknown | null);
    implementation_complexity?: (string | null);
    deliverables?: (unknown | null);
};

export type TimesheetQuickAddRequest = {
    project_id: number;
    hours: number;
    description: string;
    work_type?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    id: (number | string);
    username?: (string | null);
    email?: (string | null);
    mobile?: (string | null);
    nickname?: (string | null);
    headimg?: (string | null);
    member_level?: number;
    member_level_name?: (string | null);
    level_expire_time?: number;
    balance?: number;
    balance_money?: number;
    point?: number;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WebhookRequest = {
    source: string;
    event_type: string;
    payload: {
        [key: string]: unknown;
    };
    thread_id?: (string | null);
};

export type AgentChatEndpointData = {
    authorization?: (string | null);
    requestBody: ChatRequest;
    xGuestId?: (string | null);
};

export type AgentChatEndpointResponse = (unknown);

export type AgentRewindChatData = {
    requestBody: ChatRequest;
};

export type AgentRewindChatResponse = (unknown);

export type AgentWebhookEndpointData = {
    requestBody: WebhookRequest;
};

export type AgentWebhookEndpointResponse = (unknown);

export type HistorySearchConversationsData = {
    projectId?: (number | null);
    q: string;
};

export type HistorySearchConversationsResponse = (Array<SearchResult>);

export type HistoryRenameConversationData = {
    requestBody: RenameRequest;
    threadId: string;
};

export type HistoryRenameConversationResponse = (unknown);

export type DevicesGetDevicesResponse = (Array<DeviceInfo>);

export type DevicesSendCommandData = {
    deviceId: number;
    requestBody: CommandRequest;
};

export type DevicesSendCommandResponse = (unknown);

export type DevicesGetRecentLogsData = {
    deviceId: number;
    limit?: number;
    projectId?: (number | null);
};

export type DevicesGetRecentLogsResponse = (Array<LogItem>);

export type DevicesSearchLogsData = {
    deviceId: number;
    limit?: number;
    projectId?: (number | null);
    query: string;
};

export type DevicesSearchLogsResponse = (Array<LogItem>);

export type FilesListFilesData = {
    path?: (string | null);
    projectId: number;
};

export type FilesListFilesResponse = (Array<FileNode>);

export type FilesCreateFileData = {
    projectId: number;
    requestBody: CreateFileRequest;
};

export type FilesCreateFileResponse = (FileNode);

export type FilesGetFileContentData = {
    path: string;
    projectId: number;
};

export type FilesGetFileContentResponse = (FileContent);

export type FilesSearchFilesData = {
    projectId: number;
    q: string;
};

export type FilesSearchFilesResponse = (Array<{
    [key: string]: unknown;
}>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type McpListMcpServersResponse = (Array<unknown>);

export type McpAddMcpServerData = {
    requestBody: McpServerCreate;
};

export type McpAddMcpServerResponse = (unknown);

export type McpDeleteMcpServerData = {
    name: string;
};

export type McpDeleteMcpServerResponse = (unknown);

export type MemberLoginData = {
    requestBody: LoginRequest;
};

export type MemberLoginResponse = (unknown);

export type MemberLoginMobileData = {
    requestBody: MobileLoginRequest;
};

export type MemberLoginMobileResponse = (unknown);

export type MemberSendMobileCodeData = {
    requestBody: SendMobileCodeRequest;
};

export type MemberSendMobileCodeResponse = (unknown);

export type MemberGetCaptchaConfigResponse = (unknown);

export type MemberGetCaptchaData = {
    id?: string;
};

export type MemberGetCaptchaResponse = (unknown);

export type MemberGetRegisterConfigResponse = (unknown);

export type MemberGetRegisterAgreementData = {
    type?: string;
};

export type MemberGetRegisterAgreementResponse = (unknown);

export type MemberRegisterUsernameData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type MemberRegisterUsernameResponse = (unknown);

export type MemberRegisterMobileData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type MemberRegisterMobileResponse = (unknown);

export type MemberSendRegisterCodeData = {
    requestBody: SendMobileCodeRequest;
};

export type MemberSendRegisterCodeResponse = (unknown);

export type MemberStatusResponse = (unknown);

export type MemberLogoutResponse = (unknown);

export type MemberGetCancellationInfoResponse = (unknown);

export type MemberApplyCancellationResponse = (unknown);

export type MemberCancelCancellationApplyResponse = (unknown);

export type MemoryListConceptsData = {
    projectId: number;
};

export type MemoryListConceptsResponse = (Array<ConceptResponse>);

export type MemoryAddConceptData = {
    projectId: number;
    requestBody: ConceptCreate;
};

export type MemoryAddConceptResponse = (unknown);

export type MemorySearchMemoryData = {
    projectId: number;
    q: string;
};

export type MemorySearchMemoryResponse = (Array<ConceptResponse>);

export type PlanningGetPlanData = {
    threadId: string;
};

export type PlanningGetPlanResponse = (unknown);

export type ProjectModulesGetBudgetListData = {
    page?: number;
    pageSize?: number;
    projectId: number;
    authorization?: (string | null);
};

export type ProjectModulesGetBudgetListResponse = (unknown);

export type ProjectModulesGetBudgetOverviewData = {
    projectId: number;
    authorization?: (string | null);
};

export type ProjectModulesGetBudgetOverviewResponse = (unknown);

export type ProjectModulesGetTimesheetListData = {
    page?: number;
    pageSize?: number;
    projectId: number;
    authorization?: (string | null);
};

export type ProjectModulesGetTimesheetListResponse = (unknown);

export type ProjectModulesQuickAddTimesheetData = {
    requestBody: TimesheetQuickAddRequest;
    authorization?: (string | null);
};

export type ProjectModulesQuickAddTimesheetResponse = (unknown);

export type ProjectModulesGetProjectStatisticsData = {
    projectId?: (number | null);
    authorization?: (string | null);
};

export type ProjectModulesGetProjectStatisticsResponse = (unknown);

export type ProjectsListProjectsResponse = (unknown);

export type ProjectsCreateProjectData = {
    requestBody: CreateProjectRequest;
};

export type ProjectsCreateProjectResponse = (unknown);

export type ProjectsDeleteProjectData = {
    projectId: number;
};

export type ProjectsDeleteProjectResponse = (unknown);

export type ProjectsRunIndexingEndpointData = {
    requestBody: IndexingRequest;
};

export type ProjectsRunIndexingEndpointResponse = (unknown);

export type ProjectsListProjectConversationsData = {
    projectId: number;
};

export type ProjectsListProjectConversationsResponse = (unknown);

export type ProjectsGetConversationHistoryData = {
    threadId: string;
};

export type ProjectsGetConversationHistoryResponse = (unknown);

export type ProjectsGetConversationActivityData = {
    threadId: string;
};

export type ProjectsGetConversationActivityResponse = (unknown);

export type ProjectsDeleteConversationData = {
    conversationId: string;
};

export type ProjectsDeleteConversationResponse = (unknown);

export type SymbolsSearchSymbolsData = {
    limit?: number;
    projectId: number;
    /**
     * Search query for symbol name
     */
    q: string;
    /**
     * Filter by entity type (class, function)
     */
    type?: (string | null);
};

export type SymbolsSearchSymbolsResponse = (Array<{
    [key: string]: unknown;
}>);

export type SymbolsGenerateSymbolWikiData = {
    projectId: number;
    symbolId: number;
};

export type SymbolsGenerateSymbolWikiResponse = (unknown);

export type SystemGetSystemConfigData = {
    authorization?: (string | null);
};

export type SystemGetSystemConfigResponse = (Array<SystemConfig>);

export type SystemUpdateSystemConfigData = {
    authorization?: (string | null);
    requestBody: SystemConfig;
};

export type SystemUpdateSystemConfigResponse = (SystemConfig);

export type TasksGetProjectTasksData = {
    page?: number;
    pageSize?: number;
    projectId: number;
    status?: (number | null);
    authorization?: (string | null);
};

export type TasksGetProjectTasksResponse = (unknown);

export type TasksCreateTaskData = {
    requestBody: TaskCreateRequest;
    authorization?: (string | null);
};

export type TasksCreateTaskResponse = (unknown);

export type TasksGetTaskDetailData = {
    taskId: number;
    authorization?: (string | null);
};

export type TasksGetTaskDetailResponse = (unknown);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdateRequest;
    taskId: number;
    authorization?: (string | null);
};

export type TasksUpdateTaskResponse = (unknown);

export type TasksDeleteTaskData = {
    taskId: number;
    authorization?: (string | null);
};

export type TasksDeleteTaskResponse = (unknown);

export type TasksUpdateTaskStatusEndpointData = {
    requestBody: TaskStatusUpdate;
    taskId: number;
    authorization?: (string | null);
};

export type TasksUpdateTaskStatusEndpointResponse = (unknown);

export type UsersReadUserMeData = {
    authorization?: (string | null);
};

export type UsersReadUserMeResponse = (UserPublic);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetEvoloopStatusResponse = (unknown);

export type TasksExecuteTaskData = {
    taskId: number;
    authorization?: (string | null);
};

export type TasksExecuteTaskResponse = (unknown);

export type EmbeddingConfigRequest = {
    provider: string;
    base_url: string;
    model: string;
    api_key?: (string | null);
    project_id?: (number | null);
};

export type EmbeddingTestResponse = {
    success: boolean;
    dimensions: number;
};

export type EmbeddingApplyResponse = {
    status: string;
    message: string;
};

export type SystemTestEmbeddingConnectionData = {
    requestBody: EmbeddingConfigRequest;
    authorization?: (string | null);
};

export type SystemTestEmbeddingConnectionResponse = (EmbeddingTestResponse);

export type SystemApplyEmbeddingConfigData = {
    requestBody: EmbeddingConfigRequest;
    authorization?: (string | null);
};

export type SystemApplyEmbeddingConfigResponse = (EmbeddingApplyResponse);

export type LLMConfigRequest = {
    provider: string;
    base_url: string;
    model: string;
    api_key?: (string | null);
};

export type SystemTestLLMConnectionResponse = {
    success: boolean;
    reply: (string | null);
};

export type SystemTestLLMConnectionData = {
    requestBody: LLMConfigRequest;
    authorization?: (string | null);
};

export type SystemApplyLLMConfigData = {
    requestBody: LLMConfigRequest;
    authorization?: (string | null);
};

export type SystemApplyLLMConfigResponse = {
    status: string;
    message: string;
};