// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatRequest = {
    thread_id: string;
    message: string;
    project_id?: (number | null);
    checkpoint_id?: (string | null);
};

export type CreateProjectRequest = {
    name: string;
};

export type FileContent = {
    content: string;
    language: string;
};

export type FileNode = {
    name: string;
    path: string;
    type: string;
    children?: (Array<FileNode> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IndexingRequest = {
    project_id: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type McpServerRequest = {
    name: string;
    command: string;
    args?: Array<(string)>;
    env?: {
        [key: string]: (string);
    };
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RenameRequest = {
    title: string;
};

export type SearchResult = {
    thread_id: string;
    role: string;
    content: string;
    created_at: string;
    match_snippet?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: (string | number);
    username?: (string | null);
    mobile?: (string | null);
    nickname?: (string | null);
    headimg?: (string | null);
    member_level?: number;
    member_level_name?: (string | null);
    level_expire_time?: number;
    balance?: number;
    balance_money?: number;
    point?: number;
    auto_renew?: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WebhookRequest = {
    source: string;
    event_type: string;
    payload: {
        [key: string]: unknown;
    };
    thread_id?: (string | null);
};

export type AgentChatEndpointData = {
    requestBody: ChatRequest;
};

export type AgentChatEndpointResponse = (unknown);

export type AgentWebhookEndpointData = {
    requestBody: WebhookRequest;
};

export type AgentWebhookEndpointResponse = (unknown);

export type AgentChatEndpoint1Data = {
    requestBody: ChatRequest;
};

export type AgentChatEndpoint1Response = (unknown);

export type AgentWebhookEndpoint1Data = {
    requestBody: WebhookRequest;
};

export type AgentWebhookEndpoint1Response = (unknown);

export type HistorySearchConversationsData = {
    projectId?: (number | null);
    q: string;
};

export type HistorySearchConversationsResponse = (Array<SearchResult>);

export type HistoryRenameConversationData = {
    requestBody: RenameRequest;
    threadId: string;
};

export type HistoryRenameConversationResponse = (unknown);

export type FilesListFilesData = {
    path?: (string | null);
    projectId: number;
};

export type FilesListFilesResponse = (Array<FileNode>);

export type FilesGetFileContentData = {
    path: string;
    projectId: number;
};

export type FilesGetFileContentResponse = (FileContent);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type McpAddMcpServerData = {
    requestBody: McpServerRequest;
};

export type McpAddMcpServerResponse = (unknown);

export type McpListMcpServersResponse = (unknown);

export type McpDeleteMcpServerData = {
    name: string;
};

export type McpDeleteMcpServerResponse = (unknown);

export type MemberLoginData = {
    requestBody: LoginRequest;
};

export type MemberLoginResponse = (unknown);

export type MemberStatusResponse = (unknown);

export type MemberLogoutResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsResponse = (unknown);

export type ProjectsCreateProjectData = {
    requestBody: CreateProjectRequest;
};

export type ProjectsCreateProjectResponse = (unknown);

export type ProjectsDeleteProjectData = {
    projectId: number;
};

export type ProjectsDeleteProjectResponse = (unknown);

export type ProjectsRunIndexingEndpointData = {
    requestBody: IndexingRequest;
};

export type ProjectsRunIndexingEndpointResponse = (unknown);

export type ProjectsListProjectConversationsData = {
    projectId: number;
};

export type ProjectsListProjectConversationsResponse = (unknown);

export type ProjectsGetConversationHistoryData = {
    threadId: string;
};

export type ProjectsGetConversationHistoryResponse = (unknown);

export type ProjectsGetConversationActivityData = {
    threadId: string;
};

export type ProjectsGetConversationActivityResponse = (unknown);

export type ProjectsDeleteConversationData = {
    threadId: string;
};

export type ProjectsDeleteConversationResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);