// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatRequest = {
    thread_id: string;
    message: string;
    project_id?: (number | null);
    checkpoint_id?: (string | null);
};

export type ConceptCreate = {
    name: string;
    description: string;
    related_files?: (Array<(string)> | null);
};

export type ConceptResponse = {
    name: string;
    description: string;
};

export type CreateFileRequest = {
    path: string;
    content: string;
};

export type CreateProjectRequest = {
    name: string;
};

export type FileContent = {
    content: string;
    language: string;
};

export type FileNode = {
    name: string;
    path: string;
    type: string;
    children?: (Array<FileNode> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IndexingRequest = {
    project_id: number;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type McpServerCreate = {
    name: string;
    command: string;
    args?: (Array<(string)> | null);
    env?: ({
        [key: string]: (string);
    } | null);
};

export type Message = {
    message: string;
};

export type RenameRequest = {
    title: string;
};

export type SearchResult = {
    thread_id: string;
    role: string;
    content: string;
    created_at: string;
    match_snippet?: (string | null);
};

export type SystemConfig = {
    key: string;
    value: string;
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    id: (number | string);
    username?: (string | null);
    email?: (string | null);
    mobile?: (string | null);
    nickname?: (string | null);
    headimg?: (string | null);
    member_level?: number;
    member_level_name?: (string | null);
    level_expire_time?: number;
    balance?: number;
    balance_money?: number;
    point?: number;
    is_active?: boolean;
    is_superuser?: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WebhookRequest = {
    source: string;
    event_type: string;
    payload: {
        [key: string]: unknown;
    };
    thread_id?: (string | null);
};

export type AgentChatEndpointData = {
    requestBody: ChatRequest;
};

export type AgentChatEndpointResponse = (unknown);

export type AgentRewindChatData = {
    requestBody: ChatRequest;
};

export type AgentRewindChatResponse = (unknown);

export type AgentWebhookEndpointData = {
    requestBody: WebhookRequest;
};

export type AgentWebhookEndpointResponse = (unknown);

export type HistorySearchConversationsData = {
    projectId?: (number | null);
    q: string;
};

export type HistorySearchConversationsResponse = (Array<SearchResult>);

export type HistoryRenameConversationData = {
    requestBody: RenameRequest;
    threadId: string;
};

export type HistoryRenameConversationResponse = (unknown);

export type FilesListFilesData = {
    path?: (string | null);
    projectId: number;
};

export type FilesListFilesResponse = (Array<FileNode>);

export type FilesCreateFileData = {
    projectId: number;
    requestBody: CreateFileRequest;
};

export type FilesCreateFileResponse = (FileNode);

export type FilesGetFileContentData = {
    path: string;
    projectId: number;
};

export type FilesGetFileContentResponse = (FileContent);

export type FilesSearchFilesData = {
    projectId: number;
    q: string;
};

export type FilesSearchFilesResponse = (Array<{
    [key: string]: unknown;
}>);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type McpListMcpServersResponse = (Array<unknown>);

export type McpAddMcpServerData = {
    requestBody: McpServerCreate;
};

export type McpAddMcpServerResponse = (unknown);

export type McpDeleteMcpServerData = {
    name: string;
};

export type McpDeleteMcpServerResponse = (unknown);

export type MemberLoginData = {
    requestBody: LoginRequest;
};

export type MemberLoginResponse = (unknown);

export type MemberStatusResponse = (unknown);

export type MemberLogoutResponse = (unknown);

export type MemoryListConceptsData = {
    projectId: number;
};

export type MemoryListConceptsResponse = (Array<ConceptResponse>);

export type MemoryAddConceptData = {
    projectId: number;
    requestBody: ConceptCreate;
};

export type MemoryAddConceptResponse = (unknown);

export type MemorySearchMemoryData = {
    projectId: number;
    q: string;
};

export type MemorySearchMemoryResponse = (Array<ConceptResponse>);

export type PlanningGetPlanData = {
    threadId: string;
};

export type PlanningGetPlanResponse = (unknown);

export type ProjectsListProjectsResponse = (unknown);

export type ProjectsCreateProjectData = {
    requestBody: CreateProjectRequest;
};

export type ProjectsCreateProjectResponse = (unknown);

export type ProjectsDeleteProjectData = {
    projectId: number;
};

export type ProjectsDeleteProjectResponse = (unknown);

export type ProjectsRunIndexingEndpointData = {
    requestBody: IndexingRequest;
};

export type ProjectsRunIndexingEndpointResponse = (unknown);

export type ProjectsListProjectConversationsData = {
    projectId: number;
};

export type ProjectsListProjectConversationsResponse = (unknown);

export type ProjectsGetConversationHistoryData = {
    threadId: string;
};

export type ProjectsGetConversationHistoryResponse = (unknown);

export type ProjectsGetConversationActivityData = {
    threadId: string;
};

export type ProjectsGetConversationActivityResponse = (unknown);

export type ProjectsDeleteConversationData = {
    conversationId: string;
};

export type ProjectsDeleteConversationResponse = (unknown);

export type SymbolsSearchSymbolsData = {
    limit?: number;
    projectId: number;
    /**
     * Search query for symbol name
     */
    q: string;
    /**
     * Filter by entity type (class, function)
     */
    type?: (string | null);
};

export type SymbolsSearchSymbolsResponse = (Array<{
    [key: string]: unknown;
}>);

export type SymbolsGenerateSymbolWikiData = {
    projectId: number;
    symbolId: number;
};

export type SymbolsGenerateSymbolWikiResponse = (unknown);

export type SystemGetSystemConfigResponse = (Array<SystemConfig>);

export type SystemUpdateSystemConfigData = {
    requestBody: SystemConfig;
};

export type SystemUpdateSystemConfigResponse = (SystemConfig);

export type UsersReadUserMeResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetEvoloopStatusResponse = (unknown);

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    username?: (string | null);
};

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);