"""Learning schemas package."""

from app.core.learning.schemas.events import (
    GlobalEventData,
    DomEventData,
    RecordingSessionItem,
    PreviewVideoInfo,
    PreviewEventsSummary,
    PreviewKeyframeSummary,
)
from app.core.learning.schemas.requests import (
    HumanInputRequestOut,
    ExecuteSkillRequest,
    RespondRequest,
    StartMirrorRequest,
    StopMirrorRequest,
    StartMirrorRecordingRequest,
    PersistMirrorEventsRequest,
    GlobalEventsRequest,
    DomEventsRequest,
    ImportSkillsRequest,
    StartRecordingRequest,
    SynthesizeRequest,
    UpdateSkillRequest,
    SynthesizeFromRecordingRequest,
    AndroidExtractPointRequest,
    SmartSynthesisRequest,
    CreateSkillFromYamlRequest,
    ValidateYamlRequest,
)
from app.core.learning.schemas.responses import (
    PaginatedSkillsResponse,
    RecordingSessionsResponse,
    SynthesizeSkillResponse,
    ImportSkillsResponse,
    UpdateSkillResponse,
    ExecuteSkillResponse,
    MirrorDevicesResponse,
    MirrorSessionResponse,
    MirrorRecordingResponse,
    MirrorPersistResponse,
    StopMirrorResponse,
    DeviceResolutionResponse,
    ValidateSkillResponse,
    PreviewRecordingDataResponse,
    CleanupRecordingResponse,
    CreateSkillFromYamlResponse,
    StartRecordingResponse,
    StopRecordingResponse,
    UploadScreenshotResponse,
    SynthesizeFromRecordingResponse,
    AnnotationResponse,
    AndroidExtractPointResponse,
    SmartSynthesisResponse,
    SynthesisJobResponse,
    ValidateYamlResponse,
)
from app.core.learning.schemas.skills import (
    SkillExecutionParams,
    SkillDTO,
    SkillDetailResponse,
    SkillResponse,
    SkillParameter,
)
