// This file is auto-generated by @hey-api/openapi-ts

/**
 * Definition of a system-wide action (Capability).
 * Acts as the single source of truth for prompts, UI, and execution.
 */
export type ActionDef = {
    id: string;
    platforms: Array<(string)>;
    icon: string;
    description: string;
    translation_key: string;
    params?: {
        [key: string]: unknown;
    };
    mappings?: {
        [key: string]: (string);
    };
};

/**
 * Android镜像实时提取点标记请求 - 支持区域标记
 */
export type AndroidExtractPointRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    session_id: string;
    x: number;
    y: number;
    width?: (number | null);
    height?: (number | null);
    timestamp_ms?: (number | null);
    note?: (string | null);
};

/**
 * Android镜像提取点标记响应
 */
export type AndroidExtractPointResponse = {
    success?: boolean;
    message?: string;
    id: number;
    session_id: string;
    x: number;
    y: number;
    width: (number | null);
    height: (number | null);
    timestamp_ms: (number | null);
    note: (string | null);
    created_at: string;
    [key: string]: unknown | boolean | string | number;
};

/**
 * 标注响应
 */
export type AnnotationResponse = {
    success?: boolean;
    message?: string;
    id: number;
    session_id: string;
    annotation_type: string;
    video_timestamp_ms: number;
    region: ({
    [key: string]: unknown;
} | null);
    user_note: (string | null);
    created_at: string;
    [key: string]: unknown | boolean | string | number;
};

export type AuthProxyMobileCodeRequest = {
    mobile: string;
    captcha_id: string;
    captcha_code: string;
    type?: string;
    [key: string]: unknown | string;
};

/**
 * Standard API response envelope with success/message.
 */
export type BaseAPIResponse = {
    success?: boolean;
    message?: string;
    [key: string]: unknown | boolean | string;
};

export type BatchCheckRequest = {
    benefit_codes: Array<(string)>;
    [key: string]: unknown | string;
};

export type BatchCheckResponse = {
    success?: boolean;
    message?: string;
    results: {
        [key: string]: (boolean);
    };
    is_expired: boolean;
    level_name: string;
    [key: string]: unknown | boolean | string;
};

export type BatchImportRequest = {
    repo_ids: Array<(number)>;
    [key: string]: unknown | number;
};

/**
 * Batch import response.
 */
export type BatchImportResponse = {
    success?: boolean;
    message?: string;
    status: string;
    summary: string;
    results: {
        [key: string]: Array<BatchResultItem>;
    };
    [key: string]: unknown | boolean | string | BatchResultItem;
};

/**
 * Single result in batch operation.
 */
export type BatchResultItem = {
    repo_id: number;
    name?: (string | null);
    error?: (string | null);
    [key: string]: unknown | number;
};

export type BenefitsUpdateWebhook = {
    member_id: number;
    event: string;
    level_id?: (number | null);
    timestamp: number;
    signature: string;
    [key: string]: unknown | number | string;
};

export type BindClientRequest = {
    client_id: string;
    [key: string]: unknown | string;
};

/**
 * Device bind response.
 */
export type BindResponse = {
    success?: boolean;
    message?: string;
    status: string;
    data?: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown | boolean | string;
};

export type Body_account_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_audio_text_to_speech_stream = {
    text: string;
    voice_id?: string;
    speed?: number;
    format?: string;
};

export type Body_audio_transcribe_audio = {
    file: (Blob | File);
    language?: string;
    model?: string;
    prompt?: (string | null);
    provider?: (string | null);
};

export type Body_audio_transcribe_stream = {
    file: (Blob | File);
    language?: string;
};

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type Body_knowledge_bulk_upload = {
    /**
     * Multiple files to upload
     */
    files: Array<((Blob | File))>;
    /**
     * Collection name
     */
    collection?: string;
    /**
     * Document type
     */
    doc_type?: string;
};

export type Body_knowledge_import_zip = {
    /**
     * ZIP archive containing documents
     */
    file: (Blob | File);
    /**
     * Collection name
     */
    collection?: string;
    /**
     * Preserve directory structure
     */
    preserve_structure?: boolean;
};

export type Body_knowledge_upload_document = {
    /**
     * Document to upload
     */
    file: (Blob | File);
    /**
     * Collection name
     */
    collection?: string;
    /**
     * Document type (doc, code, guide, etc.)
     */
    doc_type?: string;
    /**
     * Extract metadata automatically
     */
    extract_metadata?: boolean;
};

export type Body_knowledge_validate_zip = {
    /**
     * ZIP archive to validate
     */
    file: (Blob | File);
};

export type Body_learning_upload_screenshot = {
    file: (Blob | File);
};

export type Body_project_requirements_upload_requirement_document = {
    file: (Blob | File);
};

/**
 * Response for bulk upload.
 */
export type BulkUploadResponse = {
    success?: boolean;
    message?: string;
    [key: string]: unknown | boolean | string;
};

export type CacheInvalidateResponse = {
    code?: number;
    message: string;
    [key: string]: unknown | number | string;
};

export type CancelHITLRequest = {
    project_id?: (number | null);
    thread_id: string;
    reason?: (string | null);
};

export type ChangePasswordRequest = {
    /**
     * Current password
     */
    old_password: string;
    /**
     * New password (min 8 characters)
     */
    new_password: string;
    [key: string]: unknown | string;
};

/**
 * Hierarchical node for file operation tree.
 */
export type ChangesetNode = {
    name: string;
    path: string;
    is_dir: boolean;
    operation?: (string | null);
    diff?: (string | null);
    children?: Array<ChangesetNode>;
    [key: string]: unknown | string | boolean | ChangesetNode;
};

export type ChatRequest = {
    project_id?: (number | null);
    thread_id: string;
    message: string;
    model?: (string | null);
    command_id?: (number | null);
    checkpoint_id?: (string | null);
    message_id?: (number | null);
    attachments?: (Array<{
    [key: string]: unknown;
}> | null);
    skill_id?: (number | null);
    revert_files?: boolean;
};

export type CheckMobileRequest = {
    mobile: string;
    [key: string]: unknown | string;
};

export type CleanupRecordingResponse = {
    success?: boolean;
    message?: string;
    deleted: {
        [key: string]: unknown;
    };
    [key: string]: unknown | boolean | string;
};

export type CloudStatusResponse = {
    success?: boolean;
    message?: string;
    is_logged_in: boolean;
    device_id?: (string | null);
    is_linked: boolean;
    device_name: string;
    api_url: string;
    [key: string]: unknown | boolean | string;
};

/**
 * Response for listing collections.
 */
export type CollectionResponse = {
    success?: boolean;
    message?: string;
    collections: Array<(string)>;
    stats: {
        [key: string]: unknown;
    };
    [key: string]: unknown | boolean | string;
};

/**
 * Dynamic command parameters for device control.
 *
 * Different command_types accept different parameters.
 * Extra fields are allowed to support all command types.
 */
export type CommandParams = {
    [key: string]: unknown;
};

export type ConceptCreate = {
    name: string;
    description: string;
    related_files?: (Array<(string)> | null);
    [key: string]: unknown | string;
};

/**
 * Response for concept add/delete/update operations.
 */
export type ConceptOperationResponse = {
    success?: boolean;
    message?: string;
    status: string;
    name: string;
    [key: string]: unknown | boolean | string;
};

export type ConceptResponse = {
    success?: boolean;
    message?: string;
    name: string;
    description?: (string | null);
    episode_count?: (number | null);
    [key: string]: unknown | boolean | string;
};

export type ConceptUpdate = {
    description?: (string | null);
    related_files?: (Array<(string)> | null);
    [key: string]: unknown;
};

export type ConversationListItem = {
    thread_id: string;
    title: string;
    project_id: (number | null);
    updated_at: (string | null);
    status?: string;
    [key: string]: unknown | string;
};

export type ConversationSearchResult = {
    id: number;
    thread_id: string;
    role: string;
    content: string;
    created_at: string;
    match_snippet?: (string | null);
    [key: string]: unknown | number | string;
};

export type CreateFileRequest = {
    path: string;
    content: string;
    [key: string]: unknown | string;
};

export type CreateOrderRequest = {
    level_id: number;
    auto_renew?: boolean;
    [key: string]: unknown | number | boolean;
};

export type CreateProjectRequest = {
    name: string;
    description?: string;
    path: string;
    [key: string]: unknown | string;
};

/**
 * Request to create a skill from YAML macro definition.
 */
export type CreateSkillFromYamlRequest = {
    name: string;
    description?: (string | null);
    namespace?: (string | null);
    yaml_content: string;
};

export type CreateSkillFromYamlResponse = {
    success?: boolean;
    message?: string;
    skill_id: number;
    skill_name: string;
    step_count: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * EvoCloud debug status response.
 */
export type DebugStatusResponse = {
    success?: boolean;
    message?: string;
    is_logged_in: boolean;
    token_prefix: (string | null);
    device_id: (string | null);
    device_name: string;
    is_connected: boolean;
    api_url: string;
    [key: string]: unknown | boolean | string;
};

/**
 * Detected project awaiting import.
 */
export type DetectedProjectItem = {
    id: number;
    name: string;
    path: (string | null);
    detected_at: (string | null);
    [key: string]: unknown | number | string;
};

/**
 * Response for detected projects.
 */
export type DetectedProjectsResponse = {
    success?: boolean;
    message?: string;
    data?: Array<DetectedProjectItem>;
    total?: number;
    page?: number;
    page_size?: number;
    [key: string]: unknown | boolean | string | DetectedProjectItem | number;
};

export type DeviceResolutionResponse = {
    success?: boolean;
    message?: string;
    width: number;
    height: number;
    [key: string]: unknown | boolean | string | number;
};

export type DiscoverRequest = {
    record_secrets?: boolean;
    [key: string]: unknown | boolean;
};

export type DiscoverResponse = {
    success?: boolean;
    message?: string;
    status: string;
    project_id: number;
    thread_id: string;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Response for reading document content.
 */
export type DocumentContentResponse = {
    success?: boolean;
    message?: string;
    path: string;
    content: string;
    metadata: DocumentMetadataResponse;
    offset: number;
    limit: number;
    total_lines: number;
    has_more: boolean;
    [key: string]: unknown | boolean | string | DocumentMetadataResponse | number;
};

/**
 * Item in a document list from the knowledge base.
 */
export type DocumentListItem = {
    path: string;
    size_bytes: number;
    modified_at: string;
    has_metadata: boolean;
    tags: Array<(string)>;
    title: string;
    source?: (string | null);
    source_project_id?: (number | null);
    [key: string]: unknown | string | number | boolean;
};

/**
 * Response for listing documents.
 */
export type DocumentListResponse = {
    success?: boolean;
    message?: string;
    data?: Array<DocumentListItem>;
    total?: number;
    page?: number;
    page_size?: number;
    documents: Array<DocumentListItem>;
    collections: Array<(string)>;
    [key: string]: unknown | boolean | string | DocumentListItem | number;
};

/**
 * Structured metadata for a document chunk/response.
 */
export type DocumentMetadataResponse = {
    success?: boolean;
    message?: string;
    title?: (string | null);
    source_file?: (string | null);
    source_mime_type?: (string | null);
    file_size_bytes?: (number | null);
    extracted_at?: (string | null);
    source_project_id?: (number | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Response for document operations.
 */
export type DocumentResponse = {
    success?: boolean;
    message?: string;
    path?: (string | null);
    document?: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Single document search result.
 */
export type DocumentSearchItem = {
    path: string;
    match_count: number;
    matches: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | string | number;
};

/**
 * Response for document search.
 */
export type DocumentSearchResponse = {
    query: string;
    results: Array<DocumentSearchItem>;
    total: number;
};

/**
 * DOM 事件数据
 */
export type DomEventData = {
    timestamp: number;
    event_type: string;
    selector?: (string | null);
    target_text?: (string | null);
    value?: (string | null);
    url?: (string | null);
    xpath?: (string | null);
    coordinates?: ({
    [key: string]: unknown;
} | null);
};

/**
 * 请求模型：接收 DOM 事件
 */
export type DomEventsRequest = {
    project_id?: (number | null);
    thread_id: string;
    session_id: string;
    events: Array<DomEventData>;
};

export type EmbeddingApplyResponse = {
    success?: boolean;
    message?: string;
    status: string;
    [key: string]: unknown | boolean | string;
};

export type EmbeddingConfigRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    /**
     * openai, ollama, or generic
     */
    provider: string;
    /**
     * API Base URL
     */
    base_url: string;
    /**
     * Model Name
     */
    model: string;
    dimensions?: (number | null);
    api_key?: (string | null);
};

export type EmbeddingTestResponse = {
    success?: boolean;
    message?: string;
    dimensions?: (number | null);
    [key: string]: unknown | boolean | string;
};

export type EpisodeResponse = {
    success?: boolean;
    message?: string;
    id: string;
    goal: string;
    result: (string | null);
    error: (string | null);
    timestamp: (string | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Generic transparent proxy response from EvoCloud / Member Center APIs.
 */
export type EvoCloudProxyResponse = {
    code?: number;
    message?: (string | null);
    data?: (unknown | null);
    success?: (boolean | null);
    [key: string]: unknown | number;
};

export type EvoloopStatusResponse = {
    success?: boolean;
    message?: string;
    connected: boolean;
    device_id?: (string | null);
    device_name: string;
    [key: string]: unknown | boolean | string;
};

export type ExecuteSkillRequest = {
    project_id?: (number | null);
    thread_id: string;
    params: SkillExecutionParams;
    execution_mode?: (string | null);
};

export type ExecuteSkillResponse = {
    success?: boolean;
    message?: string;
    execution_mode: string;
    [key: string]: unknown | boolean | string;
};

export type FileContent = {
    content: string;
    language: string;
    [key: string]: unknown | string;
};

/**
 * Single file name search result.
 */
export type FileNameSearchResult = {
    name: string;
    path: string;
    type: string;
    [key: string]: unknown | string;
};

export type FileNode = {
    name: string;
    path: string;
    type: string;
    children?: (Array<FileNode> | null);
    [key: string]: unknown | string;
};

/**
 * Single file content search result.
 */
export type FileSearchResult = {
    file: string;
    line: number;
    content: string;
    [key: string]: unknown | string | number;
};

/**
 * Response for FTS search.
 */
export type FTSSearchResponse = {
    query: string;
    results: Array<FTSSearchResult>;
    total: number;
    facets: {
        [key: string]: unknown;
    };
};

/**
 * Single FTS search result.
 */
export type FTSSearchResult = {
    doc_id: string;
    path: string;
    collection: (string | null);
    title: string;
    snippet: string;
    highlights: string;
    score: number;
    [key: string]: unknown | string | number;
};

/**
 * Response for FTS suggestions.
 */
export type FTSSuggestResponse = {
    success?: boolean;
    message?: string;
    suggestions: Array<(string)>;
    [key: string]: unknown | boolean | string;
};

/**
 * 全局桌面事件数据
 */
export type GlobalEventData = {
    timestamp: number;
    event_type: string;
    key?: (string | null);
    mouse_button?: (string | null);
    position?: ([
    number,
    number
] | null);
    window_title?: (string | null);
    app_name?: (string | null);
    process_id?: (number | null);
    source?: (string | null);
};

/**
 * 请求模型：接收全局桌面事件
 */
export type GlobalEventsRequest = {
    project_id?: (number | null);
    thread_id: string;
    session_id: string;
    events: Array<GlobalEventData>;
};

export type HealthCheckResponse = {
    success?: boolean;
    message?: string;
    status: string;
    service: string;
    [key: string]: unknown | boolean | string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type HumanInputRequestOut = {
    id: string;
    thread_id: string;
    request_type: string;
    prompt: string;
    options?: (Array<(string)> | null);
    context?: (string | null);
    default_value?: (string | null);
    created_at: string;
    status: string;
};

/**
 * Single item in hybrid search results.
 */
export type HybridResultItem = {
    type: string;
    score: number;
    data: {
        [key: string]: unknown;
    };
    [key: string]: unknown | string | number;
};

/**
 * Hybrid search response.
 */
export type HybridSearchResponse = {
    success?: boolean;
    message?: string;
    data?: Array<HybridResultItem>;
    total?: number;
    page?: number;
    page_size?: number;
    query: string;
    search_type: string;
    vector_results_count?: (number | null);
    text_results_count?: (number | null);
    [key: string]: unknown | boolean | string | HybridResultItem | number;
};

/**
 * Project ignore response.
 */
export type IgnoreProjectResponse = {
    success?: boolean;
    message?: string;
    status: string;
    repo_id: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Project import response.
 */
export type ImportProjectResponse = {
    success?: boolean;
    message?: string;
    status: string;
    repo_id: number;
    name: string;
    [key: string]: unknown | boolean | string | number;
};

export type ImportSkillsRequest = {
    directory: string;
};

export type ImportSkillsResponse = {
    success?: boolean;
    message?: string;
    results: {
        [key: string]: unknown;
    };
    [key: string]: unknown | boolean | string;
};

export type IndexingRequest = {
    project_id: number;
    thread_id?: (string | null);
};

/**
 * Indexing dispatch response.
 */
export type IndexingRunResponse = {
    success?: boolean;
    message?: string;
    status: string;
    project_id: number;
    [key: string]: unknown | boolean | string | number;
};

export type LLMApplyResponse = {
    success?: boolean;
    message?: string;
    status: string;
    [key: string]: unknown | boolean | string;
};

export type LLMConfigRequest = {
    /**
     * 供应商名称: openai, anthropic, moonshot, deepseek
     */
    provider: string;
    /**
     * 协议类型: openai | anthropic
     */
    provider_type?: string;
    /**
     * API Base URL
     */
    base_url: string;
    /**
     * Model Name
     */
    model: string;
    /**
     * Vision Model Name (e.g. gpt-4o)
     */
    vision_model?: (string | null);
    api_key?: (string | null);
    [key: string]: unknown | string;
};

export type LLMTestResponse = {
    success?: boolean;
    message?: string;
    reply?: (string | null);
    [key: string]: unknown | boolean | string;
};

export type LoginMobileRequest = {
    mobile: string;
    key: string;
    code: string;
    [key: string]: unknown | string;
};

/**
 * Enriched login result from EvoCloud auth methods.
 */
export type LoginResult = {
    success: boolean;
    token?: (string | null);
    member_id?: (number | null);
    data?: ({
    [key: string]: unknown;
} | null);
    message?: (string | null);
    [key: string]: unknown | boolean;
};

export type LogoutResponse = {
    success?: boolean;
    message?: string;
    code: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Response for MCP connect operation.
 */
export type McpConnectResponse = {
    success?: boolean;
    message?: string;
    status: string;
    name: string;
    tools_count: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Response for MCP add/remove operations.
 */
export type McpOperationResponse = {
    success?: boolean;
    message?: string;
    status: string;
    [key: string]: unknown | boolean | string;
};

export type McpServerCreate = {
    name: string;
    command: string;
    args?: (Array<(string)> | null);
    env?: ({
    [key: string]: (string);
} | null);
    [key: string]: unknown | string;
};

export type MemberBenefitsResponse = {
    code?: number;
    data?: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown | number;
};

export type MessageItem = {
    id?: (string | null);
    role: string;
    content?: string;
    thinking?: (string | null);
    created_at?: (string | null);
    steps?: Array<ToolStep>;
    tool_calls?: (Array<{
    [key: string]: unknown;
}> | null);
    metadata?: {
        [key: string]: unknown;
    };
    steps_snapshot?: (Array<{
    [key: string]: unknown;
}> | null);
    run_id?: (string | null);
    parent_id?: (number | null);
    references?: Array<ReferenceItem>;
    has_file_operations?: boolean;
    changeset_count?: number;
    [key: string]: unknown | string | ToolStep | ReferenceItem | boolean | number;
};

/**
 * Response model for paginated message list.
 */
export type MessageListResponse = {
    success?: boolean;
    message?: string;
    data?: Array<MessageItem>;
    total?: number;
    page?: number;
    page_size?: number;
    has_more: boolean;
    first_id?: (number | null);
    last_id?: (number | null);
    total_count?: (number | null);
    [key: string]: unknown | boolean | string | MessageItem | number;
};

export type MessageResponse = {
    success?: boolean;
    message?: string;
    [key: string]: unknown | boolean | string;
};

export type MirrorDevicesResponse = {
    success?: boolean;
    message?: string;
    devices: Array<{
        [key: string]: unknown;
    }>;
    scrcpy_available: boolean;
    [key: string]: unknown | boolean | string;
};

export type MirrorPersistResponse = {
    success?: boolean;
    message?: string;
    count: number;
    [key: string]: unknown | boolean | string | number;
};

export type MirrorRecordingResponse = {
    success?: boolean;
    message?: string;
    session_id: string;
    [key: string]: unknown | boolean | string;
};

export type MirrorSessionResponse = {
    success?: boolean;
    message?: string;
    session_id: string;
    device_id: string;
    [key: string]: unknown | boolean | string;
};

export type MobileCodeRequest = {
    /**
     * Phone number
     */
    mobile: string;
    captcha_id?: (string | null);
    captcha_code?: (string | null);
    [key: string]: unknown | string;
};

export type MobileCodeResponse = {
    success?: boolean;
    message?: string;
    code: number;
    key?: (string | null);
    [key: string]: unknown | boolean | string | number;
};

export type MobileLoginRequest = {
    /**
     * Phone number
     */
    mobile: string;
    /**
     * SMS verification code
     */
    code: string;
    /**
     * Verification key returned from code request
     */
    key: string;
    [key: string]: unknown | string;
};

export type ModelsListResponse = {
    success?: boolean;
    message?: string;
    models: Array<{
        [key: string]: unknown;
    }>;
    last_updated: string;
    [key: string]: unknown | boolean | string;
};

/**
 * Response for next executable task.
 */
export type NextTaskResponse = {
    success?: boolean;
    message?: string;
    task: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown | boolean | string;
};

export type OpenFileRequest = {
    path: string;
    [key: string]: unknown | string;
};

/**
 * Simple operation status response.
 */
export type OperationResponse = {
    success?: boolean;
    message?: string;
    status: string;
    id: number;
    [key: string]: unknown | boolean | string | number;
};

export type PaginatedSkillsResponse = {
    success?: boolean;
    message?: string;
    data?: Array<SkillDTO>;
    total?: number;
    page?: number;
    page_size?: number;
    [key: string]: unknown | boolean | string | SkillDTO | number;
};

/**
 * 请求模型：持久化存储镜像事件
 */
export type PersistMirrorEventsRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    session_id: string;
};

/**
 * Nested plan data.
 */
export type PlanDataResponse = {
    id: string;
    title: string;
    steps: Array<PlanStepResponse>;
    current_step_id: (string | null);
    [key: string]: unknown | string | PlanStepResponse;
};

/**
 * Plan API response.
 */
export type PlanResponse = {
    success?: boolean;
    message?: string;
    status: string;
    plan?: (PlanDataResponse | null);
    generated_at?: (string | null);
    error?: (string | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Plan step item.
 */
export type PlanStepResponse = {
    success?: boolean;
    message?: string;
    id: string;
    title: string;
    status: string;
    result: (string | null);
    [key: string]: unknown | boolean | string;
};

export type PreviewEventsSummary = {
    total: number;
    types: Array<(string)>;
};

export type PreviewKeyframeSummary = {
    planned: number;
    est_frames: number;
    est_tokens: string;
    details: Array<{
        [key: string]: unknown;
    }>;
};

export type PreviewRecordingDataResponse = {
    success?: boolean;
    message?: string;
    video_info: PreviewVideoInfo;
    events: PreviewEventsSummary;
    keyframes: PreviewKeyframeSummary;
    [key: string]: unknown | boolean | string | PreviewVideoInfo | PreviewEventsSummary | PreviewKeyframeSummary;
};

export type PreviewVideoInfo = {
    path: string;
    duration: number;
    resolution: string;
    fps: number;
};

export type ProfileContentResponse = {
    success?: boolean;
    message?: string;
    content?: (string | null);
    exists?: boolean;
    [key: string]: unknown | boolean | string;
};

/**
 * Project deletion response.
 */
export type ProjectDeleteResponse = {
    success?: boolean;
    message?: string;
    status: string;
    id: number;
    [key: string]: unknown | boolean | string | number;
};

export type ProjectDiscoveryConfigRequest = {
    enabled: boolean;
    [key: string]: unknown | boolean;
};

export type ProjectDiscoveryConfigUpdateResponse = {
    success?: boolean;
    message?: string;
    enabled: boolean;
    locked?: (boolean | null);
    [key: string]: unknown | boolean | string;
};

/**
 * System task activity state.
 */
export type ProjectStatusActivity = {
    status?: string;
    updated_at?: number;
    agent_state?: {
        [key: string]: unknown;
    };
    steps?: Array<unknown>;
    [key: string]: unknown | string | number;
};

/**
 * Real-time project system status.
 */
export type ProjectStatusResponse = {
    success?: boolean;
    message?: string;
    indexing: ProjectStatusActivity;
    summarization: ProjectStatusActivity;
    wiki: ProjectStatusActivity;
    [key: string]: unknown | boolean | string | ProjectStatusActivity;
};

export type RecordingSessionItem = {
    session_id: string;
    thread_id: string;
    task_name?: (string | null);
    started_at: string;
    event_count: number;
};

export type RecordingSessionsResponse = {
    success?: boolean;
    message?: string;
    sessions: Array<RecordingSessionItem>;
    [key: string]: unknown | boolean | string | RecordingSessionItem;
};

export type ReferenceItem = {
    id: string;
    type: string;
    target_id: string;
    target_name: string;
    metadata?: (ReferenceItemMetadata | null);
    [key: string]: unknown | string;
};

/**
 * Metadata for a message reference. Extra fields allowed per reference type.
 */
export type ReferenceItemMetadata = {
    duration?: (number | null);
    transcript?: (string | null);
    waveform?: (Array<(number)> | null);
    url?: (string | null);
    mime_type?: (string | null);
    [key: string]: unknown;
};

export type RegisterMobileRequest = {
    mobile: string;
    key: string;
    code: string;
    captcha_id?: (string | null);
    captcha_code?: (string | null);
    [key: string]: unknown | string;
};

export type RegisterUsernameRequest = {
    username: string;
    password: string;
    captcha_id?: (string | null);
    captcha_code?: (string | null);
    [key: string]: unknown | string;
};

export type RenameRequest = {
    title: string;
    [key: string]: unknown | string;
};

/**
 * Analysis item in requirement detail.
 */
export type RequirementAnalysisItem = {
    id: string;
    status: string;
    version: number;
    data: ({
    [key: string]: unknown;
} | null);
    user_edited: boolean;
    confirmed_at: (string | null);
    tasks_count: number;
    synced_tasks: number;
    [key: string]: unknown | string | number | boolean;
};

/**
 * Response after deleting a requirement document.
 */
export type RequirementDeleteResponse = {
    success?: boolean;
    message?: string;
    status: string;
    document_id: string;
    [key: string]: unknown | boolean | string;
};

/**
 * Response for requirement document detail.
 */
export type RequirementDetailResponse = {
    success?: boolean;
    message?: string;
    id: string;
    file_name: string;
    file_type: string;
    file_size: number;
    status: string;
    raw_content_preview: (string | null);
    created_at: (string | null);
    updated_at: (string | null);
    analyses: Array<RequirementAnalysisItem>;
    [key: string]: unknown | boolean | string | number | RequirementAnalysisItem;
};

/**
 * Item in requirement document list.
 */
export type RequirementListItem = {
    id: string;
    file_name: string;
    file_type: string;
    status: string;
    created_at: (string | null);
    analysis_count: number;
    [key: string]: unknown | string | number;
};

/**
 * Response for listing requirement documents.
 */
export type RequirementListResponse = {
    success?: boolean;
    message?: string;
    data?: Array<RequirementListItem>;
    total?: number;
    page?: number;
    page_size?: number;
    [key: string]: unknown | boolean | string | RequirementListItem | number;
};

/**
 * Requirement to task mapping.
 */
export type RequirementMapping = {
    by_requirement: {
        [key: string]: Array<(string)>;
    };
    by_task: {
        [key: string]: Array<(string)>;
    };
    unmapped_tasks: Array<(string)>;
    [key: string]: unknown | string;
};

/**
 * Sync progress stats.
 */
export type RequirementProgress = {
    total: number;
    synced: number;
    failed: number;
    syncing: number;
    pending: number;
    percentage: number;
    is_complete: boolean;
    has_failures: boolean;
    [key: string]: unknown | number | boolean;
};

/**
 * Response for sync progress.
 */
export type RequirementSyncProgressResponse = {
    success?: boolean;
    message?: string;
    analysis_id: string;
    progress: RequirementProgress;
    last_updated: (string | null);
    [key: string]: unknown | boolean | string | RequirementProgress;
};

/**
 * Task item in requirement task list.
 */
export type RequirementTaskItem = {
    id: string;
    title: string;
    description: string;
    priority: string;
    estimated_hours: number;
    category: string;
    tags: Array<(string)>;
    requirement_refs: Array<(string)>;
    acceptance_criteria: Array<(string)>;
    sync_status: string;
    sync_error: (string | null);
    evocloud_task_id: (string | null);
    synced_at: (string | null);
    created_at: (string | null);
    [key: string]: unknown | string | number;
};

/**
 * Response for analysis tasks.
 */
export type RequirementTasksResponse = {
    success?: boolean;
    message?: string;
    analysis_id: string;
    document_id: string;
    project_id: number;
    sync_stats: {
        [key: string]: (number);
    };
    tasks: Array<RequirementTaskItem>;
    requirement_mapping: RequirementMapping;
    [key: string]: unknown | boolean | string | number | RequirementTaskItem | RequirementMapping;
};

/**
 * Response after uploading a requirement document.
 */
export type RequirementUploadResponse = {
    success?: boolean;
    message?: string;
    document_id: string;
    thread_id: string;
    status: string;
    [key: string]: unknown | boolean | string;
};

export type ResetKnowledgeResponse = {
    success?: boolean;
    message?: string;
    status: string;
    [key: string]: unknown | boolean | string;
};

export type ResetPasswordMobileRequest = {
    mobile: string;
    key: string;
    code: string;
    password: string;
    [key: string]: unknown | string;
};

export type ResourceCreate = {
    type: 'file' | 'link';
    name: string;
    content: string;
    [key: string]: unknown | string;
};

export type type = 'file' | 'link';

export type ResourceResponse = {
    success?: boolean;
    message?: string;
    id: number;
    project_id: number;
    type: string;
    name: string;
    content: string;
    created_at: string;
    [key: string]: unknown | boolean | string | number;
};

export type RespondRequest = {
    response: unknown;
};

export type ResumeRequest = {
    project_id?: (number | null);
    thread_id: string;
    user_input?: (string | null);
    command_id?: (number | null);
};

export type RewindRequest = {
    revert_files?: boolean;
    message_id?: (string | null);
    [key: string]: unknown | boolean;
};

export type RewindResponse = {
    success?: boolean;
    message?: string;
    status: string;
    thread_id: string;
    removed_count?: number;
    files_reverted?: number;
    [key: string]: unknown | boolean | string | number;
};

export type SendCommandRequest = {
    command_type: string;
    params?: CommandParams;
    [key: string]: unknown | string | CommandParams;
};

export type SkillDetailResponse = {
    id: number;
    name: string;
    description: string;
    namespace?: (string | null);
    trigger_patterns: Array<(string)>;
    parameters: Array<SkillParameter>;
    tools_used: Array<(string)>;
    success_count: number;
    failure_count: number;
    is_active: boolean;
    status: string;
    execution_mode?: string;
    macro_script?: (string | null);
    validation_report?: ({
    [key: string]: unknown;
} | null);
    instructions?: (string | null);
    created_at: string;
    updated_at: string;
    preconditions?: Array<{
        [key: string]: unknown;
    }>;
    source_thread_id?: (string | null);
    source_session_id?: (string | null);
    resource_path?: (string | null);
};

export type SkillDTO = {
    id: number;
    name: string;
    description: string;
    namespace?: (string | null);
    trigger_patterns: Array<(string)>;
    parameters: Array<SkillParameter>;
    tools_used: Array<(string)>;
    success_count: number;
    failure_count: number;
    is_active: boolean;
    status: string;
    execution_mode?: string;
    macro_script?: (string | null);
    validation_report?: ({
    [key: string]: unknown;
} | null);
    instructions?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Parameters for skill execution. Extra fields are allowed per skill type.
 */
export type SkillExecutionParams = {
    [key: string]: unknown;
};

/**
 * Shared parameter definition for learned skills.
 */
export type SkillParameter = {
    name: string;
    type?: string;
    description?: string;
    default?: (unknown | null);
    required?: boolean;
};

/**
 * 智能合成请求
 */
export type SmartSynthesisRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    session_id: string;
    task_goal: string;
    annotation_ids?: (Array<(number)> | null);
};

/**
 * 智能合成响应
 */
export type SmartSynthesisResponse = {
    success?: boolean;
    message?: string;
    job_id: number;
    status: string;
    [key: string]: unknown | boolean | string | number;
};

/**
 * [NEW] Request to start event recording for an active mirror session.
 */
export type StartMirrorRecordingRequest = {
    session_id: string;
};

export type StartMirrorRequest = {
    device_id: string;
    record_video?: boolean;
};

export type StartRecordingRequest = {
    project_id?: (number | null);
    thread_id: string;
    task_name?: (string | null);
};

export type StartRecordingResponse = {
    success?: boolean;
    message?: string;
    session_id: string;
    [key: string]: unknown | boolean | string;
};

/**
 * Response for stopping a chat.
 */
export type StopChatResponse = {
    success?: boolean;
    message?: string;
    status: string;
    thread_id: string;
    [key: string]: unknown | boolean | string;
};

export type StopMirrorRequest = {
    session_id: string;
};

export type StopMirrorResponse = {
    success?: boolean;
    message?: string;
    video_path?: (string | null);
    session_id: string;
    event_count: number;
    [key: string]: unknown | boolean | string | number;
};

export type StopRecordingResponse = {
    success?: boolean;
    message?: string;
    session_id: string;
    event_count: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * STT 提供商列表响应
 */
export type STTProvidersResponse = {
    success?: boolean;
    message?: string;
    providers: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | boolean | string;
};

/**
 * Subtask creation request.
 */
export type SubtaskCreate = {
    title: string;
    description?: string;
    priority?: string;
    estimated_hours?: number;
    [key: string]: unknown | string | number;
};

/**
 * Code symbol search result.
 */
export type SymbolResponse = {
    success?: boolean;
    message?: string;
    id: number;
    name: string;
    full_name: string;
    type: string;
    file_path: string;
    start_line: number;
    end_line: number;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Response for symbol wiki generation.
 */
export type SymbolWikiResponse = {
    success?: boolean;
    message?: string;
    content: string;
    [key: string]: unknown | boolean | string;
};

/**
 * 合成任务状态响应
 */
export type SynthesisJobResponse = {
    success?: boolean;
    message?: string;
    id: number;
    session_id: string;
    status: string;
    progress_percent: number;
    current_phase: (string | null);
    task_goal: string;
    created_at: string;
    started_at: (string | null);
    completed_at: (string | null);
    result: ({
    [key: string]: unknown;
} | null);
    error: ({
    [key: string]: unknown;
} | null);
    [key: string]: unknown | boolean | string | number;
};

/**
 * 从录制合成 Skill 的请求（v3 统一版）
 *
 * [v3 统一架构] 所有录制类型（Desktop/Global/Android）的事件都已通过
 * 实时 API（/global/events, /dom/events, /mirror/events）持久化到数据库，
 * 合成时统一从数据库读取，不再支持通过请求体传入事件。
 */
export type SynthesizeFromRecordingRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    video_path: string;
    session_id: string;
    task_description: string;
};

/**
 * 从录制合成 Skill 的响应
 */
export type SynthesizeFromRecordingResponse = {
    success?: boolean;
    message?: string;
    skill_id: (number | null);
    skill_name: (string | null);
    skill_yaml: (string | null);
    macro_script?: (string | null);
    verification?: ({
    [key: string]: unknown;
} | null);
    error: (string | null);
    processing_time_seconds: number;
    frames_analyzed: number;
    events_processed: number;
    [key: string]: unknown | boolean | string | number;
};

export type SynthesizeRequest = {
    project_id?: (number | null);
    thread_id: string;
    session_id?: (string | null);
    auto_optimize?: boolean;
};

export type SynthesizeSkillResponse = {
    success?: boolean;
    message?: string;
    skill_id: number;
    skill_name: string;
    skill_yaml: string;
    [key: string]: unknown | boolean | string | number;
};

export type SystemConfig = {
    key: string;
    value: string;
    description?: (string | null);
};

export type SystemStatusResponse = {
    success?: boolean;
    message?: string;
    cpu_percent: number;
    ram_percent: number;
    ram_used_gb: number;
    ram_total_gb: number;
    status?: string;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Single tag with document count.
 */
export type TagItem = {
    name: string;
    count: number;
    [key: string]: unknown | string | number;
};

/**
 * Response for listing tags.
 */
export type TagResponse = {
    success?: boolean;
    message?: string;
    tags: Array<TagItem>;
    total: number;
    [key: string]: unknown | boolean | string | TagItem | number;
};

export type TaskCreateRequest = {
    project_id: number;
    thread_id?: (string | null);
    task_title: string;
    task_desc?: (string | null);
    priority?: number;
    match_score?: (number | null);
    relevance_analysis?: (string | null);
    key_modules?: (unknown | null);
    technical_challenges?: (unknown | null);
    implementation_complexity?: (string | null);
    deliverables?: (unknown | null);
};

/**
 * Response after creating a task with subtasks.
 */
export type TaskCreateResponse = {
    success?: boolean;
    message?: string;
    task: {
        [key: string]: unknown;
    };
    [key: string]: unknown | boolean | string;
};

/**
 * Response for flattened task tree.
 */
export type TaskFlatResponse = {
    success?: boolean;
    message?: string;
    count: number;
    tasks: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | boolean | string | number;
};

/**
 * Item in root task list.
 */
export type TaskListItem = {
    id: string;
    title: string;
    status: string;
    progress: number;
    priority: string;
    has_subtasks: boolean;
    created_at: (string | null);
    [key: string]: unknown | string | number | boolean;
};

/**
 * Response for listing root tasks.
 */
export type TaskListResponse = {
    success?: boolean;
    message?: string;
    count: number;
    tasks: Array<TaskListItem>;
    [key: string]: unknown | boolean | string | number | TaskListItem;
};

/**
 * Task progress update.
 */
export type TaskProgressUpdate = {
    status?: (string | null);
    progress?: (number | null);
    result?: (string | null);
    [key: string]: unknown;
};

/**
 * Response after updating task progress.
 */
export type TaskProgressUpdateResponse = {
    success?: boolean;
    message?: string;
    [key: string]: unknown | boolean | string;
};

export type TaskStatusUpdate = {
    status: number;
    progress?: (number | null);
    [key: string]: unknown | number;
};

/**
 * Response wrapping a task tree.
 */
export type TaskTreeWrapperResponse = {
    success?: boolean;
    message?: string;
    task: {
        [key: string]: unknown;
    };
    [key: string]: unknown | boolean | string;
};

export type TaskUpdateRequest = {
    task_title?: (string | null);
    task_desc?: (string | null);
    priority?: (number | null);
    status?: (number | null);
    progress?: (number | null);
    match_score?: (number | null);
    relevance_analysis?: (string | null);
    key_modules?: (unknown | null);
    technical_challenges?: (unknown | null);
    implementation_complexity?: (string | null);
    deliverables?: (unknown | null);
    [key: string]: unknown;
};

/**
 * Create parent task with subtasks.
 */
export type TaskWithSubtasksCreate = {
    title: string;
    description?: string;
    priority?: string;
    estimated_hours?: number;
    subtasks?: Array<SubtaskCreate>;
    analysis_id?: (string | null);
    [key: string]: unknown | string | number | SubtaskCreate;
};

export type TimesheetQuickAddRequest = {
    project_id: number;
    thread_id?: (string | null);
    hours: number;
    description: string;
    work_type?: (string | null);
};

/**
 * Schema for creating a new Todo.
 */
export type TodoCreate = {
    title: string;
    description?: (string | null);
    priority?: ('low' | 'medium' | 'high' | TodoPriority);
    category?: (string | null);
    due_date?: (string | null);
    project_id?: (number | null);
    source_conversation_id?: (string | null);
    source_message_id?: (string | null);
};

export type TodoPriority = 'low' | 'medium' | 'high';

/**
 * Schema for Todo responses.
 */
export type TodoResponse = {
    id: string;
    title: string;
    description: (string | null);
    status: TodoStatus;
    priority: TodoPriority;
    category: (string | null);
    due_date: (string | null);
    source_conversation_id: (string | null);
    source_message_id: (string | null);
    project_id: (number | null);
    created_at: string;
    updated_at: string;
};

export type TodoStatus = 'pending' | 'completed' | 'cancelled';

/**
 * Schema for updating an existing Todo.
 */
export type TodoUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (TodoStatus | null);
    priority?: ('low' | 'medium' | 'high' | TodoPriority | null);
    category?: (string | null);
    due_date?: (string | null);
    project_id?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ToolInfo = {
    name: string;
    description: string;
    args_schema?: ({
    [key: string]: unknown;
} | null);
    is_runtime?: (boolean | null);
    [key: string]: unknown | string;
};

/**
 * Standard model for a single tool execution step within an AI message.
 * Used for both persistent history and real-time streaming.
 */
export type ToolStep = {
    id: string;
    tool: string;
    tool_name?: (string | null);
    input?: ({
    [key: string]: unknown;
} | string | unknown);
    output?: string;
    status?: string;
    duration?: (number | null);
    tool_call_id?: (string | null);
    [key: string]: unknown | string;
};

/**
 * 语音识别响应
 */
export type TranscriptionResponse = {
    success?: boolean;
    message?: string;
    text: string;
    duration: number;
    language: string;
    confidence?: (number | null);
    [key: string]: unknown | boolean | string | number;
};

/**
 * 语音合成请求
 */
export type TTSRequest = {
    text: string;
    voice_id?: string;
    speed?: number;
    format?: string;
    [key: string]: unknown | string | number;
};

/**
 * 语音合成响应
 */
export type TTSResponse = {
    success?: boolean;
    message?: string;
    url: string;
    duration?: (number | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Project unignore response.
 */
export type UnignoreProjectResponse = {
    success?: boolean;
    message?: string;
    status: string;
    repo_id: number;
    name: string;
    [key: string]: unknown | boolean | string | number;
};

export type UpdateSkillFromYamlResponse = {
    success?: boolean;
    message?: string;
    step_count: number;
    [key: string]: unknown | boolean | string | number;
};

export type UpdateSkillRequest = {
    name?: (string | null);
    description?: (string | null);
    namespace?: (string | null);
    trigger_patterns?: (Array<(string)> | null);
    parameters?: (Array<{
    [key: string]: unknown;
}> | null);
    instructions?: (string | null);
    preconditions?: (Array<{
    [key: string]: unknown;
}> | null);
    execution_mode?: (string | null);
    macro_script?: (string | null);
};

export type UpdateSkillResponse = {
    success?: boolean;
    message?: string;
    skill: SkillDetailResponse;
    [key: string]: unknown | boolean | string | SkillDetailResponse;
};

export type UpdateUserRequest = {
    /**
     * User nickname
     */
    nickname?: (string | null);
    /**
     * Avatar URL
     */
    headimg?: (string | null);
    /**
     * Email address
     */
    email?: (string | null);
    [key: string]: unknown;
};

export type UploadScreenshotResponse = {
    success?: boolean;
    message?: string;
    path: string;
    [key: string]: unknown | boolean | string;
};

export type UserPublic = {
    id: (number | string);
    username?: (string | null);
    nickname?: (string | null);
    mobile?: (string | null);
    email?: (string | null);
    headimg?: (string | null);
    member_level?: number;
    member_level_name?: (string | null);
    member_level_type?: number;
    level_expire_time?: number;
    member_label?: number;
    member_label_name?: (string | null);
    member_code?: (string | null);
    point?: number;
    balance?: number;
    balance_money?: number;
    growth?: number;
    status?: number;
    has_password?: boolean;
    is_edit_username?: number;
    is_fenxiao?: number;
    realname?: (string | null);
    sex?: number;
    birthday?: (string | null);
    source_member?: number;
    province_id?: number;
    city_id?: number;
    district_id?: number;
    address?: (string | null);
    full_address?: (string | null);
    longitude?: number;
    latitude?: number;
    wx_openid?: (string | null);
    wx_unionid?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
};

export type ValidateSkillResponse = {
    success?: boolean;
    message?: string;
    validation?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    [key: string]: unknown | boolean | string;
};

/**
 * Request to validate YAML macro format.
 */
export type ValidateYamlRequest = {
    yaml_content: string;
};

/**
 * Response from YAML validation.
 */
export type ValidateYamlResponse = {
    success?: boolean;
    message?: string;
    valid: boolean;
    errors: Array<(string)>;
    step_count?: number;
    [key: string]: unknown | boolean | string | number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Vector search response.
 */
export type VectorSearchResponse = {
    success?: boolean;
    message?: string;
    data?: Array<VectorSearchResult>;
    total?: number;
    page?: number;
    page_size?: number;
    query: string;
    search_type: string;
    [key: string]: unknown | boolean | string | VectorSearchResult | number;
};

/**
 * Vector search result item.
 */
export type VectorSearchResult = {
    id: string;
    content: string;
    file_path: string;
    repository_id: string;
    chunk_type: string;
    identifier: string;
    start_line: number;
    end_line: number;
    language: string;
    score: number;
    [key: string]: unknown | string | number;
};

/**
 * TTS 声音列表响应
 */
export type VoiceListResponse = {
    success?: boolean;
    message?: string;
    voices: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | boolean | string;
};

/**
 * External webhook payload. Extra fields are allowed per source/event_type.
 */
export type WebhookPayload = {
    [key: string]: unknown;
};

export type WebhookRequest = {
    project_id?: (number | null);
    thread_id?: (string | null);
    source: string;
    event_type: string;
    payload: WebhookPayload;
};

export type WeChatConfigResponse = {
    success?: boolean;
    message?: string;
    enabled: boolean;
    app_id?: (string | null);
    [key: string]: unknown | boolean | string;
};

export type WeChatQRResponse = {
    success?: boolean;
    message?: string;
    key?: (string | null);
    expire_time: number;
    qrcode_url?: (string | null);
    ticket: string;
    [key: string]: unknown | boolean | string | number;
};

export type WeChatStatusResponse = {
    success?: boolean;
    message?: string;
    status: string;
    access_token?: (string | null);
    token_type?: (string | null);
    [key: string]: unknown | boolean | string;
};

export type WikiGenerationRequest = {
    project_id: number;
    topic?: string;
    force_regenerate?: boolean;
};

export type WikiGenerationResponse = {
    status: string;
    message: string;
    task_id: string;
    [key: string]: unknown | string;
};

export type WikiPageRead = {
    project_id: number;
    title: string;
    slug: string;
    content: string;
    parent_id?: (number | null);
    order?: number;
    id: number;
    created_at: string;
    updated_at: string;
};

/**
 * Response for ZIP import.
 */
export type ZipImportResponse = {
    success?: boolean;
    message?: string;
    [key: string]: unknown | boolean | string;
};

export type AccountLoginAccessTokenData = {
    formData: Body_account_login_access_token;
};

export type AccountLoginAccessTokenResponse = (Token);

export type AccountRequestMobileCodeData = {
    requestBody: MobileCodeRequest;
};

export type AccountRequestMobileCodeResponse = (MobileCodeResponse);

export type AccountLoginMobileData = {
    requestBody: MobileLoginRequest;
};

export type AccountLoginMobileResponse = (Token);

export type AccountGetWechatConfigResponse = (WeChatConfigResponse);

export type AccountGenerateQrCodeResponse = (WeChatQRResponse);

export type AccountCheckWechatLoginStatusData = {
    /**
     * The unique key from QR code generation
     */
    key: string;
};

export type AccountCheckWechatLoginStatusResponse = (WeChatStatusResponse);

export type AccountWechatDirectLoginData = {
    /**
     * The unique key from QR code generation
     */
    key: string;
};

export type AccountWechatDirectLoginResponse = (Token);

export type AccountWechatCallbackData = {
    nonce: string;
    signature: string;
    timestamp: string;
};

export type AccountWechatCallbackResponse = (unknown);

export type AccountLogoutResponse = (LogoutResponse);

export type AgentChatEndpointData = {
    guestId?: (string | null);
    requestBody: ChatRequest;
    token?: (string | null);
    xGuestId?: (string | null);
};

export type AgentChatEndpointResponse = (unknown);

export type AgentStopChatData = {
    requestBody: ChatRequest;
};

export type AgentStopChatResponse = (StopChatResponse);

export type AgentRetryChatData = {
    guestId?: (string | null);
    requestBody: ChatRequest;
    token?: (string | null);
    xGuestId?: (string | null);
};

export type AgentRetryChatResponse = (unknown);

export type AgentResumeChatData = {
    requestBody: ResumeRequest;
};

export type AgentResumeChatResponse = (unknown);

export type AgentCancelHitlRequestData = {
    requestBody: CancelHITLRequest;
};

export type AgentCancelHitlRequestResponse = (unknown);

export type AgentWebhookEndpointData = {
    requestBody: WebhookRequest;
};

export type AgentWebhookEndpointResponse = (unknown);

export type AudioListVoicesResponse = (VoiceListResponse);

export type AudioTextToSpeechData = {
    requestBody: TTSRequest;
};

export type AudioTextToSpeechResponse = (TTSResponse);

export type AudioTextToSpeechStreamData = {
    formData: Body_audio_text_to_speech_stream;
};

export type AudioTextToSpeechStreamResponse = (unknown);

export type AudioGetTtsFileData = {
    filename: string;
};

export type AudioGetTtsFileResponse = (unknown);

export type AudioListSttProvidersResponse = (STTProvidersResponse);

export type AudioTranscribeAudioData = {
    formData: Body_audio_transcribe_audio;
};

export type AudioTranscribeAudioResponse = (TranscriptionResponse);

export type AudioTranscribeStreamData = {
    formData: Body_audio_transcribe_stream;
};

export type AudioTranscribeStreamResponse = (unknown);

export type AuthGetCaptchaConfigResponse = (EvoCloudProxyResponse);

export type AuthGetCaptchaData = {
    captchaId: string;
};

export type AuthGetCaptchaResponse = (EvoCloudProxyResponse);

export type AuthGetRegisterConfigResponse = (EvoCloudProxyResponse);

export type AuthGetRegisterAgreementResponse = (EvoCloudProxyResponse);

export type AuthSendSmsData = {
    requestBody: AuthProxyMobileCodeRequest;
};

export type AuthSendSmsResponse = (EvoCloudProxyResponse);

export type AuthRegisterMobileData = {
    requestBody: RegisterMobileRequest;
};

export type AuthRegisterMobileResponse = (EvoCloudProxyResponse);

export type AuthRegisterUsernameData = {
    requestBody: RegisterUsernameRequest;
};

export type AuthRegisterUsernameResponse = (EvoCloudProxyResponse);

export type AuthLoginMobileData = {
    requestBody: LoginMobileRequest;
};

export type AuthLoginMobileResponse = (LoginResult);

export type AuthCheckMobileData = {
    requestBody: CheckMobileRequest;
};

export type AuthCheckMobileResponse = (EvoCloudProxyResponse);

export type AuthResetPasswordData = {
    requestBody: ResetPasswordMobileRequest;
};

export type AuthResetPasswordResponse = (EvoCloudProxyResponse);

export type ConversationsListConversationsData = {
    projectId?: (number | null);
};

export type ConversationsListConversationsResponse = (Array<ConversationListItem>);

export type ConversationsGetConversationMessagesData = {
    beforeId?: (number | null);
    limit?: number;
    threadId: string;
};

export type ConversationsGetConversationMessagesResponse = (MessageListResponse);

export type ConversationsSearchConversationsData = {
    projectId?: (number | null);
    q: string;
};

export type ConversationsSearchConversationsResponse = (Array<ConversationSearchResult>);

export type ConversationsRenameConversationData = {
    requestBody: RenameRequest;
    threadId: string;
};

export type ConversationsRenameConversationResponse = (unknown);

export type ConversationsDeleteConversationData = {
    threadId: string;
};

export type ConversationsDeleteConversationResponse = (unknown);

export type ConversationsGetThreadActivityData = {
    threadId: string;
};

export type ConversationsGetThreadActivityResponse = (unknown);

export type ConversationsRewindConversationData = {
    requestBody?: RewindRequest;
    threadId: string;
};

export type ConversationsRewindConversationResponse = (RewindResponse);

export type ConversationsGetThreadChangesetData = {
    threadId: string;
};

export type ConversationsGetThreadChangesetResponse = (Array<ChangesetNode>);

export type DevicesGetDevicesResponse = (unknown);

export type DevicesSendCommandData = {
    deviceId: number;
    requestBody: SendCommandRequest;
};

export type DevicesSendCommandResponse = (unknown);

export type DevicesGetRecentLogsData = {
    deviceId: number;
    limit?: number;
    projectId?: (number | null);
};

export type DevicesGetRecentLogsResponse = (unknown);

export type DevicesSearchLogsData = {
    deviceId: number;
    limit?: number;
    projectId?: (number | null);
    query: string;
};

export type DevicesSearchLogsResponse = (unknown);

export type DevicesBindClientData = {
    deviceId: number;
    requestBody: BindClientRequest;
};

export type DevicesBindClientResponse = (BindResponse);

export type DevicesBindCurrentDeviceData = {
    requestBody: BindClientRequest;
};

export type DevicesBindCurrentDeviceResponse = (BindResponse);

export type DevicesGetDebugStatusResponse = (DebugStatusResponse);

export type FilesListFilesData = {
    path?: (string | null);
    projectId: number;
};

export type FilesListFilesResponse = (Array<FileNode>);

export type FilesCreateFileData = {
    projectId: number;
    requestBody: CreateFileRequest;
};

export type FilesCreateFileResponse = (FileNode);

export type FilesGetFileContentData = {
    path: string;
    projectId: number;
};

export type FilesGetFileContentResponse = (FileContent);

export type FilesGetRawFileData = {
    path: string;
    projectId: number;
};

export type FilesGetRawFileResponse = (unknown);

export type FilesOpenFileData = {
    projectId: number;
    requestBody: OpenFileRequest;
};

export type FilesOpenFileResponse = (unknown);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
    projectId: number;
};

export type FilesUploadFileResponse = (unknown);

export type FilesSearchFilesData = {
    projectId: number;
    q: string;
};

export type FilesSearchFilesResponse = (Array<FileSearchResult>);

export type FilesSearchFilesByNameData = {
    projectId: number;
    q: string;
};

export type FilesSearchFilesByNameResponse = (Array<FileNameSearchResult>);

export type KnowledgeUploadDocumentData = {
    formData: Body_knowledge_upload_document;
};

export type KnowledgeUploadDocumentResponse = (DocumentResponse);

export type KnowledgeListDocumentsData = {
    /**
     * Filter by collection
     */
    collection?: (string | null);
    limit?: number;
    offset?: number;
    /**
     * File pattern
     */
    pattern?: string;
    /**
     * Filter by workspace project ID
     */
    sourceProjectId?: (number | null);
    /**
     * Filter by tags (comma-separated)
     */
    tags?: (string | null);
};

export type KnowledgeListDocumentsResponse = (DocumentListResponse);

export type KnowledgeReadDocumentData = {
    /**
     * Max lines to read
     */
    limit?: number;
    /**
     * Line offset (0-based)
     */
    offset?: number;
    path: string;
};

export type KnowledgeReadDocumentResponse = (DocumentContentResponse);

export type KnowledgeDeleteDocumentData = {
    path: string;
};

export type KnowledgeDeleteDocumentResponse = (DocumentResponse);

export type KnowledgeListCollectionsResponse = (CollectionResponse);

export type KnowledgeCreateCollectionData = {
    name: string;
};

export type KnowledgeCreateCollectionResponse = (DocumentResponse);

export type KnowledgeListTagsData = {
    /**
     * Filter by collection
     */
    collection?: (string | null);
    limit?: number;
};

export type KnowledgeListTagsResponse = (TagResponse);

export type KnowledgeSearchDocumentsData = {
    /**
     * Limit to collection
     */
    collection?: (string | null);
    contextLines?: number;
    /**
     * Search query
     */
    q: string;
};

export type KnowledgeSearchDocumentsResponse = (DocumentSearchResponse);

export type KnowledgeBulkUploadData = {
    formData: Body_knowledge_bulk_upload;
};

export type KnowledgeBulkUploadResponse = (BulkUploadResponse);

export type KnowledgeImportZipData = {
    formData: Body_knowledge_import_zip;
};

export type KnowledgeImportZipResponse = (ZipImportResponse);

export type KnowledgeValidateZipData = {
    formData: Body_knowledge_validate_zip;
};

export type KnowledgeValidateZipResponse = (unknown);

export type KnowledgeFtsSearchData = {
    /**
     * Filter by collection
     */
    collection?: (string | null);
    limit?: number;
    offset?: number;
    /**
     * FTS5 search query
     */
    q: string;
    /**
     * Filter by workspace project ID
     */
    sourceProjectId?: (number | null);
    /**
     * Filter by tags (comma-separated)
     */
    tags?: (string | null);
};

export type KnowledgeFtsSearchResponse = (FTSSearchResponse);

export type KnowledgeFtsSuggestData = {
    /**
     * Filter by collection
     */
    collection?: (string | null);
    limit?: number;
    /**
     * Search prefix
     */
    prefix: string;
};

export type KnowledgeFtsSuggestResponse = (FTSSuggestResponse);

export type KnowledgeAnalyzeDuplicatesData = {
    /**
     * Collection to analyze
     */
    collection?: (string | null);
};

export type KnowledgeAnalyzeDuplicatesResponse = (unknown);

export type KnowledgeMergeDocumentsData = {
    requestBody: Array<(string)>;
    strategy?: string;
    targetPath?: (string | null);
};

export type KnowledgeMergeDocumentsResponse = (unknown);

export type KnowledgeGetPopularDocumentsData = {
    /**
     * Filter by collection
     */
    collection?: (string | null);
    days?: number;
    limit?: number;
};

export type KnowledgeGetPopularDocumentsResponse = (unknown);

export type KnowledgeGetUsageAnalyticsData = {
    days?: number;
};

export type KnowledgeGetUsageAnalyticsResponse = (unknown);

export type KnowledgeGetRecommendationsData = {
    /**
     * Reference document path
     */
    path: string;
};

export type KnowledgeGetRecommendationsResponse = (unknown);

export type KnowledgeGetDocumentStatsData = {
    path: string;
};

export type KnowledgeGetDocumentStatsResponse = (unknown);

export type KnowledgeRunMaintenanceData = {
    /**
     * Target collection
     */
    collection?: (string | null);
    /**
     * Preview changes without applying
     */
    dryRun?: boolean;
    /**
     * Maintenance level: light, medium, deep
     */
    level?: string;
};

export type KnowledgeRunMaintenanceResponse = (unknown);

export type KnowledgeAnalyzeMaintenanceDuplicatesData = {
    /**
     * Target collection
     */
    collection?: (string | null);
};

export type KnowledgeAnalyzeMaintenanceDuplicatesResponse = (unknown);

export type KnowledgeMergeMaintenanceDocumentsData = {
    requestBody: Array<(string)>;
    /**
     * Merge strategy: concatenate, deduplicate
     */
    strategy?: string;
    /**
     * Target path for merged document
     */
    targetPath?: (string | null);
};

export type KnowledgeMergeMaintenanceDocumentsResponse = (unknown);

export type KnowledgeCheckQualityData = {
    /**
     * Target collection
     */
    collection?: (string | null);
    /**
     * Maximum documents to check
     */
    limit?: number;
};

export type KnowledgeCheckQualityResponse = (unknown);

export type KnowledgeListMaintenanceReportsData = {
    /**
     * Number of recent reports
     */
    limit?: number;
};

export type KnowledgeListMaintenanceReportsResponse = (unknown);

export type LearningGetActionRegistryResponse = (Array<ActionDef>);

export type LearningListPendingRequestsData = {
    threadId?: (string | null);
};

export type LearningListPendingRequestsResponse = (Array<HumanInputRequestOut>);

export type LearningGetRequestData = {
    requestId: string;
};

export type LearningGetRequestResponse = (HumanInputRequestOut);

export type LearningRespondToRequestData = {
    requestBody: RespondRequest;
    requestId: string;
};

export type LearningRespondToRequestResponse = (BaseAPIResponse);

export type LearningCancelPendingRequestData = {
    requestId: string;
};

export type LearningCancelPendingRequestResponse = (BaseAPIResponse);

export type LearningCleanupRequestsData = {
    maxAgeHours?: number;
};

export type LearningCleanupRequestsResponse = (BaseAPIResponse);

export type LearningStartRecordingData = {
    requestBody: StartRecordingRequest;
};

export type LearningStartRecordingResponse = (StartRecordingResponse);

export type LearningStopRecordingData = {
    sessionId: string;
};

export type LearningStopRecordingResponse = (StopRecordingResponse);

export type LearningListRecordingSessionsData = {
    threadId?: (string | null);
};

export type LearningListRecordingSessionsResponse = (RecordingSessionsResponse);

export type LearningSynthesizeSkillData = {
    requestBody: SynthesizeRequest;
};

export type LearningSynthesizeSkillResponse = (SynthesizeSkillResponse);

export type LearningImportSkillsData = {
    requestBody: ImportSkillsRequest;
};

export type LearningImportSkillsResponse = (ImportSkillsResponse);

export type LearningListSkillsData = {
    activeOnly?: boolean;
    page?: number;
    pageSize?: number;
};

export type LearningListSkillsResponse = (PaginatedSkillsResponse);

export type LearningGetSkillData = {
    skillId: number;
};

export type LearningGetSkillResponse = (SkillDetailResponse);

export type LearningDeleteSkillData = {
    skillId: number;
};

export type LearningDeleteSkillResponse = (BaseAPIResponse);

export type LearningUpdateSkillData = {
    requestBody: UpdateSkillRequest;
    skillId: number;
};

export type LearningUpdateSkillResponse = (UpdateSkillResponse);

export type LearningExecuteSkillData = {
    requestBody: ExecuteSkillRequest;
    skillId: number;
};

export type LearningExecuteSkillResponse = (ExecuteSkillResponse);

export type LearningListMirrorDevicesResponse = (MirrorDevicesResponse);

export type LearningStartMirrorSessionData = {
    requestBody: StartMirrorRequest;
};

export type LearningStartMirrorSessionResponse = (MirrorSessionResponse);

export type LearningStartMirrorRecordingData = {
    requestBody: StartMirrorRecordingRequest;
};

export type LearningStartMirrorRecordingResponse = (MirrorRecordingResponse);

export type LearningStopMirrorSessionData = {
    requestBody: StopMirrorRequest;
};

export type LearningStopMirrorSessionResponse = (StopMirrorResponse);

export type LearningGetDeviceResolutionData = {
    deviceId: string;
};

export type LearningGetDeviceResolutionResponse = (DeviceResolutionResponse);

export type LearningPersistMirrorEventsData = {
    requestBody: PersistMirrorEventsRequest;
};

export type LearningPersistMirrorEventsResponse = (MirrorPersistResponse);

export type LearningPersistGlobalEventsData = {
    requestBody: GlobalEventsRequest;
};

export type LearningPersistGlobalEventsResponse = (MirrorPersistResponse);

export type LearningPersistDomEventsData = {
    requestBody: DomEventsRequest;
};

export type LearningPersistDomEventsResponse = (MirrorPersistResponse);

export type LearningUploadScreenshotData = {
    formData: Body_learning_upload_screenshot;
};

export type LearningUploadScreenshotResponse = (UploadScreenshotResponse);

export type LearningValidateSkillData = {
    skillId: number;
};

export type LearningValidateSkillResponse = (ValidateSkillResponse);

export type LearningSynthesizeFromRecordingData = {
    requestBody: SynthesizeFromRecordingRequest;
};

export type LearningSynthesizeFromRecordingResponse = (SynthesizeFromRecordingResponse);

export type LearningPreviewRecordingDataData = {
    sessionId: string;
    videoPath: string;
};

export type LearningPreviewRecordingDataResponse = (PreviewRecordingDataResponse);

export type LearningListAnnotationsData = {
    sessionId: string;
};

export type LearningListAnnotationsResponse = (Array<AnnotationResponse>);

export type LearningCreateAndroidExtractPointData = {
    requestBody: AndroidExtractPointRequest;
};

export type LearningCreateAndroidExtractPointResponse = (AndroidExtractPointResponse);

export type LearningListAndroidExtractPointsData = {
    sessionId: string;
};

export type LearningListAndroidExtractPointsResponse = (Array<AndroidExtractPointResponse>);

export type LearningStartSmartSynthesisData = {
    requestBody: SmartSynthesisRequest;
    sessionId: string;
};

export type LearningStartSmartSynthesisResponse = (SmartSynthesisResponse);

export type LearningGetSynthesisJobData = {
    jobId: number;
};

export type LearningGetSynthesisJobResponse = (SynthesisJobResponse);

export type LearningListSessionSynthesisJobsData = {
    sessionId: string;
};

export type LearningListSessionSynthesisJobsResponse = (Array<SynthesisJobResponse>);

export type LearningCleanupRecordingSessionData = {
    sessionId: string;
    videoPath?: (string | null);
};

export type LearningCleanupRecordingSessionResponse = (CleanupRecordingResponse);

export type LearningConfirmLearnedSkillData = {
    skillId: number;
};

export type LearningConfirmLearnedSkillResponse = (BaseAPIResponse);

export type LearningCreateSkillFromYamlData = {
    requestBody: CreateSkillFromYamlRequest;
};

export type LearningCreateSkillFromYamlResponse = (CreateSkillFromYamlResponse);

export type LearningValidateSkillYamlData = {
    requestBody: ValidateYamlRequest;
};

export type LearningValidateSkillYamlResponse = (ValidateYamlResponse);

export type LearningGetSkillYamlData = {
    skillId: number;
};

export type LearningGetSkillYamlResponse = (unknown);

export type LearningUpdateSkillYamlData = {
    requestBody: string;
    skillId: number;
};

export type LearningUpdateSkillYamlResponse = (UpdateSkillFromYamlResponse);

export type McpListMcpServersResponse = (Array<unknown>);

export type McpAddMcpServerData = {
    requestBody: McpServerCreate;
};

export type McpAddMcpServerResponse = (unknown);

export type McpDeleteMcpServerData = {
    name: string;
};

export type McpDeleteMcpServerResponse = (McpOperationResponse);

export type McpConnectMcpServerData = {
    name: string;
};

export type McpConnectMcpServerResponse = (McpConnectResponse);

export type MemberReadUserMeResponse = (UserPublic);

export type MemberUpdateUserMeData = {
    requestBody: UpdateUserRequest;
};

export type MemberUpdateUserMeResponse = (UserPublic);

export type MemberChangePasswordData = {
    requestBody: ChangePasswordRequest;
};

export type MemberChangePasswordResponse = (MessageResponse);

export type MemberGetCancellationInfoResponse = (EvoCloudProxyResponse);

export type MemberApplyCancellationResponse = (EvoCloudProxyResponse);

export type MemberCancelCancellationResponse = (EvoCloudProxyResponse);

export type MemberCheckBenefitsBatchData = {
    requestBody: BatchCheckRequest;
};

export type MemberCheckBenefitsBatchResponse = (BatchCheckResponse);

export type MemberGetMemberBenefitsApiData = {
    forceRefresh?: boolean;
};

export type MemberGetMemberBenefitsApiResponse = (MemberBenefitsResponse);

export type MemberInvalidateMemberBenefitsCacheResponse = (CacheInvalidateResponse);

export type MemoryListConceptsData = {
    projectId: number;
};

export type MemoryListConceptsResponse = (Array<ConceptResponse>);

export type MemoryAddConceptData = {
    projectId: number;
    requestBody: ConceptCreate;
};

export type MemoryAddConceptResponse = (ConceptOperationResponse);

export type MemoryListConceptsWithCountsData = {
    limit?: number;
    projectId: number;
};

export type MemoryListConceptsWithCountsResponse = (Array<ConceptResponse>);

export type MemoryGetConceptData = {
    conceptName: string;
    projectId: number;
};

export type MemoryGetConceptResponse = (ConceptResponse);

export type MemoryDeleteConceptData = {
    conceptName: string;
    projectId: number;
};

export type MemoryDeleteConceptResponse = (ConceptOperationResponse);

export type MemoryUpdateConceptData = {
    conceptName: string;
    projectId: number;
    requestBody: ConceptUpdate;
};

export type MemoryUpdateConceptResponse = (ConceptOperationResponse);

export type MemorySearchMemoryData = {
    projectId?: (number | null);
    q: string;
    /**
     * Use vector similarity search if available
     */
    useVector?: boolean;
};

export type MemorySearchMemoryResponse = (Array<ConceptResponse>);

export type MemorySearchMemoryVectorData = {
    projectId?: (number | null);
    q: string;
    repositoryId?: (string | null);
    topK?: number;
};

export type MemorySearchMemoryVectorResponse = (VectorSearchResponse);

export type MemorySearchMemoryHybridData = {
    projectId?: (number | null);
    q: string;
    topK?: number;
    vectorWeight?: number;
};

export type MemorySearchMemoryHybridResponse = (HybridSearchResponse);

export type MemoryGetEpisodesByConceptData = {
    concept: string;
    limit?: number;
    projectId: number;
};

export type MemoryGetEpisodesByConceptResponse = (Array<EpisodeResponse>);

export type MemoryDeduplicateCheckpointsData = {
    dryRun?: boolean;
};

export type MemoryDeduplicateCheckpointsResponse = (unknown);

export type PlanningGetPlanData = {
    threadId: string;
};

export type PlanningGetPlanResponse = (PlanResponse);

export type ProjectModulesGetBudgetListData = {
    page?: number;
    pageSize?: number;
    projectId: number;
};

export type ProjectModulesGetBudgetListResponse = (unknown);

export type ProjectModulesGetBudgetOverviewData = {
    projectId: number;
};

export type ProjectModulesGetBudgetOverviewResponse = (unknown);

export type ProjectModulesGetTimesheetListData = {
    authorization?: (string | null);
    page?: number;
    pageSize?: number;
    projectId: number;
};

export type ProjectModulesGetTimesheetListResponse = (unknown);

export type ProjectModulesQuickAddTimesheetData = {
    authorization?: (string | null);
    requestBody: TimesheetQuickAddRequest;
};

export type ProjectModulesQuickAddTimesheetResponse = (unknown);

export type ProjectModulesGetProjectStatisticsData = {
    authorization?: (string | null);
    projectId?: (number | null);
};

export type ProjectModulesGetProjectStatisticsResponse = (unknown);

export type ProjectProfilesDiscoverProfileData = {
    projectId: number;
    requestBody: DiscoverRequest;
};

export type ProjectProfilesDiscoverProfileResponse = (DiscoverResponse);

export type ProjectProfilesGetProfileData = {
    projectId: number;
};

export type ProjectProfilesGetProfileResponse = (ProfileContentResponse);

export type ProjectRequirementsUploadRequirementDocumentData = {
    formData: Body_project_requirements_upload_requirement_document;
    projectId: number;
};

export type ProjectRequirementsUploadRequirementDocumentResponse = (RequirementUploadResponse);

export type ProjectRequirementsListProjectRequirementsData = {
    projectId: number;
};

export type ProjectRequirementsListProjectRequirementsResponse = (RequirementListResponse);

export type ProjectRequirementsGetRequirementDetailData = {
    docId: string;
    projectId: number;
};

export type ProjectRequirementsGetRequirementDetailResponse = (RequirementDetailResponse);

export type ProjectRequirementsDeleteRequirementDocumentData = {
    docId: string;
    projectId: number;
};

export type ProjectRequirementsDeleteRequirementDocumentResponse = (RequirementDeleteResponse);

export type ProjectRequirementsGetAnalysisTasksData = {
    analysisId: string;
    docId: string;
    projectId: number;
};

export type ProjectRequirementsGetAnalysisTasksResponse = (RequirementTasksResponse);

export type ProjectRequirementsGetAnalysisSyncProgressData = {
    analysisId: string;
    docId: string;
    projectId: number;
};

export type ProjectRequirementsGetAnalysisSyncProgressResponse = (RequirementSyncProgressResponse);

export type ProjectsGetProjectsData = {
    filterType?: (string | null);
    page?: number;
    pageSize?: number;
};

export type ProjectsGetProjectsResponse = (unknown);

export type ProjectsCreateProjectData = {
    requestBody: CreateProjectRequest;
};

export type ProjectsCreateProjectResponse = (unknown);

export type ProjectsGetCurrentProjectResponse = (unknown);

export type ProjectsGetProjectStatusData = {
    projectId: number;
};

export type ProjectsGetProjectStatusResponse = (ProjectStatusResponse);

export type ProjectsDeleteProjectData = {
    projectId: number;
};

export type ProjectsDeleteProjectResponse = (ProjectDeleteResponse);

export type ProjectsRunIndexingEndpointData = {
    requestBody: IndexingRequest;
};

export type ProjectsRunIndexingEndpointResponse = (IndexingRunResponse);

export type ProjectsGetDetectedProjectsResponse = (DetectedProjectsResponse);

export type ProjectsImportDetectedProjectData = {
    repoId: number;
};

export type ProjectsImportDetectedProjectResponse = (ImportProjectResponse);

export type ProjectsIgnoreDetectedProjectData = {
    repoId: number;
};

export type ProjectsIgnoreDetectedProjectResponse = (IgnoreProjectResponse);

export type ProjectsGetIgnoredProjectsResponse = (DetectedProjectsResponse);

export type ProjectsUnignoreProjectData = {
    repoId: number;
};

export type ProjectsUnignoreProjectResponse = (UnignoreProjectResponse);

export type ProjectsBatchImportProjectsData = {
    requestBody: BatchImportRequest;
};

export type ProjectsBatchImportProjectsResponse = (BatchImportResponse);

export type ProjectsBatchIgnoreProjectsData = {
    requestBody: BatchImportRequest;
};

export type ProjectsBatchIgnoreProjectsResponse = (BatchImportResponse);

export type ResourcesListResourcesData = {
    projectId: number;
};

export type ResourcesListResourcesResponse = (Array<ResourceResponse>);

export type ResourcesCreateResourceData = {
    projectId: number;
    requestBody: ResourceCreate;
};

export type ResourcesCreateResourceResponse = (ResourceResponse);

export type ResourcesDeleteResourceData = {
    projectId: number;
    resourceId: number;
};

export type ResourcesDeleteResourceResponse = (OperationResponse);

export type StreamStreamChatData = {
    guestId?: (string | null);
    threadId: string;
    token?: (string | null);
    xGuestId?: (string | null);
};

export type StreamStreamChatResponse = (unknown);

export type SubscriptionGetSubscriptionPlansResponse = (unknown);

export type SubscriptionCalculateUpgradePriceData = {
    targetLevelId: number;
};

export type SubscriptionCalculateUpgradePriceResponse = (unknown);

export type SubscriptionGetSubscriptionStatusResponse = (unknown);

export type SubscriptionGetSubscriptionDetailResponse = (unknown);

export type SubscriptionCreateSubscriptionOrderData = {
    requestBody: CreateOrderRequest;
};

export type SubscriptionCreateSubscriptionOrderResponse = (unknown);

export type SubscriptionCancelSubscriptionData = {
    cancelType?: string;
    reason?: string;
};

export type SubscriptionCancelSubscriptionResponse = (unknown);

export type SubscriptionCheckSubscriptionOrderStatusData = {
    orderId: string;
};

export type SubscriptionCheckSubscriptionOrderStatusResponse = (unknown);

export type SubscriptionGetAiQuotaResponse = (unknown);

export type SubscriptionGetAllAiQuotasResponse = (unknown);

export type SubscriptionGetAiQuotaHistoryData = {
    page?: number;
    pageSize?: number;
};

export type SubscriptionGetAiQuotaHistoryResponse = (unknown);

export type SubscriptionHandleBenefitsUpdateWebhookData = {
    requestBody: BenefitsUpdateWebhook;
};

export type SubscriptionHandleBenefitsUpdateWebhookResponse = (unknown);

export type SubtasksCreateTaskWithSubtasksData = {
    projectId: number;
    requestBody: TaskWithSubtasksCreate;
};

export type SubtasksCreateTaskWithSubtasksResponse = (TaskCreateResponse);

export type SubtasksGetTaskTreeData = {
    maxDepth?: number;
    projectId: number;
    taskId: string;
};

export type SubtasksGetTaskTreeResponse = (TaskTreeWrapperResponse);

export type SubtasksUpdateTaskProgressData = {
    projectId: number;
    requestBody: TaskProgressUpdate;
    taskId: string;
};

export type SubtasksUpdateTaskProgressResponse = (TaskProgressUpdateResponse);

export type SubtasksGetNextExecutableTaskData = {
    projectId: number;
};

export type SubtasksGetNextExecutableTaskResponse = (NextTaskResponse);

export type SubtasksFlattenTaskTreeData = {
    projectId: number;
    taskId: string;
};

export type SubtasksFlattenTaskTreeResponse = (TaskFlatResponse);

export type SubtasksListRootTasksData = {
    limit?: number;
    projectId: number;
    status?: (string | null);
};

export type SubtasksListRootTasksResponse = (TaskListResponse);

export type SymbolsSearchSymbolsData = {
    limit?: number;
    projectId: number;
    /**
     * Search query for symbol name
     */
    q: string;
    /**
     * Filter by entity type (class, function)
     */
    type?: (string | null);
};

export type SymbolsSearchSymbolsResponse = (Array<SymbolResponse>);

export type SymbolsGenerateSymbolWikiData = {
    projectId: number;
    symbolId: number;
};

export type SymbolsGenerateSymbolWikiResponse = (SymbolWikiResponse);

export type SystemGetSystemStatusResponse = (SystemStatusResponse);

export type SystemGetSystemConfigResponse = (Array<SystemConfig>);

export type SystemUpdateSystemConfigData = {
    requestBody: SystemConfig;
};

export type SystemUpdateSystemConfigResponse = (SystemConfig);

export type SystemHealthCheckResponse = (HealthCheckResponse);

export type SystemTestEmbeddingConnectionData = {
    requestBody: EmbeddingConfigRequest;
};

export type SystemTestEmbeddingConnectionResponse = (EmbeddingTestResponse);

export type SystemApplyEmbeddingConfigData = {
    requestBody: EmbeddingConfigRequest;
};

export type SystemApplyEmbeddingConfigResponse = (EmbeddingApplyResponse);

export type SystemTestLlmConnectionData = {
    requestBody: LLMConfigRequest;
};

export type SystemTestLlmConnectionResponse = (LLMTestResponse);

export type SystemApplyLlmConfigData = {
    requestBody: LLMConfigRequest;
};

export type SystemApplyLlmConfigResponse = (LLMApplyResponse);

export type SystemResetKnowledgeBaseResponse = (ResetKnowledgeResponse);

export type SystemGetCloudStatusResponse = (CloudStatusResponse);

export type SystemGetLlmModelsData = {
    configType?: string;
};

export type SystemGetLlmModelsResponse = (ModelsListResponse);

export type SystemGetEmbeddingModelsResponse = (ModelsListResponse);

export type SystemGetProjectDiscoveryConfigResponse = (unknown);

export type SystemSetProjectDiscoveryConfigData = {
    requestBody: ProjectDiscoveryConfigRequest;
};

export type SystemSetProjectDiscoveryConfigResponse = (ProjectDiscoveryConfigUpdateResponse);

export type TasksGetProjectTasksData = {
    page?: number;
    pageSize?: number;
    projectId: number;
    status?: (number | null);
};

export type TasksGetProjectTasksResponse = (unknown);

export type TasksCreateTaskData = {
    authorization?: (string | null);
    requestBody: TaskCreateRequest;
};

export type TasksCreateTaskResponse = (unknown);

export type TasksGetTaskDetailData = {
    taskId: number;
};

export type TasksGetTaskDetailResponse = (unknown);

export type TasksUpdateTaskData = {
    authorization?: (string | null);
    requestBody: TaskUpdateRequest;
    taskId: number;
};

export type TasksUpdateTaskResponse = (unknown);

export type TasksDeleteTaskData = {
    authorization?: (string | null);
    taskId: number;
};

export type TasksDeleteTaskResponse = (unknown);

export type TasksUpdateTaskStatusEndpointData = {
    authorization?: (string | null);
    requestBody: TaskStatusUpdate;
    taskId: number;
};

export type TasksUpdateTaskStatusEndpointResponse = (unknown);

export type TasksExecuteTaskData = {
    authorization?: (string | null);
    taskId: number;
};

export type TasksExecuteTaskResponse = (unknown);

export type TodosCreateTodoData = {
    requestBody: TodoCreate;
};

export type TodosCreateTodoResponse = (TodoResponse);

export type TodosListTodosData = {
    limit?: number;
    offset?: number;
    projectId?: (number | null);
    status?: (TodoStatus | null);
};

export type TodosListTodosResponse = (Array<TodoResponse>);

export type TodosGetTodoData = {
    todoId: string;
};

export type TodosGetTodoResponse = (TodoResponse);

export type TodosUpdateTodoData = {
    requestBody: TodoUpdate;
    todoId: string;
};

export type TodosUpdateTodoResponse = (TodoResponse);

export type TodosDeleteTodoData = {
    todoId: string;
};

export type TodosDeleteTodoResponse = (unknown);

export type ToolsListRuntimeToolsResponse = (Array<ToolInfo>);

export type ToolsListAllToolsResponse = (Array<ToolInfo>);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetEvoloopStatusResponse = (EvoloopStatusResponse);

export type UtilsGetAiConfigResponse = (unknown);

export type WikiGetWikiPagesData = {
    projectId: number;
};

export type WikiGetWikiPagesResponse = (Array<WikiPageRead>);

export type WikiGenerateWikiData = {
    requestBody: WikiGenerationRequest;
};

export type WikiGenerateWikiResponse = (WikiGenerationResponse);