"""add_is_pinned_to_conversation

Revision ID: 14faa7da50a8
Revises: 84439cba68a9
Create Date: 2026-05-19 16:15:17.344664

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '14faa7da50a8'
down_revision = '84439cba68a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), server_default='0', nullable=False))
    op.create_index(op.f('ix_conversations_is_pinned'), 'conversations', ['is_pinned'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_is_pinned'), table_name='conversations')
    op.drop_column('conversations', 'is_pinned')
    # ### end Alembic commands ###
