"""add allow_self_healing to learned_skills

Revision ID: 7e8cbf993ca1
Revises: a8f9c2d4e5b6
Create Date: 2026-03-09 14:19:29.039829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7e8cbf993ca1'
down_revision = 'a8f9c2d4e5b6'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as nullable first
    op.add_column('learned_skills', sa.Column('allow_self_healing', sa.Boolean(), nullable=True))
    
    # 2. Update existing rows to True (default)
    op.execute("UPDATE learned_skills SET allow_self_healing = TRUE")
    
    # 3. Set column to NOT NULL
    op.alter_column('learned_skills', 'allow_self_healing', nullable=False)
    
    op.drop_index('ix_synthesis_jobs_status', table_name='synthesis_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_synthesis_jobs_status', 'synthesis_jobs', ['status'], unique=False)
    op.drop_column('learned_skills', 'allow_self_healing')
    # ### end Alembic commands ###
