"""Add source field to messages

Revision ID: 800f1b4d563c
Revises: f5c8a2d1e9b4
Create Date: 2026-06-18 18:59:48.016765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800f1b4d563c'
down_revision = 'f5c8a2d1e9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_messages_source'), 'messages', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_source'), table_name='messages')
    op.drop_column('messages', 'source')
    # ### end Alembic commands ###
