"""Remove legacy skill execution json columns

Revision ID: a251388bcfdd
Revises: 036d351ab82f
Create Date: 2026-02-20 23:51:07.946228

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a251388bcfdd'
down_revision = '036d351ab82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learned_skills', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
