"""add_sync_status_to_conversation_and_message

Revision ID: a4899aa1a087
Revises: 878f1f175b93
Create Date: 2026-04-20 02:23:53.714456

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a4899aa1a087'
down_revision = '878f1f175b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('conversations', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_sync_status'), 'conversations', ['sync_status'], unique=False)
    op.add_column('messages', sa.Column('sync_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('messages', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_messages_sync_status'), 'messages', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sync_status'), table_name='messages')
    op.drop_column('messages', 'last_synced_at')
    op.drop_column('messages', 'sync_status')
    op.drop_index(op.f('ix_conversations_sync_status'), table_name='conversations')
    op.drop_column('conversations', 'last_synced_at')
    op.drop_column('conversations', 'sync_status')
    # ### end Alembic commands ###
