"""add remember fields to messages

Revision ID: b184728f63c0
Revises: 1569b5fdd982
Create Date: 2026-07-03 17:54:24.228036

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b184728f63c0'
down_revision = '1569b5fdd982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_remembered', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('messages', sa.Column('remembered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('memory_concept_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_messages_is_remembered'), 'messages', ['is_remembered'], unique=False)
    op.create_index(op.f('ix_messages_memory_concept_id'), 'messages', ['memory_concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_memory_concept_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_remembered'), table_name='messages')
    op.drop_column('messages', 'memory_concept_id')
    op.drop_column('messages', 'remembered_at')
    op.drop_column('messages', 'is_remembered')
    # ### end Alembic commands ###
