"""curious_scout_skill_level_skill_source

Revision ID: bb42b0e55725
Revises: i3b8c42e56f2
Create Date: 2026-02-19 23:38:24.369904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb42b0e55725'
down_revision = 'i3b8c42e56f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_env_knowledge_category'), table_name='env_knowledge')
    op.drop_index(op.f('ix_env_knowledge_key'), table_name='env_knowledge')
    op.drop_table('env_knowledge')
    op.add_column('learned_skills', sa.Column('skill_level', sa.String(length=10), nullable=True))
    op.add_column('learned_skills', sa.Column('skill_source', sa.String(length=20), nullable=True))
    op.alter_column('learned_skills', 'validation_report',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learned_skills', 'validation_report',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('learned_skills', 'skill_source')
    op.drop_column('learned_skills', 'skill_level')
    op.create_table('env_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('env_knowledge_pkey')),
    sa.UniqueConstraint('category', 'key', name=op.f('uix_category_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_env_knowledge_key'), 'env_knowledge', ['key'], unique=False)
    op.create_index(op.f('ix_env_knowledge_category'), 'env_knowledge', ['category'], unique=False)
    # ### end Alembic commands ###
