"""add_project_requirement_models

Revision ID: c3397314c4e7
Revises: bb17a6119509
Create Date: 2026-03-01 16:53:54.791249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c3397314c4e7'
down_revision = 'bb17a6119509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create project_requirement_documents table
    op.create_table(
        'project_requirement_documents',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('repo_id', sa.Integer(), nullable=True),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.Text(), nullable=False),
        sa.Column('file_type', sa.String(length=50), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False, default=0),
        sa.Column('raw_content', sa.Text(), nullable=True),
        sa.Column('content_hash', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, default='pending'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_requirement_documents_project_id'), 'project_requirement_documents', ['project_id'], unique=False)

    # Create project_requirement_analyses table
    op.create_table(
        'project_requirement_analyses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('document_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False, default=1),
        sa.Column('analysis_data', postgresql.JSON(astext_type=sa.Text()), nullable=False, default={}),
        sa.Column('user_edited', sa.Boolean(), nullable=False, default=False),
        sa.Column('edited_by', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, default='draft'),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['project_requirement_documents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_requirement_analyses_document_id'), 'project_requirement_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_requirement_analyses_project_id'), 'project_requirement_analyses', ['project_id'], unique=False)

    # Create project_requirement_tasks table
    op.create_table(
        'project_requirement_tasks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('analysis_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('evocloud_task_id', sa.Integer(), nullable=True),
        sa.Column('task_data', postgresql.JSON(astext_type=sa.Text()), nullable=False, default={}),
        sa.Column('sync_status', sa.String(length=50), nullable=False, default='pending'),
        sa.Column('sync_error', sa.Text(), nullable=True),
        sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['analysis_id'], ['project_requirement_analyses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_requirement_tasks_analysis_id'), 'project_requirement_tasks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_project_requirement_tasks_project_id'), 'project_requirement_tasks', ['project_id'], unique=False)

    # Other schema changes
    op.drop_column('learned_skills', 'embedding')
    op.drop_index(op.f('ix_repositories_detected_at'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_sync_status'), table_name='repositories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_requirement_tasks_project_id'), table_name='project_requirement_tasks')
    op.drop_index(op.f('ix_project_requirement_tasks_analysis_id'), table_name='project_requirement_tasks')
    op.drop_table('project_requirement_tasks')

    op.drop_index(op.f('ix_project_requirement_analyses_project_id'), table_name='project_requirement_analyses')
    op.drop_index(op.f('ix_project_requirement_analyses_document_id'), table_name='project_requirement_analyses')
    op.drop_table('project_requirement_analyses')

    op.drop_index(op.f('ix_project_requirement_documents_project_id'), table_name='project_requirement_documents')
    op.drop_table('project_requirement_documents')

    op.create_index(op.f('ix_repositories_sync_status'), 'repositories', ['sync_status'], unique=False)
    op.create_index(op.f('ix_repositories_detected_at'), 'repositories', ['detected_at'], unique=False)
    # Note: pgvector column restore is database-specific and may need manual handling
    # ### end Alembic commands ###
