"""add sedimentation fields and trace message_id

Revision ID: da11f0635fe3
Revises: d1e9b2a3c4f5
Create Date: 2026-07-17 08:23:17.362998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da11f0635fe3'
down_revision = 'd1e9b2a3c4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'sedimentation_eligible',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )

    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'message_id',
                sa.String(length=36),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f('ix_trace_events_message_id'),
            ['message_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_events_message_id'))
        batch_op.drop_column('message_id')

    with op.batch_alter_table('agent_activities', schema=None) as batch_op:
        batch_op.drop_column('sedimentation_eligible')
        batch_op.drop_column('summary')
    # ### end Alembic commands ###
