#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"
#include "generated/evo_loop_mobile/RNOH/generated/BaseEvoLoopMobilePackage.h"

// Manual C++ package headers for skipped libraries
#include "ReanimatedPackage.h"
#include "PermissionsPackage.h"
#include "WebViewPackage.h"
#include "AsyncStoragePackage.h"
#include "RNAudioRecorderPlayerPackage.h"
#include "SafeAreaViewPackage.h"
#include "RNCVideoPackage.h"
#include "FlashListPackage.h"
#include "ClipboardPackage.h"
#include "VisionCameraPackage.h"
#include "GestureHandlerPackage.h"
#include "ImageCropPickerPackage.h"

#include <dlfcn.h>
#include <string>
#include <hilog/log.h>

using namespace rnoh;

static void preload_dummy_function() {}

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  // Preload dependent libraries for sherpa_onnx
  Dl_info info;
  if (dladdr((void*)&preload_dummy_function, &info) != 0 && info.dli_fname != nullptr) {
    std::string app_so_path = info.dli_fname;
    size_t last_slash = app_so_path.find_last_of('/');
    if (last_slash != std::string::npos) {
      std::string lib_dir = app_so_path.substr(0, last_slash + 1);
      std::string cpp_shared_path = lib_dir + "libc++_shared.so";
      std::string onnx_path = lib_dir + "libonnxruntime.so";
      std::string sherpa_c_path = lib_dir + "libsherpa-onnx-c-api.so";
      
      OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Preloading: %{public}s", cpp_shared_path.c_str());
      void* cpp_shared_handle = dlopen(cpp_shared_path.c_str(), RTLD_NOW | RTLD_GLOBAL);
      if (!cpp_shared_handle) {
        OH_LOG_Print(LOG_APP, LOG_ERROR, 0xFF00, "RNOH_ASR", "Failed to preload libc++_shared.so: %{public}s", dlerror());
      } else {
        OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Successfully preloaded libc++_shared.so");
      }
      
      OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Preloading: %{public}s", onnx_path.c_str());
      void* onnx_handle = dlopen(onnx_path.c_str(), RTLD_NOW | RTLD_GLOBAL);
      if (!onnx_handle) {
        OH_LOG_Print(LOG_APP, LOG_ERROR, 0xFF00, "RNOH_ASR", "Failed to preload libonnxruntime.so: %{public}s", dlerror());
      } else {
        OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Successfully preloaded libonnxruntime.so");
      }
      
      OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Preloading: %{public}s", sherpa_c_path.c_str());
      void* sherpa_c_handle = dlopen(sherpa_c_path.c_str(), RTLD_NOW | RTLD_GLOBAL);
      if (!sherpa_c_handle) {
        OH_LOG_Print(LOG_APP, LOG_ERROR, 0xFF00, "RNOH_ASR", "Failed to preload libsherpa-onnx-c-api.so: %{public}s", dlerror());
      } else {
        OH_LOG_Print(LOG_APP, LOG_INFO, 0xFF00, "RNOH_ASR", "Successfully preloaded libsherpa-onnx-c-api.so");
      }
    }
  }

  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  packages.push_back(std::make_shared<BaseEvoLoopMobilePackage>(ctx));
  
  // Register manual C++ packages
  packages.push_back(std::make_shared<ReanimatedPackage>(ctx));
  packages.push_back(std::make_shared<PermissionsPackage>(ctx));
  packages.push_back(std::make_shared<WebViewPackage>(ctx));
  packages.push_back(std::make_shared<AsyncStoragePackage>(ctx));
  packages.push_back(std::make_shared<RNAudioRecorderPlayerPackage>(ctx));
  packages.push_back(std::make_shared<SafeAreaViewPackage>(ctx));
  packages.push_back(std::make_shared<RNCVideoPackage>(ctx));
  packages.push_back(std::make_shared<FlashListPackage>(ctx));
  packages.push_back(std::make_shared<ClipboardPackage>(ctx));
  packages.push_back(std::make_shared<VisionCameraPackage>(ctx));
  packages.push_back(std::make_shared<GestureHandlerPackage>(ctx));
  packages.push_back(std::make_shared<ImageCropPickerPackage>(ctx));
  
  return packages;
}