#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"
#include "generated/evo_loop_mobile/RNOH/generated/BaseEvoLoopMobilePackage.h"

// Manual C++ package headers for skipped libraries
#include "ReanimatedPackage.h"
#include "PermissionsPackage.h"
#include "WebViewPackage.h"
#include "AsyncStoragePackage.h"
#include "RNAudioRecorderPlayerPackage.h"
#include "SafeAreaViewPackage.h"
#include "RNCVideoPackage.h"
#include "FlashListPackage.h"
#include "ClipboardPackage.h"
#include "VisionCameraPackage.h"
#include "GestureHandlerPackage.h"
#include "ImageCropPickerPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  packages.push_back(std::make_shared<BaseEvoLoopMobilePackage>(ctx));
  
  // Register manual C++ packages
  packages.push_back(std::make_shared<ReanimatedPackage>(ctx));
  packages.push_back(std::make_shared<PermissionsPackage>(ctx));
  packages.push_back(std::make_shared<WebViewPackage>(ctx));
  packages.push_back(std::make_shared<AsyncStoragePackage>(ctx));
  packages.push_back(std::make_shared<RNAudioRecorderPlayerPackage>(ctx));
  packages.push_back(std::make_shared<SafeAreaViewPackage>(ctx));
  packages.push_back(std::make_shared<RNCVideoPackage>(ctx));
  packages.push_back(std::make_shared<FlashListPackage>(ctx));
  packages.push_back(std::make_shared<ClipboardPackage>(ctx));
  packages.push_back(std::make_shared<VisionCameraPackage>(ctx));
  packages.push_back(std::make_shared<GestureHandlerPackage>(ctx));
  packages.push_back(std::make_shared<ImageCropPickerPackage>(ctx));
  
  return packages;
}