#!/usr/bin/env python3
"""Full pipeline: project_discovery Agent → framework_profile → indexing → summary → appmap → macros."""

from __future__ import annotations

import asyncio
import logging
import os
import sys
import time

os.environ.setdefault("EMBEDDED_MODE", "True")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

PROJECT_PATH = "/Users/huangjinhuan/Projects/Ruoyi-Cloud-Plus"
PROJECT_ID = 122
WORKSPACE_ROOT = "/Users/huangjinhuan/Projects"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s", handlers=[logging.StreamHandler(sys.stdout)])
logger = logging.getLogger("pipeline_test")

passed = 0
failed = 0

def check(name: str, ok: bool, detail: str = ""):
    global passed, failed
    if ok:
        passed += 1
        logger.info(f"  \u2705 {name}")
    else:
        failed += 1
        logger.error(f"  \u274c {name}: {detail}")

async def step1_project_discovery():
    from sqlalchemy import delete
    from app.infrastructure.database import session_scope
    from app.models.macro import Macro
    from app.models.app_map import AppMap
    async with session_scope() as s:
        await s.execute(delete(Macro).where(Macro.project_id == PROJECT_ID))
        await s.execute(delete(AppMap).where(AppMap.project_id == PROJECT_ID))
        await s.commit()

    from app.core.project.utils import read_project_json, write_project_json
    pj = read_project_json(PROJECT_PATH)
    pj.pop("framework_profile", None)
    write_project_json(PROJECT_PATH, pj)

    from sqlalchemy import select
    from app.models.learning import LearnedSkill
    async with session_scope() as s:
        skill = (await s.execute(select(LearnedSkill).where(LearnedSkill.name == "Project Discovery", LearnedSkill.is_active.is_(True)))).scalar_one_or_none()
    if not skill:
        from app.core.config import settings
        from app.core.learning.skill_importer import SkillImporter
        await SkillImporter.import_from_directory(settings.SKILLS_DIR)
        async with session_scope() as s:
            skill = (await s.execute(select(LearnedSkill).where(LearnedSkill.name == "Project Discovery", LearnedSkill.is_active.is_(True)))).scalar_one_or_none()
    assert skill is not None

    from app.core.engine.dispatch import dispatch_agent_run
    from app.core.context import thread_context_store
    thread_id = f"pd-{PROJECT_ID}-{int(time.time())}"
    thread_context_store.set_working_directory(thread_id, PROJECT_PATH)

    result = await dispatch_agent_run(
        thread_id=thread_id,
        message_content=(
            f"**Mission Goal**: Analyze the project at {PROJECT_PATH}.\n"
            "1. Identify tech stack and project type.\n"
            "2. Write a `framework_profile` into `.evoloop/project.json` "
            "with language, framework, build_tool, architecture, role_classifiers, "
            "module_paths, and domain_vocabulary.\n"
            "3. Generate a `PROJECT.md` at the root.\n"
            "4. Stop and report once done."
        ),
        project_id=PROJECT_ID,
        references=[{"type": "skill", "id": str(skill.id), "target_id": str(skill.id), "target_name": skill.name}],
        metadata={"goal_prefix": "[Pipeline Test] "},
    )
    assert result.status != "failed", f"Dispatch failed: {result.error}"
    result.inputs.setdefault("metadata", {})
    result.inputs["metadata"]["skip_persistence"] = True

    from app.core.engine.background_agent import run_agent_background
    await run_agent_background(thread_id, result.inputs)

    pj = read_project_json(PROJECT_PATH)
    fp = pj.get("framework_profile")
    assert fp is not None, "Agent did not write framework_profile"
    check("Step1: framework_profile generated by Agent", True)
    check("  has language", bool(fp.get("language")))

async def step2_entity_grouper():
    from app.core.atlas.source.skeleton import EntityGrouper
    grouper = EntityGrouper(project_path=PROJECT_PATH)
    check("Step2: EntityGrouper loaded", grouper is not None)

async def step3_summary():
    from app.core.project.summarizer import _summarize_project_logic
    await _summarize_project_logic("Ruoyi-Cloud-Plus", PROJECT_PATH)
    check("Step3: Summary generated", True)

async def step4_index():
    from app.core.project.sync_service import ProjectSyncService
    from app.core.project.utils import write_project_json
    from sqlalchemy import select
    from app.infrastructure.database import session_scope
    from app.models.codebase import Repository

    async with session_scope() as s:
        r = await s.execute(select(Repository).where(Repository.local_path == PROJECT_PATH))
        repo = r.scalar_one_or_none()
    if not repo:
        repo = await ProjectSyncService().import_project_by_path(PROJECT_PATH, workspace_root=WORKSPACE_ROOT)
    if repo.project_id != PROJECT_ID:
        async with session_scope() as s:
            db = await s.get(Repository, repo.id)
            db.project_id = PROJECT_ID
            await s.commit()
    write_project_json(PROJECT_PATH, {"project_id": PROJECT_ID, "repo_id": repo.id})

    from app.domain.codebase.indexing.service import IndexingService
    from app.domain.codebase.indexing.manager import indexing_manager
    await IndexingService().index_repository(PROJECT_PATH, repo.id, force=True)
    await indexing_manager._update_indexing_status(repo.id, "completed")
    check("Step4: Indexing complete (0 LLM)", True)

async def step5_appmap_and_macros():
    from app.domain.codebase.generation.runner import run_generation_item
    await run_generation_item(PROJECT_ID, "appmap")
    await run_generation_item(PROJECT_ID, "summary")
    check("Step5: AppMap + Macros generated", True)

async def step6_verify():
    from sqlalchemy import select, func, text
    from app.infrastructure.database import session_scope
    from app.models.macro import Macro
    from app.models.app_map import AppMap

    async with session_scope() as s:
        am = (await s.execute(select(func.count(AppMap.id)).where(AppMap.project_id == PROJECT_ID))).scalar()
        mc = (await s.execute(select(func.count(Macro.id)).where(Macro.project_id == PROJECT_ID))).scalar()
        check("Step6: AppMaps > 0", am > 0, f"got {am}")
        check("Step6: Macros > 0", mc > 0, f"got {mc}")

        entities = [r[0] for r in (await s.execute(text("SELECT DISTINCT entity FROM app_maps WHERE project_id = :pid AND status = 'active'"), {"pid": PROJECT_ID})).all()]
        garbage = {"resize", "ruoyi-ui", "ruoyi-auth", "ruoyi-example", "ruoyi-gateway", "ruoyi-modules", "ruoyiresourceapplication", "resourceapplicationrunner"}
        found = [e for e in entities if e in garbage]
        check("Step6: No garbage entities", len(found) == 0, f"{found}")

        dupes = (await s.execute(text("SELECT name, COUNT(*) FROM macros WHERE project_id = :pid GROUP BY name HAVING COUNT(*) > 1"), {"pid": PROJECT_ID})).all()
        check("Step6: No duplicate macro names", len(dupes) == 0, f"{len(dupes)} dupes")

        bad = 0
        for m in (await s.execute(select(Macro).where(Macro.project_id == PROJECT_ID).limit(30))).scalars().all():
            for t in (m.trigger_patterns or []):
                if "{{" in t: bad += 1
        check("Step6: No {{}} in trigger_patterns", bad == 0, f"{bad} bad")

    from app.core.project.utils import read_project_json
    pj = read_project_json(PROJECT_PATH)
    check("Step6: framework_profile preserved", "framework_profile" in pj)

async def step7_profile_api():
    from app.core.project.utils import read_project_json
    pj = read_project_json(PROJECT_PATH)
    fp = pj.get("framework_profile")
    check("Step7: Profile API has framework_profile", fp is not None)
    if fp:
        check("  language set", bool(fp.get("language")))
        check("  domain_vocabulary non-empty", len(fp.get("domain_vocabulary") or []) > 0)

async def main():
    from app.infrastructure.database.resource_manager import db_resource_manager
    await db_resource_manager.initialize()

    from app.core.evocloud import evocloud_manager
    from app.core.identity import identity_service
    evocloud_manager.initialize()
    login = await evocloud_manager.login("preterchan", "hellomylife")
    await identity_service.set_token(login["token"], login.get("refresh_token", ""))

    from app.core.environment import awaken
    await awaken()

    from app.infrastructure.config.service import SystemConfigService
    SystemConfigService.set_value("LLM_MODEL", "deepseek-v4-flash")
    SystemConfigService.set_value("LLM_CONFIG_TYPE", "platform")

    try:
        t0 = time.time()
        await step1_project_discovery()
        await step2_entity_grouper()
        await step3_summary()
        await step4_index()
        await step5_appmap_and_macros()
        await step6_verify()
        await step7_profile_api()
        elapsed = time.time() - t0

        logger.info("=" * 60)
        logger.info(f"RESULTS: {passed} passed, {failed} failed ({elapsed:.1f}s)")
        logger.info("=" * 60)
        if failed:
            logger.error(f"\u274c {failed} FAILURES")
            sys.exit(1)
        logger.info("\u2705 ALL TESTS PASSED")
    finally:
        await db_resource_manager.shutdown()

if __name__ == "__main__":
    asyncio.run(main())
