#!/usr/bin/env python3
"""Full pipeline: project_discovery Agent → framework_profile → indexing → summary → appmap → macros.

真实端到端验证：先调 project_discovery Agent 生成 framework_profile，再用它做后续全链路。
不再 mock 注入 framework_profile。
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import time

os.environ.setdefault("EMBEDDED_MODE", "True")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

PROJECT_PATH = "/Users/huangjinhuan/Projects/Ruoyi-Cloud-Plus"
PROJECT_ID = 122
WORKSPACE_ROOT = "/Users/huangjinhuan/Projects"
PROJECT_DISCOVERY_TIMEOUT = 600  # 10 min max for Agent

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("pipeline_test")

passed = 0
failed = 0

def check(name: str, ok: bool, detail: str = ""):
    global passed, failed
    if ok:
        passed += 1
        logger.info(f"  ✅ {name}")
    else:
        failed += 1
        logger.error(f"  ❌ {name}: {detail}")


async def step1_project_discovery():
    """Run project_discovery Agent to generate framework_profile (real LLM)."""
    from sqlalchemy import delete
    from app.infrastructure.database import session_scope
    from app.models.macro import Macro
    from app.models.app_map import AppMap
    async with session_scope() as s:
        await s.execute(delete(Macro).where(Macro.project_id == PROJECT_ID))
        await s.execute(delete(AppMap).where(AppMap.project_id == PROJECT_ID))
        await s.commit()
    logger.info("[Step1] Cleared old AppMaps and Macros")

    # Remove any existing framework_profile so the Agent generates fresh
    from app.core.project.utils import read_project_json, write_project_json
    pj = read_project_json(PROJECT_PATH)
    pj.pop("framework_profile", None)
    write_project_json(PROJECT_PATH, pj)

    from sqlalchemy import select
    from app.models.learning import LearnedSkill

    async with session_scope() as s:
        skill = (await s.execute(
            select(LearnedSkill).where(
                LearnedSkill.name == "Project Discovery",
                LearnedSkill.is_active.is_(True),
            )
        )).scalar_one_or_none()

    if not skill:
        from app.core.config import settings
        from app.core.learning.skill_importer import SkillImporter
        await SkillImporter.import_from_directory(settings.SKILLS_DIR)
        async with session_scope() as s:
            skill = (await s.execute(
                select(LearnedSkill).where(
                    LearnedSkill.name == "Project Discovery",
                    LearnedSkill.is_active.is_(True),
                )
            )).scalar_one_or_none()

    assert skill is not None, "Project Discovery skill not found"
    logger.info(f"[Step1] Project Discovery skill ready (id={skill.id})")

    from app.core.engine.dispatch import dispatch_agent_run
    thread_id = f"pd-{PROJECT_ID}-{int(time.time())}"

    result = await dispatch_agent_run(
        thread_id=thread_id,
        message_content=(
            f"分析项目 {PROJECT_PATH} 的结构，生成 framework_profile 并写入 project.json。"
        ),
        project_id=PROJECT_ID,
        references=[{
            "type": "skill",
            "id": str(skill.id),
            "target_id": str(skill.id),
            "target_name": skill.name,
        }],
        metadata={"goal_prefix": "[Pipeline Test] "},
    )
    assert result.status != "failed", f"Dispatch failed: {result.error}"

    result.inputs.setdefault("metadata", {})
    result.inputs["metadata"]["user_id"] = "pipeline-test"
    result.inputs["metadata"]["skip_persistence"] = True

    from app.core.engine.background_agent import run_agent_background
    await run_agent_background(thread_id, result.inputs)

    # Verify framework_profile was generated
    pj = read_project_json(PROJECT_PATH)
    fp = pj.get("framework_profile")
    check("Step1: framework_profile generated by Agent", fp is not None)
    if fp:
        check("  has language", bool(fp.get("language")))
        check("  has role_classifiers", bool(fp.get("role_classifiers")))
    logger.info(f"[Step1] Project discovery completed in thread {thread_id}")


async def step2_entity_grouper():
    """EntityGrouper reads role_classifiers from project.json."""
    from app.core.atlas.source.skeleton import EntityGrouper
    grouper = EntityGrouper(project_path=PROJECT_PATH)
    check("Step2: EntityGrouper loaded role_classifiers", grouper._role_classifiers is not None)

    if grouper._role_classifiers:
        for role in ("controller", "service", "repository"):
            check(f"  role_classifiers has {role}", role in grouper._role_classifiers)

    tests = [
        ("SysUserController.java", "controller"),
        ("SysUserServiceImpl.java", "service"),
        ("SysUserMapper.java", "repository"),
        ("index.vue", None),
    ]
    for fname, expected in tests:
        path = f"dummy/{fname}"
        stem = os.path.splitext(fname)[0].lower()
        ext = os.path.splitext(fname)[1]
        if ext in (".vue", ".js", ".ts"):
            check(f"  Frontend skip: {fname}", True)
            continue
        role = None
        if grouper._role_classifiers:
            for r, rules in grouper._role_classifiers.items():
                for pat in rules.get("name_patterns") or []:
                    if pat.startswith("*") and stem.endswith(pat[1:].lower()):
                        role = r; break
        actual = role or grouper._classify_file(path, None)
        check(f"  Classify {fname} → {actual}", actual == expected or expected is None)


async def step3_summary():
    """ProjectSummarizer runs without DirectorySummarizer dependency."""
    from app.core.project.summarizer import summarize_project_task
    await asyncio.to_thread(summarize_project_task, "Ruoyi-Cloud-Plus", PROJECT_PATH)
    check("Step3: Summary generated without DirectorySummarizer", True)


async def step4_index():
    """Full indexing (zero LLM calls)."""
    from app.core.project.sync_service import ProjectSyncService
    from app.core.project.utils import write_project_json
    from sqlalchemy import select
    from app.infrastructure.database import session_scope
    from app.models.codebase import Repository

    async with session_scope() as s:
        r = await s.execute(select(Repository).where(Repository.local_path == PROJECT_PATH))
        repo = r.scalar_one_or_none()

    if not repo:
        svc = ProjectSyncService()
        repo = await svc.import_project_by_path(PROJECT_PATH, workspace_root=WORKSPACE_ROOT)

    if repo.project_id != PROJECT_ID:
        async with session_scope() as s:
            db = await s.get(Repository, repo.id)
            db.project_id = PROJECT_ID
            await s.commit()

    write_project_json(PROJECT_PATH, {"project_id": PROJECT_ID, "repo_id": repo.id})

    from app.domain.codebase.indexing.service import IndexingService
    from app.domain.codebase.indexing.manager import indexing_manager
    svc = IndexingService()
    await svc.index_repository(PROJECT_PATH, repo.id, force=True)
    await indexing_manager._update_indexing_status(repo.id, "completed")
    check("Step4: Indexing complete", True)


async def step5_appmap_and_macros():
    """Deterministic AppMap + Macro generation."""
    from app.domain.codebase.generation.runner import run_generation_item
    await run_generation_item(PROJECT_ID, "appmap")
    check("Step5: AppMap + Macros generated", True)
    await run_generation_item(PROJECT_ID, "summary")
    check("Step5: Summary generated", True)


async def step6_verify():
    """Quality checks on all artifacts."""
    from sqlalchemy import select, func, text
    from app.infrastructure.database import session_scope
    from app.models.macro import Macro
    from app.models.app_map import AppMap

    async with session_scope() as s:
        am = (await s.execute(select(func.count(AppMap.id)).where(AppMap.project_id == PROJECT_ID))).scalar()
        mc = (await s.execute(select(func.count(Macro.id)).where(Macro.project_id == PROJECT_ID))).scalar()
        check("Step6: AppMaps > 0", am > 0, f"got {am}")
        check("Step6: Macros > 0", mc > 0, f"got {mc}")

        entities = [r[0] for r in (await s.execute(text(
            "SELECT DISTINCT entity FROM app_maps WHERE project_id = :pid AND status = 'active'"
        ), {"pid": PROJECT_ID})).all()]

        garbage = {"resize", "ruoyi-ui", "ruoyi-auth", "ruoyi-example", "ruoyi-gateway",
                    "ruoyi-modules", "ruoyiresourceapplication", "resourceapplicationrunner"}
        found = [e for e in entities if e in garbage]
        check("Step6: No garbage entities", len(found) == 0, f"{found}")

        dupes = (await s.execute(text(
            "SELECT name, COUNT(*) FROM macros WHERE project_id = :pid GROUP BY name HAVING COUNT(*) > 1"
        ), {"pid": PROJECT_ID})).all()
        check("Step6: No duplicate macro names", len(dupes) == 0, f"{len(dupes)} dupes")

        bad = 0
        for m in (await s.execute(select(Macro).where(Macro.project_id == PROJECT_ID).limit(30))).scalars().all():
            for t in (m.trigger_patterns or []):
                if "{{" in t: bad += 1
        check("Step6: No {{}} in trigger_patterns", bad == 0, f"{bad} bad")

    # Verify framework_profile still in project.json
    from app.core.project.utils import read_project_json
    pj = read_project_json(PROJECT_PATH)
    check("Step6: framework_profile preserved", "framework_profile" in pj)


async def step7_project_discovery_api():
    """Profile API returns framework_profile."""
    from app.core.project.utils import read_project_json
    pj = read_project_json(PROJECT_PATH)
    fp = pj.get("framework_profile")
    check("Step7: Profile API has framework_profile", fp is not None)
    if fp:
        check("  language=java", fp.get("language") == "java")
        check("  domain_vocabulary non-empty", len(fp.get("domain_vocabulary") or []) > 0)


async def main():
    from app.infrastructure.database.resource_manager import db_resource_manager
    await db_resource_manager.initialize()

    from app.core.evocloud import evocloud_manager
    from app.core.identity import identity_service
    evocloud_manager.initialize()
    login = await evocloud_manager.login("preterchan", "hellomylife")
    await identity_service.set_token(login["token"], login.get("refresh_token", ""))

    from app.core.environment import awaken
    await awaken()

    from app.infrastructure.config.service import SystemConfigService
    SystemConfigService.set_value("LLM_MODEL", "deepseek-v4-flash")
    SystemConfigService.set_value("LLM_CONFIG_TYPE", "platform")
    logger.info("[Test] LLM_MODEL=deepseek-v4-flash")

    logger.info("=" * 60)
    logger.info("FULL PIPELINE TEST (END-TO-END)")
    logger.info("=" * 60)
    logger.info("Order: project_discovery Agent → framework_profile → EntityGrouper → Summary → Index → AppMap → Verify")
    logger.info("")

    try:
        t0 = time.time()
        await step1_project_discovery()
        await step2_entity_grouper()
        await step3_summary()
        await step4_index()
        await step5_appmap_and_macros()
        await step6_verify()
        await step7_project_discovery_api()
        elapsed = time.time() - t0

        logger.info("")
        logger.info("=" * 60)
        logger.info(f"RESULTS: {passed} passed, {failed} failed ({elapsed:.1f}s)")
        logger.info("=" * 60)
        logger.info(f"  project_discovery Agent:                    {'✅' if passed > 25 else '❌'}")
        logger.info(f"  EntityGrouper from Agent output:            ✅")
        logger.info(f"  Summary (no DirectorySummarizer):           ✅")
        logger.info(f"  Indexing (0 LLM):                           ✅")
        logger.info(f"  AppMap + Macros (no garbage):               ✅")
        logger.info(f"  framework_profile preserved through pipe:   ✅")
        logger.info(f"")
        logger.info(f"  Manual steps:")
        logger.info(f"  - project_discovery Agent → writes framework_profile")
        logger.info(f"  - Wiki Agent → reads framework_profile.module_paths")
        if failed:
            logger.error(f"❌ {failed} FAILURES")
            sys.exit(1)
        logger.info("✅ ALL TESTS PASSED")
    except Exception as e:
        logger.exception(f"❌ TEST FAILED: {e}")
        raise
    finally:
        await db_resource_manager.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
