/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMcpRouteImport } from './routes/_layout/mcp'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutProjectsProjectIdIndexRouteImport } from './routes/_layout/projects.$projectId.index'
import { Route as LayoutProjectsProjectIdTimesheetRouteImport } from './routes/_layout/projects.$projectId.timesheet'
import { Route as LayoutProjectsProjectIdTasksRouteImport } from './routes/_layout/projects.$projectId.tasks'
import { Route as LayoutProjectsProjectIdReportsRouteImport } from './routes/_layout/projects.$projectId.reports'
import { Route as LayoutProjectsProjectIdGanttRouteImport } from './routes/_layout/projects.$projectId.gantt'
import { Route as LayoutProjectsProjectIdFilesRouteImport } from './routes/_layout/projects.$projectId.files'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMcpRoute = LayoutMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdIndexRoute =
  LayoutProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdTimesheetRoute =
  LayoutProjectsProjectIdTimesheetRouteImport.update({
    id: '/timesheet',
    path: '/timesheet',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdTasksRoute =
  LayoutProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdReportsRoute =
  LayoutProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdGanttRoute =
  LayoutProjectsProjectIdGanttRouteImport.update({
    id: '/gantt',
    path: '/gantt',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdFilesRoute =
  LayoutProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof LayoutChatRoute
  '/mcp': typeof LayoutMcpRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/projects': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/gantt': typeof LayoutProjectsProjectIdGanttRoute
  '/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/timesheet': typeof LayoutProjectsProjectIdTimesheetRoute
  '/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof LayoutChatRoute
  '/mcp': typeof LayoutMcpRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/gantt': typeof LayoutProjectsProjectIdGanttRoute
  '/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/timesheet': typeof LayoutProjectsProjectIdTimesheetRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/mcp': typeof LayoutMcpRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/_layout/projects/$projectId/gantt': typeof LayoutProjectsProjectIdGanttRoute
  '/_layout/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/_layout/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/_layout/projects/$projectId/timesheet': typeof LayoutProjectsProjectIdTimesheetRoute
  '/_layout/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/mcp'
    | '/settings'
    | '/'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/files'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timesheet'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/mcp'
    | '/settings'
    | '/'
    | '/projects'
    | '/projects/$projectId/files'
    | '/projects/$projectId/gantt'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/timesheet'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/chat'
    | '/_layout/mcp'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/projects/$projectId'
    | '/_layout/projects/'
    | '/_layout/projects/$projectId/files'
    | '/_layout/projects/$projectId/gantt'
    | '/_layout/projects/$projectId/reports'
    | '/_layout/projects/$projectId/tasks'
    | '/_layout/projects/$projectId/timesheet'
    | '/_layout/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mcp': {
      id: '/_layout/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof LayoutMcpRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/': {
      id: '/_layout/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof LayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/timesheet': {
      id: '/_layout/projects/$projectId/timesheet'
      path: '/timesheet'
      fullPath: '/projects/$projectId/timesheet'
      preLoaderRoute: typeof LayoutProjectsProjectIdTimesheetRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/tasks': {
      id: '/_layout/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof LayoutProjectsProjectIdTasksRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/reports': {
      id: '/_layout/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof LayoutProjectsProjectIdReportsRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/gantt': {
      id: '/_layout/projects/$projectId/gantt'
      path: '/gantt'
      fullPath: '/projects/$projectId/gantt'
      preLoaderRoute: typeof LayoutProjectsProjectIdGanttRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/files': {
      id: '/_layout/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof LayoutProjectsProjectIdFilesRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
  }
}

interface LayoutProjectsProjectIdRouteChildren {
  LayoutProjectsProjectIdFilesRoute: typeof LayoutProjectsProjectIdFilesRoute
  LayoutProjectsProjectIdGanttRoute: typeof LayoutProjectsProjectIdGanttRoute
  LayoutProjectsProjectIdReportsRoute: typeof LayoutProjectsProjectIdReportsRoute
  LayoutProjectsProjectIdTasksRoute: typeof LayoutProjectsProjectIdTasksRoute
  LayoutProjectsProjectIdTimesheetRoute: typeof LayoutProjectsProjectIdTimesheetRoute
  LayoutProjectsProjectIdIndexRoute: typeof LayoutProjectsProjectIdIndexRoute
}

const LayoutProjectsProjectIdRouteChildren: LayoutProjectsProjectIdRouteChildren =
  {
    LayoutProjectsProjectIdFilesRoute: LayoutProjectsProjectIdFilesRoute,
    LayoutProjectsProjectIdGanttRoute: LayoutProjectsProjectIdGanttRoute,
    LayoutProjectsProjectIdReportsRoute: LayoutProjectsProjectIdReportsRoute,
    LayoutProjectsProjectIdTasksRoute: LayoutProjectsProjectIdTasksRoute,
    LayoutProjectsProjectIdTimesheetRoute:
      LayoutProjectsProjectIdTimesheetRoute,
    LayoutProjectsProjectIdIndexRoute: LayoutProjectsProjectIdIndexRoute,
  }

const LayoutProjectsProjectIdRouteWithChildren =
  LayoutProjectsProjectIdRoute._addFileChildren(
    LayoutProjectsProjectIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutMcpRoute: typeof LayoutMcpRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRouteWithChildren
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutMcpRoute: LayoutMcpRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRouteWithChildren,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
