/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as MarkerOverlayRouteImport } from './routes/marker-overlay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AndroidMarkerOverlayRouteImport } from './routes/android-marker-overlay'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodosRouteImport } from './routes/_layout/todos'
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout.subscription'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLearningRouteImport } from './routes/_layout/learning'
import { Route as LayoutKnowledgeRouteImport } from './routes/_layout/knowledge'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutSubscriptionIndexRouteImport } from './routes/_layout.subscription.index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutProjectsProjectIdIndexRouteImport } from './routes/_layout/projects.$projectId.index'
import { Route as LayoutProjectsProjectIdWikiRouteImport } from './routes/_layout/projects.$projectId.wiki'
import { Route as LayoutProjectsProjectIdTasksRouteImport } from './routes/_layout/projects.$projectId.tasks'
import { Route as LayoutProjectsProjectIdReportsRouteImport } from './routes/_layout/projects.$projectId.reports'
import { Route as LayoutProjectsProjectIdProfileRouteImport } from './routes/_layout/projects.$projectId.profile'
import { Route as LayoutProjectsProjectIdKnowledgeRouteImport } from './routes/_layout/projects.$projectId.knowledge'
import { Route as LayoutProjectsProjectIdFilesRouteImport } from './routes/_layout/projects.$projectId.files'
import { Route as LayoutLearningSkillsSkillIdEditRouteImport } from './routes/_layout/learning.skills.$skillId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerOverlayRoute = MarkerOverlayRouteImport.update({
  id: '/marker-overlay',
  path: '/marker-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidMarkerOverlayRoute = AndroidMarkerOverlayRouteImport.update({
  id: '/android-marker-overlay',
  path: '/android-marker-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosRoute = LayoutTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearningRoute = LayoutLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeRoute = LayoutKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionIndexRoute = LayoutSubscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSubscriptionRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdIndexRoute =
  LayoutProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdWikiRoute =
  LayoutProjectsProjectIdWikiRouteImport.update({
    id: '/wiki',
    path: '/wiki',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdTasksRoute =
  LayoutProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdReportsRoute =
  LayoutProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdProfileRoute =
  LayoutProjectsProjectIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdKnowledgeRoute =
  LayoutProjectsProjectIdKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdFilesRoute =
  LayoutProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutLearningSkillsSkillIdEditRoute =
  LayoutLearningSkillsSkillIdEditRouteImport.update({
    id: '/skills/$skillId/edit',
    path: '/skills/$skillId/edit',
    getParentRoute: () => LayoutLearningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof LayoutChatRoute
  '/knowledge': typeof LayoutKnowledgeRoute
  '/learning': typeof LayoutLearningRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRouteWithChildren
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/projects': typeof LayoutProjectsIndexRoute
  '/subscription/': typeof LayoutSubscriptionIndexRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/knowledge': typeof LayoutProjectsProjectIdKnowledgeRoute
  '/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
}
export interface FileRoutesByTo {
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof LayoutChatRoute
  '/knowledge': typeof LayoutKnowledgeRoute
  '/learning': typeof LayoutLearningRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/subscription': typeof LayoutSubscriptionIndexRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/knowledge': typeof LayoutProjectsProjectIdKnowledgeRoute
  '/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
  '/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/knowledge': typeof LayoutKnowledgeRoute
  '/_layout/learning': typeof LayoutLearningRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subscription': typeof LayoutSubscriptionRouteWithChildren
  '/_layout/todos': typeof LayoutTodosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/subscription/': typeof LayoutSubscriptionIndexRoute
  '/_layout/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/_layout/projects/$projectId/knowledge': typeof LayoutProjectsProjectIdKnowledgeRoute
  '/_layout/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/_layout/projects/$projectId/reports': typeof LayoutProjectsProjectIdReportsRoute
  '/_layout/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/_layout/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/_layout/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/_layout/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/knowledge'
    | '/learning'
    | '/settings'
    | '/subscription'
    | '/todos'
    | '/'
    | '/projects/$projectId'
    | '/projects'
    | '/subscription/'
    | '/projects/$projectId/files'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/profile'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId/'
    | '/learning/skills/$skillId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/knowledge'
    | '/learning'
    | '/settings'
    | '/todos'
    | '/'
    | '/projects'
    | '/subscription'
    | '/projects/$projectId/files'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/profile'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId'
    | '/learning/skills/$skillId/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/chat'
    | '/_layout/knowledge'
    | '/_layout/learning'
    | '/_layout/settings'
    | '/_layout/subscription'
    | '/_layout/todos'
    | '/_layout/'
    | '/_layout/projects/$projectId'
    | '/_layout/projects/'
    | '/_layout/subscription/'
    | '/_layout/projects/$projectId/files'
    | '/_layout/projects/$projectId/knowledge'
    | '/_layout/projects/$projectId/profile'
    | '/_layout/projects/$projectId/reports'
    | '/_layout/projects/$projectId/tasks'
    | '/_layout/projects/$projectId/wiki'
    | '/_layout/projects/$projectId/'
    | '/_layout/learning/skills/$skillId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AndroidMarkerOverlayRoute: typeof AndroidMarkerOverlayRoute
  LoginRoute: typeof LoginRoute
  MarkerOverlayRoute: typeof MarkerOverlayRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker-overlay': {
      id: '/marker-overlay'
      path: '/marker-overlay'
      fullPath: '/marker-overlay'
      preLoaderRoute: typeof MarkerOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-marker-overlay': {
      id: '/android-marker-overlay'
      path: '/android-marker-overlay'
      fullPath: '/android-marker-overlay'
      preLoaderRoute: typeof AndroidMarkerOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos': {
      id: '/_layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof LayoutTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription': {
      id: '/_layout/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutSubscriptionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learning': {
      id: '/_layout/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LayoutLearningRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge': {
      id: '/_layout/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof LayoutKnowledgeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription/': {
      id: '/_layout/subscription/'
      path: '/'
      fullPath: '/subscription/'
      preLoaderRoute: typeof LayoutSubscriptionIndexRouteImport
      parentRoute: typeof LayoutSubscriptionRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/': {
      id: '/_layout/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof LayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/wiki': {
      id: '/_layout/projects/$projectId/wiki'
      path: '/wiki'
      fullPath: '/projects/$projectId/wiki'
      preLoaderRoute: typeof LayoutProjectsProjectIdWikiRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/tasks': {
      id: '/_layout/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof LayoutProjectsProjectIdTasksRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/reports': {
      id: '/_layout/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof LayoutProjectsProjectIdReportsRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/profile': {
      id: '/_layout/projects/$projectId/profile'
      path: '/profile'
      fullPath: '/projects/$projectId/profile'
      preLoaderRoute: typeof LayoutProjectsProjectIdProfileRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/knowledge': {
      id: '/_layout/projects/$projectId/knowledge'
      path: '/knowledge'
      fullPath: '/projects/$projectId/knowledge'
      preLoaderRoute: typeof LayoutProjectsProjectIdKnowledgeRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/files': {
      id: '/_layout/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof LayoutProjectsProjectIdFilesRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/learning/skills/$skillId/edit': {
      id: '/_layout/learning/skills/$skillId/edit'
      path: '/skills/$skillId/edit'
      fullPath: '/learning/skills/$skillId/edit'
      preLoaderRoute: typeof LayoutLearningSkillsSkillIdEditRouteImport
      parentRoute: typeof LayoutLearningRoute
    }
  }
}

interface LayoutLearningRouteChildren {
  LayoutLearningSkillsSkillIdEditRoute: typeof LayoutLearningSkillsSkillIdEditRoute
}

const LayoutLearningRouteChildren: LayoutLearningRouteChildren = {
  LayoutLearningSkillsSkillIdEditRoute: LayoutLearningSkillsSkillIdEditRoute,
}

const LayoutLearningRouteWithChildren = LayoutLearningRoute._addFileChildren(
  LayoutLearningRouteChildren,
)

interface LayoutSubscriptionRouteChildren {
  LayoutSubscriptionIndexRoute: typeof LayoutSubscriptionIndexRoute
}

const LayoutSubscriptionRouteChildren: LayoutSubscriptionRouteChildren = {
  LayoutSubscriptionIndexRoute: LayoutSubscriptionIndexRoute,
}

const LayoutSubscriptionRouteWithChildren =
  LayoutSubscriptionRoute._addFileChildren(LayoutSubscriptionRouteChildren)

interface LayoutProjectsProjectIdRouteChildren {
  LayoutProjectsProjectIdFilesRoute: typeof LayoutProjectsProjectIdFilesRoute
  LayoutProjectsProjectIdKnowledgeRoute: typeof LayoutProjectsProjectIdKnowledgeRoute
  LayoutProjectsProjectIdProfileRoute: typeof LayoutProjectsProjectIdProfileRoute
  LayoutProjectsProjectIdReportsRoute: typeof LayoutProjectsProjectIdReportsRoute
  LayoutProjectsProjectIdTasksRoute: typeof LayoutProjectsProjectIdTasksRoute
  LayoutProjectsProjectIdWikiRoute: typeof LayoutProjectsProjectIdWikiRoute
  LayoutProjectsProjectIdIndexRoute: typeof LayoutProjectsProjectIdIndexRoute
}

const LayoutProjectsProjectIdRouteChildren: LayoutProjectsProjectIdRouteChildren =
  {
    LayoutProjectsProjectIdFilesRoute: LayoutProjectsProjectIdFilesRoute,
    LayoutProjectsProjectIdKnowledgeRoute:
      LayoutProjectsProjectIdKnowledgeRoute,
    LayoutProjectsProjectIdProfileRoute: LayoutProjectsProjectIdProfileRoute,
    LayoutProjectsProjectIdReportsRoute: LayoutProjectsProjectIdReportsRoute,
    LayoutProjectsProjectIdTasksRoute: LayoutProjectsProjectIdTasksRoute,
    LayoutProjectsProjectIdWikiRoute: LayoutProjectsProjectIdWikiRoute,
    LayoutProjectsProjectIdIndexRoute: LayoutProjectsProjectIdIndexRoute,
  }

const LayoutProjectsProjectIdRouteWithChildren =
  LayoutProjectsProjectIdRoute._addFileChildren(
    LayoutProjectsProjectIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutKnowledgeRoute: typeof LayoutKnowledgeRoute
  LayoutLearningRoute: typeof LayoutLearningRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRouteWithChildren
  LayoutTodosRoute: typeof LayoutTodosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRouteWithChildren
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutKnowledgeRoute: LayoutKnowledgeRoute,
  LayoutLearningRoute: LayoutLearningRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubscriptionRoute: LayoutSubscriptionRouteWithChildren,
  LayoutTodosRoute: LayoutTodosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRouteWithChildren,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AndroidMarkerOverlayRoute: AndroidMarkerOverlayRoute,
  LoginRoute: LoginRoute,
  MarkerOverlayRoute: MarkerOverlayRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
