/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceHudRouteImport } from './routes/voice-hud'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as MarkerOverlayRouteImport } from './routes/marker-overlay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AndroidMarkerOverlayRouteImport } from './routes/android-marker-overlay'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodosRouteImport } from './routes/_layout/todos'
import { Route as LayoutSubscriptionRouteImport } from './routes/_layout.subscription'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLearningRouteImport } from './routes/_layout/learning'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutSubscriptionIndexRouteImport } from './routes/_layout.subscription.index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects.index'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects.$projectId'
import { Route as LayoutProjectsProjectIdIndexRouteImport } from './routes/_layout/projects.$projectId.index'
import { Route as LayoutProjectsProjectIdWikiRouteImport } from './routes/_layout/projects.$projectId.wiki'
import { Route as LayoutProjectsProjectIdVaultRouteImport } from './routes/_layout/projects.$projectId.vault'
import { Route as LayoutProjectsProjectIdTasksRouteImport } from './routes/_layout/projects.$projectId.tasks'
import { Route as LayoutProjectsProjectIdProfileRouteImport } from './routes/_layout/projects.$projectId.profile'
import { Route as LayoutProjectsProjectIdOverviewRouteImport } from './routes/_layout/projects.$projectId.overview'
import { Route as LayoutProjectsProjectIdMacrosRouteImport } from './routes/_layout/projects.$projectId.macros'
import { Route as LayoutProjectsProjectIdGenerationRouteImport } from './routes/_layout/projects.$projectId.generation'
import { Route as LayoutProjectsProjectIdFilesRouteImport } from './routes/_layout/projects.$projectId.files'
import { Route as LayoutProjectsProjectIdAssetsRouteImport } from './routes/_layout/projects.$projectId.assets'
import { Route as LayoutProjectsProjectIdV2IndexRouteImport } from './routes/_layout/projects.$projectId.v2.index'
import { Route as LayoutProjectsProjectIdV2WikiRouteImport } from './routes/_layout/projects.$projectId.v2.wiki'
import { Route as LayoutProjectsProjectIdV2VaultRouteImport } from './routes/_layout/projects.$projectId.v2.vault'
import { Route as LayoutProjectsProjectIdV2TasksRouteImport } from './routes/_layout/projects.$projectId.v2.tasks'
import { Route as LayoutProjectsProjectIdV2ProfileRouteImport } from './routes/_layout/projects.$projectId.v2.profile'
import { Route as LayoutProjectsProjectIdV2GenerationRouteImport } from './routes/_layout/projects.$projectId.v2.generation'
import { Route as LayoutProjectsProjectIdV2AssetsRouteImport } from './routes/_layout/projects.$projectId.v2.assets'
import { Route as LayoutLearningSkillsSkillIdEditRouteImport } from './routes/_layout/learning.skills.$skillId.edit'
import { Route as LayoutLearningMacrosMacroIdEditRouteImport } from './routes/_layout/learning.macros.$macroId.edit'

const VoiceHudRoute = VoiceHudRouteImport.update({
  id: '/voice-hud',
  path: '/voice-hud',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkerOverlayRoute = MarkerOverlayRouteImport.update({
  id: '/marker-overlay',
  path: '/marker-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidMarkerOverlayRoute = AndroidMarkerOverlayRouteImport.update({
  id: '/android-marker-overlay',
  path: '/android-marker-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosRoute = LayoutTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionRoute = LayoutSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearningRoute = LayoutLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSubscriptionIndexRoute = LayoutSubscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSubscriptionRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdIndexRoute =
  LayoutProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdWikiRoute =
  LayoutProjectsProjectIdWikiRouteImport.update({
    id: '/wiki',
    path: '/wiki',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdVaultRoute =
  LayoutProjectsProjectIdVaultRouteImport.update({
    id: '/vault',
    path: '/vault',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdTasksRoute =
  LayoutProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdProfileRoute =
  LayoutProjectsProjectIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdOverviewRoute =
  LayoutProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdMacrosRoute =
  LayoutProjectsProjectIdMacrosRouteImport.update({
    id: '/macros',
    path: '/macros',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdGenerationRoute =
  LayoutProjectsProjectIdGenerationRouteImport.update({
    id: '/generation',
    path: '/generation',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdFilesRoute =
  LayoutProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdAssetsRoute =
  LayoutProjectsProjectIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2IndexRoute =
  LayoutProjectsProjectIdV2IndexRouteImport.update({
    id: '/v2/',
    path: '/v2/',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2WikiRoute =
  LayoutProjectsProjectIdV2WikiRouteImport.update({
    id: '/v2/wiki',
    path: '/v2/wiki',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2VaultRoute =
  LayoutProjectsProjectIdV2VaultRouteImport.update({
    id: '/v2/vault',
    path: '/v2/vault',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2TasksRoute =
  LayoutProjectsProjectIdV2TasksRouteImport.update({
    id: '/v2/tasks',
    path: '/v2/tasks',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2ProfileRoute =
  LayoutProjectsProjectIdV2ProfileRouteImport.update({
    id: '/v2/profile',
    path: '/v2/profile',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2GenerationRoute =
  LayoutProjectsProjectIdV2GenerationRouteImport.update({
    id: '/v2/generation',
    path: '/v2/generation',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutProjectsProjectIdV2AssetsRoute =
  LayoutProjectsProjectIdV2AssetsRouteImport.update({
    id: '/v2/assets',
    path: '/v2/assets',
    getParentRoute: () => LayoutProjectsProjectIdRoute,
  } as any)
const LayoutLearningSkillsSkillIdEditRoute =
  LayoutLearningSkillsSkillIdEditRouteImport.update({
    id: '/skills/$skillId/edit',
    path: '/skills/$skillId/edit',
    getParentRoute: () => LayoutLearningRoute,
  } as any)
const LayoutLearningMacrosMacroIdEditRoute =
  LayoutLearningMacrosMacroIdEditRouteImport.update({
    id: '/macros/$macroId/edit',
    path: '/macros/$macroId/edit',
    getParentRoute: () => LayoutLearningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/voice-hud': typeof VoiceHudRoute
  '/chat': typeof LayoutChatRoute
  '/learning': typeof LayoutLearningRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/subscription': typeof LayoutSubscriptionRouteWithChildren
  '/todos': typeof LayoutTodosRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/projects/': typeof LayoutProjectsIndexRoute
  '/subscription/': typeof LayoutSubscriptionIndexRoute
  '/projects/$projectId/assets': typeof LayoutProjectsProjectIdAssetsRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/generation': typeof LayoutProjectsProjectIdGenerationRoute
  '/projects/$projectId/macros': typeof LayoutProjectsProjectIdMacrosRoute
  '/projects/$projectId/overview': typeof LayoutProjectsProjectIdOverviewRoute
  '/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/vault': typeof LayoutProjectsProjectIdVaultRoute
  '/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/learning/macros/$macroId/edit': typeof LayoutLearningMacrosMacroIdEditRoute
  '/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
  '/projects/$projectId/v2/assets': typeof LayoutProjectsProjectIdV2AssetsRoute
  '/projects/$projectId/v2/generation': typeof LayoutProjectsProjectIdV2GenerationRoute
  '/projects/$projectId/v2/profile': typeof LayoutProjectsProjectIdV2ProfileRoute
  '/projects/$projectId/v2/tasks': typeof LayoutProjectsProjectIdV2TasksRoute
  '/projects/$projectId/v2/vault': typeof LayoutProjectsProjectIdV2VaultRoute
  '/projects/$projectId/v2/wiki': typeof LayoutProjectsProjectIdV2WikiRoute
  '/projects/$projectId/v2/': typeof LayoutProjectsProjectIdV2IndexRoute
}
export interface FileRoutesByTo {
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/voice-hud': typeof VoiceHudRoute
  '/chat': typeof LayoutChatRoute
  '/learning': typeof LayoutLearningRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/subscription': typeof LayoutSubscriptionIndexRoute
  '/projects/$projectId/assets': typeof LayoutProjectsProjectIdAssetsRoute
  '/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/projects/$projectId/generation': typeof LayoutProjectsProjectIdGenerationRoute
  '/projects/$projectId/macros': typeof LayoutProjectsProjectIdMacrosRoute
  '/projects/$projectId/overview': typeof LayoutProjectsProjectIdOverviewRoute
  '/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId/vault': typeof LayoutProjectsProjectIdVaultRoute
  '/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
  '/learning/macros/$macroId/edit': typeof LayoutLearningMacrosMacroIdEditRoute
  '/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
  '/projects/$projectId/v2/assets': typeof LayoutProjectsProjectIdV2AssetsRoute
  '/projects/$projectId/v2/generation': typeof LayoutProjectsProjectIdV2GenerationRoute
  '/projects/$projectId/v2/profile': typeof LayoutProjectsProjectIdV2ProfileRoute
  '/projects/$projectId/v2/tasks': typeof LayoutProjectsProjectIdV2TasksRoute
  '/projects/$projectId/v2/vault': typeof LayoutProjectsProjectIdV2VaultRoute
  '/projects/$projectId/v2/wiki': typeof LayoutProjectsProjectIdV2WikiRoute
  '/projects/$projectId/v2': typeof LayoutProjectsProjectIdV2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/android-marker-overlay': typeof AndroidMarkerOverlayRoute
  '/login': typeof LoginRoute
  '/marker-overlay': typeof MarkerOverlayRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/voice-hud': typeof VoiceHudRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/learning': typeof LayoutLearningRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/subscription': typeof LayoutSubscriptionRouteWithChildren
  '/_layout/todos': typeof LayoutTodosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRouteWithChildren
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/subscription/': typeof LayoutSubscriptionIndexRoute
  '/_layout/projects/$projectId/assets': typeof LayoutProjectsProjectIdAssetsRoute
  '/_layout/projects/$projectId/files': typeof LayoutProjectsProjectIdFilesRoute
  '/_layout/projects/$projectId/generation': typeof LayoutProjectsProjectIdGenerationRoute
  '/_layout/projects/$projectId/macros': typeof LayoutProjectsProjectIdMacrosRoute
  '/_layout/projects/$projectId/overview': typeof LayoutProjectsProjectIdOverviewRoute
  '/_layout/projects/$projectId/profile': typeof LayoutProjectsProjectIdProfileRoute
  '/_layout/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/_layout/projects/$projectId/vault': typeof LayoutProjectsProjectIdVaultRoute
  '/_layout/projects/$projectId/wiki': typeof LayoutProjectsProjectIdWikiRoute
  '/_layout/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/_layout/learning/macros/$macroId/edit': typeof LayoutLearningMacrosMacroIdEditRoute
  '/_layout/learning/skills/$skillId/edit': typeof LayoutLearningSkillsSkillIdEditRoute
  '/_layout/projects/$projectId/v2/assets': typeof LayoutProjectsProjectIdV2AssetsRoute
  '/_layout/projects/$projectId/v2/generation': typeof LayoutProjectsProjectIdV2GenerationRoute
  '/_layout/projects/$projectId/v2/profile': typeof LayoutProjectsProjectIdV2ProfileRoute
  '/_layout/projects/$projectId/v2/tasks': typeof LayoutProjectsProjectIdV2TasksRoute
  '/_layout/projects/$projectId/v2/vault': typeof LayoutProjectsProjectIdV2VaultRoute
  '/_layout/projects/$projectId/v2/wiki': typeof LayoutProjectsProjectIdV2WikiRoute
  '/_layout/projects/$projectId/v2/': typeof LayoutProjectsProjectIdV2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/voice-hud'
    | '/chat'
    | '/learning'
    | '/settings'
    | '/subscription'
    | '/todos'
    | '/projects/$projectId'
    | '/projects/'
    | '/subscription/'
    | '/projects/$projectId/assets'
    | '/projects/$projectId/files'
    | '/projects/$projectId/generation'
    | '/projects/$projectId/macros'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/profile'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/vault'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId/'
    | '/learning/macros/$macroId/edit'
    | '/learning/skills/$skillId/edit'
    | '/projects/$projectId/v2/assets'
    | '/projects/$projectId/v2/generation'
    | '/projects/$projectId/v2/profile'
    | '/projects/$projectId/v2/tasks'
    | '/projects/$projectId/v2/vault'
    | '/projects/$projectId/v2/wiki'
    | '/projects/$projectId/v2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/voice-hud'
    | '/chat'
    | '/learning'
    | '/settings'
    | '/todos'
    | '/'
    | '/projects'
    | '/subscription'
    | '/projects/$projectId/assets'
    | '/projects/$projectId/files'
    | '/projects/$projectId/generation'
    | '/projects/$projectId/macros'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/profile'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/vault'
    | '/projects/$projectId/wiki'
    | '/projects/$projectId'
    | '/learning/macros/$macroId/edit'
    | '/learning/skills/$skillId/edit'
    | '/projects/$projectId/v2/assets'
    | '/projects/$projectId/v2/generation'
    | '/projects/$projectId/v2/profile'
    | '/projects/$projectId/v2/tasks'
    | '/projects/$projectId/v2/vault'
    | '/projects/$projectId/v2/wiki'
    | '/projects/$projectId/v2'
  id:
    | '__root__'
    | '/_layout'
    | '/android-marker-overlay'
    | '/login'
    | '/marker-overlay'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/voice-hud'
    | '/_layout/chat'
    | '/_layout/learning'
    | '/_layout/settings'
    | '/_layout/subscription'
    | '/_layout/todos'
    | '/_layout/'
    | '/_layout/projects/$projectId'
    | '/_layout/projects/'
    | '/_layout/subscription/'
    | '/_layout/projects/$projectId/assets'
    | '/_layout/projects/$projectId/files'
    | '/_layout/projects/$projectId/generation'
    | '/_layout/projects/$projectId/macros'
    | '/_layout/projects/$projectId/overview'
    | '/_layout/projects/$projectId/profile'
    | '/_layout/projects/$projectId/tasks'
    | '/_layout/projects/$projectId/vault'
    | '/_layout/projects/$projectId/wiki'
    | '/_layout/projects/$projectId/'
    | '/_layout/learning/macros/$macroId/edit'
    | '/_layout/learning/skills/$skillId/edit'
    | '/_layout/projects/$projectId/v2/assets'
    | '/_layout/projects/$projectId/v2/generation'
    | '/_layout/projects/$projectId/v2/profile'
    | '/_layout/projects/$projectId/v2/tasks'
    | '/_layout/projects/$projectId/v2/vault'
    | '/_layout/projects/$projectId/v2/wiki'
    | '/_layout/projects/$projectId/v2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AndroidMarkerOverlayRoute: typeof AndroidMarkerOverlayRoute
  LoginRoute: typeof LoginRoute
  MarkerOverlayRoute: typeof MarkerOverlayRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VoiceHudRoute: typeof VoiceHudRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-hud': {
      id: '/voice-hud'
      path: '/voice-hud'
      fullPath: '/voice-hud'
      preLoaderRoute: typeof VoiceHudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marker-overlay': {
      id: '/marker-overlay'
      path: '/marker-overlay'
      fullPath: '/marker-overlay'
      preLoaderRoute: typeof MarkerOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android-marker-overlay': {
      id: '/android-marker-overlay'
      path: '/android-marker-overlay'
      fullPath: '/android-marker-overlay'
      preLoaderRoute: typeof AndroidMarkerOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos': {
      id: '/_layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof LayoutTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription': {
      id: '/_layout/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof LayoutSubscriptionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learning': {
      id: '/_layout/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LayoutLearningRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/subscription/': {
      id: '/_layout/subscription/'
      path: '/'
      fullPath: '/subscription/'
      preLoaderRoute: typeof LayoutSubscriptionIndexRouteImport
      parentRoute: typeof LayoutSubscriptionRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/': {
      id: '/_layout/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof LayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/wiki': {
      id: '/_layout/projects/$projectId/wiki'
      path: '/wiki'
      fullPath: '/projects/$projectId/wiki'
      preLoaderRoute: typeof LayoutProjectsProjectIdWikiRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/vault': {
      id: '/_layout/projects/$projectId/vault'
      path: '/vault'
      fullPath: '/projects/$projectId/vault'
      preLoaderRoute: typeof LayoutProjectsProjectIdVaultRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/tasks': {
      id: '/_layout/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof LayoutProjectsProjectIdTasksRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/profile': {
      id: '/_layout/projects/$projectId/profile'
      path: '/profile'
      fullPath: '/projects/$projectId/profile'
      preLoaderRoute: typeof LayoutProjectsProjectIdProfileRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/overview': {
      id: '/_layout/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof LayoutProjectsProjectIdOverviewRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/macros': {
      id: '/_layout/projects/$projectId/macros'
      path: '/macros'
      fullPath: '/projects/$projectId/macros'
      preLoaderRoute: typeof LayoutProjectsProjectIdMacrosRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/generation': {
      id: '/_layout/projects/$projectId/generation'
      path: '/generation'
      fullPath: '/projects/$projectId/generation'
      preLoaderRoute: typeof LayoutProjectsProjectIdGenerationRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/files': {
      id: '/_layout/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof LayoutProjectsProjectIdFilesRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/assets': {
      id: '/_layout/projects/$projectId/assets'
      path: '/assets'
      fullPath: '/projects/$projectId/assets'
      preLoaderRoute: typeof LayoutProjectsProjectIdAssetsRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/': {
      id: '/_layout/projects/$projectId/v2/'
      path: '/v2'
      fullPath: '/projects/$projectId/v2/'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2IndexRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/wiki': {
      id: '/_layout/projects/$projectId/v2/wiki'
      path: '/v2/wiki'
      fullPath: '/projects/$projectId/v2/wiki'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2WikiRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/vault': {
      id: '/_layout/projects/$projectId/v2/vault'
      path: '/v2/vault'
      fullPath: '/projects/$projectId/v2/vault'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2VaultRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/tasks': {
      id: '/_layout/projects/$projectId/v2/tasks'
      path: '/v2/tasks'
      fullPath: '/projects/$projectId/v2/tasks'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2TasksRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/profile': {
      id: '/_layout/projects/$projectId/v2/profile'
      path: '/v2/profile'
      fullPath: '/projects/$projectId/v2/profile'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2ProfileRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/generation': {
      id: '/_layout/projects/$projectId/v2/generation'
      path: '/v2/generation'
      fullPath: '/projects/$projectId/v2/generation'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2GenerationRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/projects/$projectId/v2/assets': {
      id: '/_layout/projects/$projectId/v2/assets'
      path: '/v2/assets'
      fullPath: '/projects/$projectId/v2/assets'
      preLoaderRoute: typeof LayoutProjectsProjectIdV2AssetsRouteImport
      parentRoute: typeof LayoutProjectsProjectIdRoute
    }
    '/_layout/learning/skills/$skillId/edit': {
      id: '/_layout/learning/skills/$skillId/edit'
      path: '/skills/$skillId/edit'
      fullPath: '/learning/skills/$skillId/edit'
      preLoaderRoute: typeof LayoutLearningSkillsSkillIdEditRouteImport
      parentRoute: typeof LayoutLearningRoute
    }
    '/_layout/learning/macros/$macroId/edit': {
      id: '/_layout/learning/macros/$macroId/edit'
      path: '/macros/$macroId/edit'
      fullPath: '/learning/macros/$macroId/edit'
      preLoaderRoute: typeof LayoutLearningMacrosMacroIdEditRouteImport
      parentRoute: typeof LayoutLearningRoute
    }
  }
}

interface LayoutLearningRouteChildren {
  LayoutLearningMacrosMacroIdEditRoute: typeof LayoutLearningMacrosMacroIdEditRoute
  LayoutLearningSkillsSkillIdEditRoute: typeof LayoutLearningSkillsSkillIdEditRoute
}

const LayoutLearningRouteChildren: LayoutLearningRouteChildren = {
  LayoutLearningMacrosMacroIdEditRoute: LayoutLearningMacrosMacroIdEditRoute,
  LayoutLearningSkillsSkillIdEditRoute: LayoutLearningSkillsSkillIdEditRoute,
}

const LayoutLearningRouteWithChildren = LayoutLearningRoute._addFileChildren(
  LayoutLearningRouteChildren,
)

interface LayoutSubscriptionRouteChildren {
  LayoutSubscriptionIndexRoute: typeof LayoutSubscriptionIndexRoute
}

const LayoutSubscriptionRouteChildren: LayoutSubscriptionRouteChildren = {
  LayoutSubscriptionIndexRoute: LayoutSubscriptionIndexRoute,
}

const LayoutSubscriptionRouteWithChildren =
  LayoutSubscriptionRoute._addFileChildren(LayoutSubscriptionRouteChildren)

interface LayoutProjectsProjectIdRouteChildren {
  LayoutProjectsProjectIdAssetsRoute: typeof LayoutProjectsProjectIdAssetsRoute
  LayoutProjectsProjectIdFilesRoute: typeof LayoutProjectsProjectIdFilesRoute
  LayoutProjectsProjectIdGenerationRoute: typeof LayoutProjectsProjectIdGenerationRoute
  LayoutProjectsProjectIdMacrosRoute: typeof LayoutProjectsProjectIdMacrosRoute
  LayoutProjectsProjectIdOverviewRoute: typeof LayoutProjectsProjectIdOverviewRoute
  LayoutProjectsProjectIdProfileRoute: typeof LayoutProjectsProjectIdProfileRoute
  LayoutProjectsProjectIdTasksRoute: typeof LayoutProjectsProjectIdTasksRoute
  LayoutProjectsProjectIdVaultRoute: typeof LayoutProjectsProjectIdVaultRoute
  LayoutProjectsProjectIdWikiRoute: typeof LayoutProjectsProjectIdWikiRoute
  LayoutProjectsProjectIdIndexRoute: typeof LayoutProjectsProjectIdIndexRoute
  LayoutProjectsProjectIdV2AssetsRoute: typeof LayoutProjectsProjectIdV2AssetsRoute
  LayoutProjectsProjectIdV2GenerationRoute: typeof LayoutProjectsProjectIdV2GenerationRoute
  LayoutProjectsProjectIdV2ProfileRoute: typeof LayoutProjectsProjectIdV2ProfileRoute
  LayoutProjectsProjectIdV2TasksRoute: typeof LayoutProjectsProjectIdV2TasksRoute
  LayoutProjectsProjectIdV2VaultRoute: typeof LayoutProjectsProjectIdV2VaultRoute
  LayoutProjectsProjectIdV2WikiRoute: typeof LayoutProjectsProjectIdV2WikiRoute
  LayoutProjectsProjectIdV2IndexRoute: typeof LayoutProjectsProjectIdV2IndexRoute
}

const LayoutProjectsProjectIdRouteChildren: LayoutProjectsProjectIdRouteChildren =
  {
    LayoutProjectsProjectIdAssetsRoute: LayoutProjectsProjectIdAssetsRoute,
    LayoutProjectsProjectIdFilesRoute: LayoutProjectsProjectIdFilesRoute,
    LayoutProjectsProjectIdGenerationRoute:
      LayoutProjectsProjectIdGenerationRoute,
    LayoutProjectsProjectIdMacrosRoute: LayoutProjectsProjectIdMacrosRoute,
    LayoutProjectsProjectIdOverviewRoute: LayoutProjectsProjectIdOverviewRoute,
    LayoutProjectsProjectIdProfileRoute: LayoutProjectsProjectIdProfileRoute,
    LayoutProjectsProjectIdTasksRoute: LayoutProjectsProjectIdTasksRoute,
    LayoutProjectsProjectIdVaultRoute: LayoutProjectsProjectIdVaultRoute,
    LayoutProjectsProjectIdWikiRoute: LayoutProjectsProjectIdWikiRoute,
    LayoutProjectsProjectIdIndexRoute: LayoutProjectsProjectIdIndexRoute,
    LayoutProjectsProjectIdV2AssetsRoute: LayoutProjectsProjectIdV2AssetsRoute,
    LayoutProjectsProjectIdV2GenerationRoute:
      LayoutProjectsProjectIdV2GenerationRoute,
    LayoutProjectsProjectIdV2ProfileRoute:
      LayoutProjectsProjectIdV2ProfileRoute,
    LayoutProjectsProjectIdV2TasksRoute: LayoutProjectsProjectIdV2TasksRoute,
    LayoutProjectsProjectIdV2VaultRoute: LayoutProjectsProjectIdV2VaultRoute,
    LayoutProjectsProjectIdV2WikiRoute: LayoutProjectsProjectIdV2WikiRoute,
    LayoutProjectsProjectIdV2IndexRoute: LayoutProjectsProjectIdV2IndexRoute,
  }

const LayoutProjectsProjectIdRouteWithChildren =
  LayoutProjectsProjectIdRoute._addFileChildren(
    LayoutProjectsProjectIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutLearningRoute: typeof LayoutLearningRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSubscriptionRoute: typeof LayoutSubscriptionRouteWithChildren
  LayoutTodosRoute: typeof LayoutTodosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRouteWithChildren
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatRoute: LayoutChatRoute,
  LayoutLearningRoute: LayoutLearningRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSubscriptionRoute: LayoutSubscriptionRouteWithChildren,
  LayoutTodosRoute: LayoutTodosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRouteWithChildren,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AndroidMarkerOverlayRoute: AndroidMarkerOverlayRoute,
  LoginRoute: LoginRoute,
  MarkerOverlayRoute: MarkerOverlayRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VoiceHudRoute: VoiceHudRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
