"""
Data models for project requirement analysis.
"""

from datetime import datetime

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database.sql.database import Base
from app.utils.time import utcnow


class ProjectRequirementDocument(Base):
    """
    Project requirement document - stores uploaded requirement files.

    Status flow:
        pending → analyzed → confirmed → breakdown_completed
    """

    __tablename__ = "project_requirement_documents"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    project_id: Mapped[int] = mapped_column(Integer, index=True)
    repo_id: Mapped[int | None] = mapped_column(
        ForeignKey("repositories.id"), nullable=True
    )

    # File info
    file_name: Mapped[str] = mapped_column(String(255))
    file_path: Mapped[str] = mapped_column(Text)
    file_type: Mapped[str] = mapped_column(String(50))  # docx/pdf/xlsx/md/txt
    file_size: Mapped[int] = mapped_column(Integer, default=0)

    # Extracted content
    raw_content: Mapped[str | None] = mapped_column(Text)  # Markdown format
    content_hash: Mapped[str | None] = mapped_column(String(64))

    # Status
    status: Mapped[str] = mapped_column(String(50), default="pending")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )

    # Relationships
    analyses: Mapped[list["ProjectRequirementAnalysis"]] = relationship(
        back_populates="document", cascade="all, delete-orphan"
    )


class ProjectRequirementAnalysis(Base):
    """
    Requirement analysis result - generated by Agent.

    Status flow:
        draft → pending_confirmation → confirmed → breakdown_completed
    """

    __tablename__ = "project_requirement_analyses"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    document_id: Mapped[str] = mapped_column(
        ForeignKey("project_requirement_documents.id")
    )
    project_id: Mapped[int] = mapped_column(Integer, index=True)

    version: Mapped[int] = mapped_column(Integer, default=1)

    # Structured analysis data (JSON)
    # {
    #   "title": "Requirement Title",
    #   "summary": "Brief summary",
    #   "functional_requirements": [...],
    #   "non_functional_requirements": [...],
    #   "user_stories": [...],
    #   "technical_suggestions": [...],
    #   "risks": [...],
    #   "dependencies": [...]
    # }
    analysis_data: Mapped[dict] = mapped_column(JSON, default=dict)

    # Human edit tracking
    user_edited: Mapped[bool] = mapped_column(Boolean, default=False)
    edited_by: Mapped[str | None] = mapped_column(String(100))

    # Status
    status: Mapped[str] = mapped_column(String(50), default="draft")
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow
    )

    # Relationships
    document: Mapped["ProjectRequirementDocument"] = relationship(
        back_populates="analyses"
    )
    tasks: Mapped[list["ProjectRequirementTask"]] = relationship(
        back_populates="analysis", cascade="all, delete-orphan"
    )


class ProjectRequirementTask(Base):
    """
    Broken-down tasks - synced to EvoCloud.
    Supports hierarchical subtasks for Agent task planning.

    Sync status flow:
        pending → syncing → synced → failed
    
    Hierarchy:
        - parent_id is null: root task
        - parent_id is set: subtask of parent
    """

    __tablename__ = "project_requirement_tasks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    analysis_id: Mapped[str] = mapped_column(
        ForeignKey("project_requirement_analyses.id")
    )
    project_id: Mapped[int] = mapped_column(Integer, index=True)

    # EvoCloud task ID (backfilled after sync)
    evocloud_task_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Hierarchy support for subtasks
    parent_id: Mapped[str | None] = mapped_column(
        ForeignKey("project_requirement_tasks.id"), 
        nullable=True,
        index=True
    )
    
    # Task execution status (independent of sync_status)
    status: Mapped[str] = mapped_column(String(50), default="pending")  # pending, in_progress, completed, failed
    progress: Mapped[int] = mapped_column(Integer, default=0)  # 0-100

    # Task data (JSON)
    # {
    #   "title": "Task Title",
    #   "description": "Detailed description",
    #   "priority": "high|medium|low",
    #   "estimated_hours": 8,
    #   "category": "frontend|backend|database",
    #   "tags": [...],
    #   "requirement_refs": ["FR-001", "US-002"],
    #   "acceptance_criteria": [...]
    # }
    task_data: Mapped[dict] = mapped_column(JSON, default=dict)

    # Sync status
    sync_status: Mapped[str] = mapped_column(String(50), default="pending")
    sync_error: Mapped[str | None] = mapped_column(Text)
    synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow
    )

    # Relationships
    analysis: Mapped["ProjectRequirementAnalysis"] = relationship(
        back_populates="tasks"
    )
    parent: Mapped["ProjectRequirementTask | None"] = relationship(
        "ProjectRequirementTask",
        remote_side="ProjectRequirementTask.id",
        back_populates="subtasks"
    )
    subtasks: Mapped[list["ProjectRequirementTask"]] = relationship(
        "ProjectRequirementTask",
        back_populates="parent",
        cascade="all, delete-orphan"
    )
