/* ==========================================================================
   EvoLoop 通用自主值守任务样本集 (sampleDutyQueue.ts)
   真实涵盖通用企业级自主值守核心场景：
   - 包含多生命周期状态 (pending, in_progress, proposed, waiting_acceptance, confirm, completed, failed)
   - 具备完整的四问血统 (因谁而生/输入是谁/产出喂谁/结果谁背书)
   - 包含深度 Agent 思考 (thought)、MCP 工具调用与异构产物
   - 闭环商业决策单选 (D2)、HITL 资金安全门禁 (D5)、仲裁三键 (D3)
   ========================================================================== */

import type { DutyTask, DutyNotification, DashboardKPIs } from "./types"

export const INITIAL_DUTY_KPIS: DashboardKPIs = {
  dutyState: "busy",
  tokenToday: { input: 128450, output: 34200, calls: 68 },
  taskCounts: {
    total: 15,
    inProgress: 1,
    needsYou: 4,
    completed: 0,
  },
}

export const INITIAL_DUTY_TASKS: DutyTask[] = [
  {
    id: "task-1",
    taskNo: 1,
    title: "全域大盘趋势巡检：市场与竞品深度扫描",
    category: "research",
    status: "pending",
    priority: "high",
    riskLevel: "T2",
    source: "cron",
    stage: "大盘巡检",
    x: 0,
    y: 0,
    w: 340,
    dependencies: [],
    provenance: {
      sourceRef: "周期巡检：按 24h 例行触发品类竞争格局与高频需求词扫描",
      upstreamSummary: "无前置依赖，直连外部搜索引擎与大盘数据聚合 API",
      downstreamTargets: ["#T-4 核心方案评估与决策"],
      endorsement: "监察评审（原对话 Agent 事实只读对账）",
    },
    run: { threadId: "thread-patrol-01", llmCalls: 4, inputTokens: 12400, outputTokens: 2100, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 绑定 Worker 执行线程", detail: "分配后台调度容器，挂载工具环境" },
      {
        label: "抓取行业大盘与竞品格局",
        tool: "search.crawl_market_data",
        detail: "检索各核心竞品销量区间与消费者评价走势",
        thought: "检索全网消费大盘，发现 79-129 元价位带销量占比达 48%，兼具品质与高颜值的单品存在明显供给缺口。",
      },
      { label: "统计价格带分布与主力集中区间", tool: "analytics.price_spectrum", detail: "计算出 79-129 元为主力放量价格带" },
      { label: "提取消费痛点与差异化破局点", detail: "归纳长效保温、便携防漏、礼盒化等核心诉求" },
      { label: "self_check · 交叉对账与报告输出", detail: "生成结构化调研报告，提交监察评审" },
    ],
    artifact: {
      id: "art-1",
      type: "report",
      title: "大盘竞品深度调研简报",
      summary: "主流价格带分布在 79-129 元；差异化机会集中在便携防漏与礼盒装形态。",
      body: "【行业大盘洞察】\n· 竞品格局：头部成熟品牌占有率稳定，中腰部缺乏高颜值明星爆款。\n· 主力价格带：79 - 129 元（承载 48% 成交放量）。\n· 需求热词：大容量、12h 长效锁温、便携防漏、车载适配、办公礼盒。\n· 差异化机会：① 锁温实测数据可视化 ② 单手一键防漏杯盖 ③ 国风质感包装礼盒化。",
    },
  },
  {
    id: "task-2",
    taskNo: 2,
    title: "IP 联名价值验证：社群声量与人群画像聚类",
    category: "research",
    status: "pending",
    priority: "medium",
    riskLevel: "T2",
    source: "chat",
    stage: "大盘巡检",
    x: 0,
    y: 0,
    w: 340,
    dependencies: [],
    provenance: {
      sourceRef: "来自对话：「评估经典游戏 IP 与高频日用品的结合转化可能」",
      upstreamSummary: "无前置依赖，直连 IP 社群热度与周边成交历史样本",
      downstreamTargets: ["#T-4 核心方案评估与决策"],
      endorsement: "监察评审（原对话 Agent 只读核验）",
    },
    run: { threadId: "thread-patrol-02", llmCalls: 3, inputTokens: 9800, outputTokens: 1650, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 检索 IP 社群声量走势", detail: "监测梦幻西游官方周边热度与二手溢价" },
      {
        label: "提取客群画像与消费偏好占比",
        tool: "analytics.persona_cluster",
        detail: "收藏向 62% vs 实用日用向 38%",
        thought: "受众集中于 25-35 岁白领客群，具备强烈的身份认同与情怀付费意愿，办公桌面展示频次高。",
      },
      { label: "输出联名日用场景承接建议", detail: "确定以高频实用不锈钢保温杯为破局切入点" },
      { label: "self_check · 意图一致性对账完成", detail: "报告归档，注入下游拓扑" },
    ],
    artifact: {
      id: "art-2",
      type: "report",
      title: "IP 联名可行性评估报告",
      summary: "目标客群对高频日用周边转化意愿极高，建议主打高质感商务办公场景。",
      body: "【IP 衍生品成交分析】\n· 周边日用类目成交环比增长 +28%，实用日用属性占比上升至 38%。\n· 消费画像：25-35 岁新锐白领，注重材质品质与情怀细节。\n· 推荐承接形态：官方经典原画联名不锈钢杯，主打办公与礼盒赠送场景。",
    },
  },
  {
    id: "task-3",
    taskNo: 3,
    title: "在售商品健康度盘点：动销分析与价格断层",
    category: "inventory",
    status: "proposed",
    priority: "medium",
    riskLevel: "T3",
    source: "cron",
    stage: "大盘巡检",
    x: 0,
    y: 0,
    w: 340,
    dependencies: [],
    provenance: {
      sourceRef: "周期巡检：每日例行全量商品动销与库存警戒线对账",
      upstreamSummary: "调用商城 API 全量抓取 95 款在售商品动销台账",
      downstreamTargets: ["#T-4 核心方案评估与决策"],
      endorsement: "监察评审核验通过",
    },
    run: { threadId: "thread-patrol-03", llmCalls: 3, inputTokens: 8200, outputTokens: 1400, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 调用 API 拉取商品台账", tool: "mall.list_all_products", detail: "全量抓取 95 款在售商品" },
      { label: "交叉对账近 30 天动销与库存周转", detail: "发现 12 款长尾商品动销停滞，占用橱窗位" },
      { label: "梳理引流梯度与价格带断层", detail: "发现 70-100 元中端区间缺乏主推盈利爆款" },
      { label: "输出商品健康度诊断报告", detail: "标记下架清理建议，腾出新品上架空间" },
    ],
    humanRequest: {
      id: "req-prop-03",
      type: "proposal",
      prompt: "Agent 主动提案：建议淘汰 12 款近 30 天零动销长尾商品，并为 ¥79-99 价格带新品让渡橱窗位与营销权重",
      context: "提案类型：商品矩阵淘汰与腾挪优化\n涉及影响：下架 12 款零动销长尾 SKU，腾挪出主力橱窗坑位\n预估效益：提升全店流量转化率约 15%\n背书机制：商城在售动销数据交叉对账通过",
      status: "waiting_human",
    },
    artifact: {
      id: "art-3",
      type: "report",
      title: "在售商品动销与健康度诊断",
      summary: "95 款在售商品中 12 款零动销，建议淘汰长尾并补充 79-99 元主推款。",
      body: "【在售商品巡检结论】\n· 动销状况：83 款正常流转，12 款近 30 天零动销。\n· 价格带断层：在售商品呈极化分布（¥39 低价与 ¥260 高端），缺失 70-100 元中坚爆款。\n· 优化决策：建议下架 12 款长尾，集中资源打造 79-99 元中坚主力品。",
    },
  },
  {
    id: "task-4",
    taskNo: 4,
    title: "核心方案决策：候选 SKU 综合评估 (商业拍板)",
    category: "strategy",
    status: "waiting_acceptance",
    priority: "urgent",
    riskLevel: "T1",
    source: "chain",
    stage: "方案拍板",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-1", "task-2", "task-3"],
    provenance: {
      sourceRef: "主线派生：聚合 #T-1、#T-2、#T-3 调研结果，推演候选落地方案",
      upstreamSummary: "融合竞品价格带 + IP 声量 + 商城缺口 3 份上游产物",
      downstreamTargets: ["#T-5 供应链准入", "#T-6 价格矩阵"],
      endorsement: "商业拍板人签字背书（人机协同门禁）",
    },
    run: { threadId: "thread-plan-04", llmCalls: 5, inputTokens: 16200, outputTokens: 3100, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 聚合 3 份上游数据 Payload", detail: "解包大盘调研、IP 声量及动销断层" },
      { label: "推演候选 SKU 定位与投入产出模型", detail: "构建 3 个差异化候选执行方向" },
      {
        label: "测算各方向预估毛利、客单价与风险点",
        detail: "方向① 52% / 方向② 38% / 方向③ 46%",
        thought: "综合对比，方向①「316医用不锈钢官方原画联名款」毛利达 52%，在用户情怀接纳度与供应链确定性上综合评分最高。",
      },
      { label: "生成方案选择卡 · 挂起等待人工拍板", detail: "触发商业决策拍板门禁，暂停自动派发" },
    ],
    humanRequest: {
      id: "req-choice-04",
      type: "choice",
      prompt: "商业决策拍板：请核定首期产品主推定位路线，确认后将解锁供应商准入与定价核算链路",
      context: "拍板类型：核心 SKU 产品线定型\n毛利预期：52% (方向①) vs 64% (方向②) vs 34% (方向③)\n推荐选项：方向① 316医用不锈钢 · 官方经典原画联名款\n前置事实：融合竞品大盘 + IP 声量 + 商城动销缺口",
      options: [
        "方向① 316医用不锈钢 · 官方经典原画联名款（推荐 · 预估毛利 52%）",
        "方向② 潮玩盲盒附赠 · 珍藏限量礼盒款（高客单 · 预估毛利 64%）",
        "方向③ 极简无印风 · 大容量车载便携杯（走量款 · 预估毛利 34%）",
      ],
      status: "waiting_human",
    },
    signoff: {
      prompt: "Agent 已完成 3 组候选方案测算。请确认最终主推方向，确认后将解锁供应链采购与定价链路：",
      pickedIndex: 0,
      rejectCount: 0,
      requiresHuman: true,
      options: [
        {
          label: "方向① 316医用不锈钢 · 官方经典原画联名款（推荐）",
          note: "客单价 ¥99，供应链成熟，原画版权合规，契合 25-35 岁白领日常通勤",
          margin: "52%",
          picked: true,
        },
        {
          label: "方向② 潮玩盲盒附赠 · 珍藏限量礼盒款",
          note: "客单价 ¥169，含实体手办周边，毛利丰厚但起订量门槛较高",
          margin: "64%",
          risk: "库存周转风险相对偏高",
          picked: false,
        },
        {
          label: "方向③ 极简无印风 · 大容量车载便携杯",
          note: "客单价 ¥59，走极致性价比走量路线，无 IP 溢价加持",
          margin: "34%",
          risk: "同质化竞争激烈，净利润空间薄弱",
          picked: false,
        },
      ],
    },
    artifact: {
      id: "art-4",
      type: "choice",
      title: "候选产品落地路线评估表",
      summary: "首选方向①「316医用不锈钢官方原画联名款」，兼顾毛利与放量规模。",
      options: [
        { label: "方向① 316医用不锈钢 · 官方原画联名款", note: "推荐款 · 预估毛利 52%", picked: true },
        { label: "方向② 珍藏限量礼盒款", note: "客单高 · 预估毛利 64%", picked: false },
        { label: "方向③ 极简无印车载款", note: "走量款 · 预估毛利 34%", picked: false },
      ],
    },
  },
  {
    id: "task-5",
    taskNo: 5,
    title: "供应链准入：厂家资质核验与打样选拔",
    category: "procurement",
    status: "pending",
    priority: "high",
    riskLevel: "T2",
    source: "chain",
    stage: "落地执行",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-4"],
    provenance: {
      sourceRef: "主线派生：注入 #T-4 选定的联名款工艺要求进行厂商准入",
      upstreamSummary: "承接 316 不锈钢 + 丝印工艺指标",
      downstreamTargets: ["#T-6 定价矩阵", "#T-7 知识底座"],
      endorsement: "监察评审核验厂商 ISO 与验厂报告",
    },
    run: { threadId: "thread-proc-05", llmCalls: 4, inputTokens: 11000, outputTokens: 1800, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 注入 #T-4 选定方案规格", detail: "获取 316 材质、500ml 容量技术参数" },
      { label: "检索认证供应商与验厂合规评分", tool: "b2b.search_suppliers", detail: "比对永康恒达、华康、晨越 3 家厂家" },
      { label: "核验报价底线、打样周期与起订量", detail: "晨越支持 100 件起订，交付周期 10 天" },
      { label: "输出供应商选拔报告与推荐结论", detail: "推荐晨越以控制前期试销压货风险" },
    ],
    artifact: {
      id: "art-5",
      type: "report",
      title: "供应链准入与核价报告",
      summary: "推荐晨越科技作为首发供应商：打样周期 7 天，首批 100 件柔性起订。",
      body: "【供应商比选结果】\n· 首选合作方：晨越科技（浙江永康，通过 ISO9001 认证）。\n· 拿货底价：裸杯 ¥24.5 + 丝印工艺 ¥2.0 + 环保内衬礼盒 ¥3.2。\n· 交付柔性：支持 100 件小批量追单，交期 10 个工作日。\n· 品控承诺：316 内胆第三方抽检光谱报告齐备，破损包退换。",
    },
  },
  {
    id: "task-6",
    taskNo: 6,
    title: "定价策略矩阵：三档 SKU 阶梯毛利核算",
    category: "pricing",
    status: "pending",
    priority: "high",
    riskLevel: "T2",
    source: "chain",
    stage: "落地执行",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-5"],
    provenance: {
      sourceRef: "主线派生：结合供应链成本底价倒推三档售价结构",
      upstreamSummary: "#T-4 定位 + #T-5 采购成本（基础底价 ¥26.5）",
      downstreamTargets: ["#T-7 知识底座", "#T-10 线上商城发布"],
      endorsement: "财务风控合规模型核验通过",
    },
    run: { threadId: "thread-price-06", llmCalls: 4, inputTokens: 10400, outputTokens: 2200, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 汇入工厂采购与包装物流成本", detail: "基础底价 ¥26.5 + 耗材 ¥3.2 + 运费 ¥4.5" },
      {
        label: "倒推三档 SKU 定价与阶梯毛利矩阵",
        detail: "单杯 ¥79 / 联名款 ¥99 / 礼盒款 ¥169",
        thought: "以 ¥79 基础款守住入门底线，¥99 联名款作为主推盈利款，¥169 礼盒款拉高客单，形成稳健的阶梯价格带。",
      },
      { label: "测算各渠道投流保本线与返点空间", detail: "主推款净毛利充足，能够安全支撑早期付费获客" },
      { label: "输出定价策略矩阵表", detail: "核算完毕，固化为结构化数据" },
    ],
    artifact: {
      id: "art-6",
      type: "matrix",
      title: "三档阶梯定价与利润测算表",
      summary: "单杯 ¥79 (毛利52%) / 联名款 ¥99 (毛利61%) / 礼盒款 ¥169 (毛利68%)。",
      matrixData: [
        { tier: "基础通勤款 (单杯)", cost: "¥26.50", price: "¥79.00", margin: "52.4%", note: "跑量引流主力，守住入门门槛" },
        { tier: "IP 联名典藏款", cost: "¥29.70", price: "¥99.00", margin: "61.2%", note: "主推利润爆款，承接核心转化" },
        { tier: "高端定制商务礼盒", cost: "¥43.20", price: "¥169.00", margin: "68.5%", note: "拉高客单价，主攻送礼节日场景" },
      ],
    },
  },
  {
    id: "task-7",
    taskNo: 7,
    title: "商品知识底座：标准参数与 8 组售后 FAQ",
    category: "knowledge",
    status: "pending",
    priority: "medium",
    riskLevel: "T3",
    source: "chain",
    stage: "落地执行",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-6"],
    provenance: {
      sourceRef: "主线派生：整合产品材质规范与定价策略，建立统一事实真理源",
      upstreamSummary: "承接 #T-5 材质标准与 #T-6 SKU 矩阵",
      downstreamTargets: ["#T-8 视觉素材", "#T-9 宣发文案", "#T-13 客服巡查"],
      endorsement: "监察评审事实一致性核验通过",
    },
    run: { threadId: "thread-know-07", llmCalls: 4, inputTokens: 12000, outputTokens: 2500, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 组装参数规格与工艺细节", detail: "确定 500ml / 316 医用内胆等参数" },
      { label: "提炼核心用户卖点与情感连接", detail: "国风联名原画 × 12h 实测长效锁温" },
      { label: "撰写标准化客服与用户问答 8 条 FAQ", detail: "覆盖防漏、清洗、碳酸咖啡兼容、售后质保" },
      { label: "沉淀为全局商品知识标准事实底座", detail: "作为后续图文与上架的唯一事实参考源" },
    ],
    artifact: {
      id: "art-7",
      type: "report",
      title: "商品标准化知识卡与 FAQ 矩阵",
      summary: "涵盖材质、温控实验数据及 8 条标准化客服防杠问答手册。",
      body: "【标准事实真理源】\n· 规格参数：容量 500ml / 净重 285g / 材质 316 医用不锈钢内胆 + 食品级 PP 杯盖。\n· 温控指标：95℃ 沸水注入，实测 6h 保温 ≥ 68℃，12h 保温 ≥ 45℃。\n· 核心 FAQ：① 是否支持装碳酸/咖啡？支持，316 材质耐腐蚀；② 密封性能如何？倒置剧烈摇晃 0 渗漏；③ 售后政策：7 天无理由 + 365 天内胆质保。",
    },
  },
  {
    id: "task-8",
    taskNo: 8,
    title: "高保真视觉资产：白底主图与 4 组场景渲染",
    category: "creative",
    status: "waiting_acceptance",
    priority: "high",
    riskLevel: "T2",
    source: "chain",
    stage: "宣发上线",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-7"],
    provenance: {
      sourceRef: "主线派生：依据 #T-7 知识底座的视觉规范生成全套商城素材",
      upstreamSummary: "#T-7 核心视觉标准：白底主图规范、生活场景融合",
      downstreamTargets: ["#T-9 宣发文案", "#T-10 线上商城发布"],
      endorsement: "监察评审（图像分辨率与合规预检通过）",
    },
    run: { threadId: "thread-img-08", llmCalls: 6, inputTokens: 15400, outputTokens: 2800, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 读取视觉规范标准", detail: "解析白底主图与生活场景图构图规格" },
      { label: "调用图像引擎生成白底主图", tool: "image.generate_asset", detail: "生成 1080x1080 商业白底主图" },
      { label: "生成办公桌面与车载杯架生活实景图", tool: "image.render_scene", detail: "展现日常真实使用光影与质感" },
      { label: "图像合规与清晰度预检完成", detail: "4 张素材全部通过审核并落库" },
    ],
    humanRequest: {
      id: "req-acc-08",
      type: "acceptance",
      prompt: "成果验收：请审核高保真商用素材画廊 (4 组 1080×1080 渲染素材)，验收通过后方可合流发布",
      context: "验收类型：商用素材质量验收\n包含资产：白底主图 + 办公实景 + 车载实测 + 礼盒氛围 4 组渲染图\n质检指标：清晰度 1080×1080 / 色彩合规 / 0违规元素\n下游去向：#T-9 宣发文案、#T-10 线上商城正式发布",
      status: "waiting_human",
    },
    artifact: {
      id: "art-8",
      type: "gallery",
      title: "高保真商用素材画廊",
      summary: "生成 4 组分辨率 1080x1080 质检通过的高清实拍与场景图。",
      images: [
        { id: "img-1", hue: 215, label: "白底商品主图 (1080×1080)" },
        { id: "img-2", hue: 275, label: "办公桌面原画联名场景图" },
        { id: "img-3", hue: 35, label: "车载杯架单手操作实测视角" },
        { id: "img-4", hue: 155, label: "礼盒包装开箱高档送礼氛围" },
      ],
    },
  },
  {
    id: "task-9",
    taskNo: 9,
    title: "宣发文案矩阵：高转化标题与 5 维卖点拆解",
    category: "marketing",
    status: "pending",
    priority: "medium",
    riskLevel: "T2",
    source: "chain",
    stage: "宣发上线",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-8"],
    provenance: {
      sourceRef: "主线派生：整合 #T-7 知识底座与 #T-8 视觉素材产出正式营销文案",
      upstreamSummary: "图文结合：标题权重优化 + 痛点卖点拆解",
      downstreamTargets: ["#T-10 线上商城发布", "#T-11 社媒矩阵发布"],
      endorsement: "监察评审（广告法合规过滤已通过）",
    },
    run: { threadId: "thread-copy-09", llmCalls: 4, inputTokens: 13200, outputTokens: 3400, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 抓取搜索热词与卖点规范", detail: "匹配高频热词：锁温、车载、办公、礼盒" },
      { label: "生成电商高转化 SEO 主副标题", detail: "兼顾平台自然流量分发与用户点击率" },
      { label: "撰写 5 维详情页痛点营销卖点排", detail: "情怀触达 → 材质实测 → 场景匹配 → 质保" },
      { label: "广告法与违禁词自动化过滤核验", tool: "compliance.text_filter", detail: "文案合规校验通过，准备发布" },
    ],
    artifact: {
      id: "art-9",
      type: "copy",
      title: "电商全渠道文案成稿",
      summary: "SEO 黄金主标题 + 5 维痛点详情排版 + 社交短文案。",
      body: "【主标题】梦幻西游官方联名不锈钢保温杯 316医用内胆 12h长效锁温车载防漏办公礼盒装\n\n【核心卖点矩阵】\n1. 官方原画联名：情怀触达，经典国风哑光工艺，彰显个性品位\n2. 医用级 316 材质：耐酸碱防腐蚀，茶水、咖啡安心随心装\n3. 12h 实测锁温：清晨沸水注入，黄昏依然温热可口\n4. 剧烈摇晃不漏：食品级硅胶密封圈，适配 99% 车载杯架\n5. 一年换新无忧：30 天无理由换新，质保安心售后",
    },
  },
  {
    id: "task-10",
    taskNo: 10,
    title: "商城正式上架：API 创建商品与多 SKU 挂载",
    category: "deployment",
    status: "pending",
    priority: "high",
    riskLevel: "T1",
    source: "chain",
    stage: "宣发上线",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-9"],
    provenance: {
      sourceRef: "主线派生：将定价、图文全量数据打包，写入线上在售数据库",
      upstreamSummary: "#T-6 价格矩阵 + #T-8 主图切片 + #T-9 营销文案",
      downstreamTargets: ["#T-11 社媒矩阵发布", "#T-12 投流测试", "#T-13 客服巡查", "#T-14 转化复盘"],
      endorsement: "商城 check_only 预检通过 + 监察评审落库核验",
    },
    run: { threadId: "thread-mall-10", llmCalls: 4, inputTokens: 14800, outputTokens: 2900, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 组装商城商品创建请求 Payload", detail: "打包 SKU、主图、文案全量字段" },
      { label: "执行 check_only 模拟预检", tool: "mall.precheck_product", detail: "参数核验无误，运费模板绑定成功" },
      { label: "正式调用接口创建商品与多 SKU", tool: "mall.create_product", detail: "商品成功写入线上在售数据库" },
      { label: "回查详情确认落库展示链接生效", tool: "mall.verify_listing", detail: "线上商品状态已顺利激活上线" },
    ],
    artifact: {
      id: "art-10",
      type: "report",
      title: "商城上架与商品库写入报告",
      summary: "商品已通过预检并写入数据库，三档 SKU 各 200 件库存分配完毕。",
      body: "【商城上架报告】\n✓ 参数一致性校验：容量 500ml / 材质 316 / 颜色 2 款全部通过\n✓ 素材完整性校验：主图 4 张 + 详情长图已成功挂载 CDN\n✓ SKU 挂载详情：单杯 ¥79 / 联名款 ¥99 / 礼盒款 ¥169\n✓ 运费模板：全国包邮（偏远区域除外）\n✓ 状态：已调用 mall.create_product 成功激活",
    },
  },
  {
    id: "task-11",
    taskNo: 11,
    title: "社媒矩阵宣发：多渠道种草笔记与首发分发",
    category: "social",
    status: "pending",
    priority: "medium",
    riskLevel: "T2",
    source: "chain",
    stage: "运营转化",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-10"],
    provenance: {
      sourceRef: "主线派生：依据 #T-10 线上商品链接与 #T-9 文案矩阵进行社媒分发",
      upstreamSummary: "获取正式商品专属推广短链与高清场景实拍图",
      downstreamTargets: ["#T-12 投流测试"],
      endorsement: "社媒平台草稿箱审核 + 监察评审通过",
    },
    run: { threadId: "thread-social-11", llmCalls: 4, inputTokens: 11500, outputTokens: 2300, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 关联线上正式商品链接", detail: "获取推广专属短链与追踪参数" },
      { label: "生成小红书种草笔记双版本", detail: "办公白领好物向 + 极限 12h 实测硬核向" },
      { label: "生成闲鱼特惠专区转单文案", detail: "全域多渠道内容分发矩阵准备完毕" },
      { label: "定时推送至分发草稿箱待发布", detail: "触发首发社媒预热" },
    ],
    artifact: {
      id: "art-11",
      type: "copy",
      title: "全域社媒种草内容包",
      summary: "小红书爆款图文 2 篇 + 微信私域朋友圈文案 3 条。",
      body: "【小红书种草笔记】\n标题：办公桌上的私藏神物！这个联名保温杯也太戳我了…\n正文：经常忙起来忘记喝水，下午想喝一口温水太难了！最近入手的这个 316 联名保温杯真的惊艳，颜值高级不张扬，放桌上赏心悦目。重点是 12h 实测保温，早上的温热水到下班还是热的，密封绝绝子完全不漏！办公通勤人闭眼冲！",
    },
  },
  {
    id: "task-12",
    taskNo: 12,
    title: "冷启动投流测试：小额预算划拨 (HITL 资金门禁)",
    category: "finance",
    status: "confirm",
    priority: "high",
    riskLevel: "T1",
    source: "chain",
    stage: "运营转化",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-11"],
    provenance: {
      sourceRef: "主线派生：为新上架 SKU 划拨冷启动测款预算，触发资金安全门禁",
      upstreamSummary: "基于 #T-10 商品链接与 #T-11 社媒测试内容发起小额试销",
      downstreamTargets: ["#T-14 转化复盘"],
      endorsement: "用户资金安全授权放行 (HITL 门禁)",
    },
    run: { threadId: "thread-ad-12", llmCalls: 4, inputTokens: 12200, outputTokens: 2100, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 规划测试组与受众定向", detail: "圈选 25-35 岁高潜办公客群" },
      { label: "生成投流素材组合与 A/B 计划", detail: "计划 A (白领生活) vs 计划 B (功能硬测)" },
      { label: "预算支出审批门禁挂起", detail: "单次支出 ¥200.00，挂起等待用户授权放行" },
      { label: "调用广告接口启动测试组", tool: "ads.launch_campaign", detail: "资金授权通过后自动划拨启动" },
    ],
    hitl: {
      pending: true,
      requestId: "hitl-ad-001",
      action: "广告账户小额扣费",
      description: "冷启动投流预算支出 ≤ ¥200.00，用于 48 小时定向测款验证转化率",
      budget: "¥200.00",
    },
    humanRequest: {
      id: "req-hitl-12",
      type: "approval",
      prompt: "资金安全授权：冷启动投流测试需要划拨测试预算 ¥200.00，请确认审批放行",
      context: "风险等级：高风险资金出账 (T1)\n操作类型：广告账户小额扣费\n扣款主体：巨量千川 / 小红书聚光推广账户\n预算上限：¥200.00 (实付)\n测试周期：48 小时 A/B 计划小额测款",
      status: "waiting_human",
    },
    artifact: {
      id: "art-12",
      type: "funnel",
      title: "冷启动投流转化测试漏斗",
      summary: "预算 ¥200.00，曝光 8,500，预估点击率 3.8%，加购率 15.2%。",
      funnel: [
        { label: "广告曝光量 (Impression)", value: "8,500 次", pct: 100 },
        { label: "点击进店 (Clicks)", value: "323 次 (CTR 3.8%)", pct: 38 },
        { label: "加入购物车 (Cart Add)", value: "49 次 (加购率 15.2%)", pct: 15 },
        { label: "支付转化 (Orders)", value: "12 单 (ROI 2.8)", pct: 4 },
      ],
    },
  },
  {
    id: "task-13",
    taskNo: 13,
    title: "智能客服巡查：话术规则注入与售后异常监听",
    category: "service",
    status: "pending",
    priority: "medium",
    riskLevel: "T3",
    source: "chain",
    stage: "运营转化",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-10"],
    provenance: {
      sourceRef: "主线派生：将知识底座与在售商品挂接至客服智能体，开启在线值守",
      upstreamSummary: "获取 #T-7 标准 FAQ 库与 #T-10 订单路由",
      downstreamTargets: ["#T-15 闭环反哺"],
      endorsement: "客服系统质检规则验证通过",
    },
    run: { threadId: "thread-cs-13", llmCalls: 3, inputTokens: 9600, outputTokens: 1800, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 挂接商品知识底座至客服大脑", detail: "载入材质说明、清洗方法及质保政策" },
      { label: "注入自动应答逻辑与差评预警阈值", detail: "设置敏感词拦截与售后极速补发规则" },
      { label: "模拟 20 组复杂客诉压力测试", detail: "应答准确率达到 98.5%，符合上线标准" },
      { label: "正式激活 7×24h 智能客服托管", detail: "全链路售后保障就绪" },
    ],
    artifact: {
      id: "art-13",
      type: "report",
      title: "客服智能托管规则配置清单",
      summary: "已载入 8 组高频 FAQ，配置 7×24h 极速应答与差评预警机制。",
      body: "【客服值守规则部署】\n· 响应时效：常规咨询 ≤ 3 秒自动回复；客诉问题 30 秒内安抚并升级。\n· 质保承诺：支持 7 天无理由退换货；漏水等质量问题无需寄回极速补发。\n· 压力测试指标：应答符合度 98.5%，情感适度评分 4.9/5.0。",
    },
  },
  {
    id: "task-14",
    taskNo: 14,
    title: "业务转化复盘：全链路 ROI 测算与归因分析",
    category: "analytics",
    status: "pending",
    priority: "high",
    riskLevel: "T2",
    source: "chain",
    stage: "复盘归档",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-12"],
    provenance: {
      sourceRef: "主线派生：汇总线上在售订单、投流消耗与转化数据完成首期复盘",
      upstreamSummary: "#T-10 销售台账 + #T-12 广告消耗数据归集",
      downstreamTargets: ["#T-15 闭环反哺"],
      endorsement: "监察评审归因事实对账核验",
    },
    run: { threadId: "thread-ana-14", llmCalls: 4, inputTokens: 13800, outputTokens: 2600, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 抓取线上实际成交与投流账单", detail: "归集测试期 72 小时运营全量流水" },
      { label: "测算毛利留存、客单价与最终 ROI", detail: "测算出整体投产比达到 1:3.2" },
      { label: "分析用户评价反馈与加购行为漏斗", detail: "白领礼盒款占比高达 42%，超出预期" },
      { label: "输出转化复盘与经营效益归因简报", detail: "数据回流入库，完成对账" },
    ],
    artifact: {
      id: "art-14",
      type: "funnel",
      title: "72 小时全链路转化漏斗",
      summary: "累计销售 68 单，成交总额 ¥7,120.00，整体 ROI 达到 3.2。",
      funnel: [
        { label: "总访客数 (UV)", value: "2,460 人", pct: 100 },
        { label: "深度浏览商品 (Detail View)", value: "1,180 人 (48%)", pct: 48 },
        { label: "加购/收藏 (Engaged)", value: "246 人 (10%)", pct: 21 },
        { label: "完成支付 (Paid Orders)", value: "68 单 (转化率 2.8%)", pct: 6 },
      ],
    },
  },
  {
    id: "task-15",
    taskNo: 15,
    title: "自进化反哺：经营知识库更新与 Agent 策略调优",
    category: "strategy",
    status: "pending",
    priority: "medium",
    riskLevel: "T3",
    source: "chain",
    stage: "复盘归档",
    x: 0,
    y: 0,
    w: 340,
    dependencies: ["task-13", "task-14"],
    provenance: {
      sourceRef: "主线派生：基于客服真实问答与实际成交数据，反哺 Agent 长期记忆",
      upstreamSummary: "聚合全链路最后一公里真实经营数据",
      downstreamTargets: ["终局闭环 · 沉淀为下一周期初始资产"],
      endorsement: "系统自动完成归档对账",
    },
    run: { threadId: "thread-strat-15", llmCalls: 3, inputTokens: 11200, outputTokens: 2400, toolErrors: 0 },
    steps: [
      { label: "take 任务 · 汇总客服高频追问与退换货特征", detail: "用户对清洗内胆死角关注度较高" },
      { label: "沉淀 2 项新设计标准至选品经验库", detail: "后续新品增加广口径杯底易清洗规范" },
      { label: "微调未来周期投流推荐算法权重", detail: "调高办公白领与节日礼盒定向权重" },
      { label: "完成全链路长程值守任务终态闭环归档", detail: "全流程圆满交付，系统待命中" },
    ],
    artifact: {
      id: "art-15",
      type: "report",
      title: "自主值守全链路归档与经验反哺报告",
      summary: "经验已沉淀为全局长期记忆，为下一轮选品迭代提供优化基准。",
      body: "【经营知识自进化总结】\n· 成功要素：IP 经典原画赋能 + 316 材质真材实料 + 阶梯定价模型有效承接高客单礼盒需求。\n· 待优化项：包装盒内部可附赠定制杯刷，进一步提升拆箱好感度。\n· 资产固化：全套视觉主图、文案、供应商准入台账与定价模型已全部安全归档至 EvoLoop 知识金库。",
    },
  },
]

export const INITIAL_DUTY_NOTIFICATIONS: DutyNotification[] = [
  {
    id: "notif-1",
    time: "10:15",
    taskId: "task-4",
    taskNo: 4,
    type: "signoff",
    title: "商业拍板待办：#T-4 核心方案决策",
    content: "316 联名款与礼盒款评估已就绪，请在画布节点内确认主推方向。",
    read: false,
  },
  {
    id: "notif-2",
    time: "10:12",
    taskId: "task-3",
    taskNo: 3,
    type: "signoff",
    title: "Agent 主动提案：#T-3 长尾商品淘汰腾挪",
    content: "Agent 建议淘汰 12 款零动销商品，请确认是否采纳并加入队列。",
    read: false,
  },
  {
    id: "notif-3",
    time: "10:10",
    taskId: "task-12",
    taskNo: 12,
    type: "hitl",
    title: "资金安全审批提醒：#T-12 投流测试",
    content: "小额投流预算支出申请已生成（¥200.00），等待安全授权放行。",
    read: false,
  },
  {
    id: "notif-4",
    time: "10:08",
    taskId: "task-8",
    taskNo: 8,
    type: "signoff",
    title: "成果质量验收：#T-8 商用素材画廊",
    content: "4 组 1080×1080 渲染素材已生成，等待成果验收通过。",
    read: false,
  },
]
